### ISSUE TITLE
Entity metadata type should be a varint, not a byte

### ISSUE THREAD

**Issue by msf567** [PrismarineJS/mineflayer#1002]
- mineflayer: 2.15.0
 - server: PaperSpigot 1.15.2
 - node:10.16.3

## Detailed description of a problem
Upon calling bot.chat ('message') the following error is thrown:

**Error: Deserialization error for play.toClient.entity_metadata.metadata.value : Read error for params.entity_metadata.metadata.value : -84 has no associated fieldInfo in switch**
    at ProtoDef.readSwitch (A:\MinecraftBots\node_modules\protodef\src\datatypes\conditional.js:10:90)
    at ProtoDef.read (A:\MinecraftBots\node_modules\protodef\src\protodef.js:36:25)
    at ProtoDef.read (A:\MinecraftBots\node_modules\protodef\src\protodef.js:110:29)
    at A:\MinecraftBots\node_modules\protodef\src\datatypes\structures.js:45:32
    at tryCatch (A:\MinecraftBots\node_modules\protodef\src\utils.js:50:16)
    at tryDoc (A:\MinecraftBots\node_modules\protodef\src\utils.js:54:10)
    at A:\MinecraftBots\node_modules\protodef\src\datatypes\structures.js:44:5
    at Array.forEach (<anonymous>)
    at ProtoDef.readContainer (A:\MinecraftBots\node_modules\protodef\src\datatypes\structures.js:43:12)
    at ProtoDef.read (A:\MinecraftBots\node_modules\protodef\src\protodef.js:110:29) {
  field: 'play.toClient.entity_metadata.metadata.value'

## Current code
```js
bot.on('chat', (username, message) => {
  if (username === bot.username) return
  if(message == 'whos online')
  Object.keys(bot.players).forEach(player => {
    bot.chat(bot.players[player].username + ' is online')
  });
```

## Expected behavior
The chat posts in-game with no errors in console

**Comment by msf567** [comment]
This is caused by the plugin 'LightChatBubbles' which was running on the server. The errors seem to be benign, but throw every time a chat message is de-serialized by the client

**Comment by Karang** [comment]
Looking quickly at https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.15.2/protocol.json#L255 it seems that the entity metadata is wrongly described.
According to https://wiki.vg/Entity_metadata#Entity_Metadata_Format the type should be a varint and not a signed byte.

**Comment by rom1504** [comment]
I looked at the revision history of this page and it was introduced in 1.13 
All previous versions use a byte.
Interesting that we missed that. I guess only non vanilla use big type values.

Well it will be an easy fix.

**Comment by rom1504** [comment]
now fixed, just run `npm update --depth 9999`
