### ISSUE TITLE
How can I make the bot click on a block?

### ISSUE THREAD

**Issue by ycesinha-schneider** [PrismarineJS/mineflayer#1010]
How can I make the bot click on a block? (bot for rankup machine) In case I want it to click on the machine (block is a sponge)

**Comment by Karang** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botactivateblockblock-callback ?

**Comment by ycesinha-schneider** [comment]
@Karang 
C:\Users\Césinha\Downloads\karma\node_modules\mineflayer\lib\plugins\inventory.js:175
    bot.lookAt(block.position.offset(0.5, 0.5, 0.5), false, () => {
                              ^

TypeError: Cannot read property 'offset' of undefined
    at Bot.activateBlock (C:\Users\Césinha\Downloads\karma\node_modules\mineflayer\lib\plugins\inventory.js:175:31)
    at Client.<anonymous> (C:\Users\Césinha\Downloads\karma\main.js:33:25)
    at Client.emit (events.js:310:20)
    at MessageCreateHandler.handle (C:\Users\Césinha\Downloads\karma\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Césinha\Downloads\karma\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (C:\Users\Césinha\Downloads\karma\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (C:\Users\Césinha\Downloads\karma\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:17)
    at WebSocket.onMessage (C:\Users\Césinha\Downloads\karma\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:310:20)
    at Receiver.receiverOnMessage (C:\Users\Césinha\Downloads\karma\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:310:20)
    at Receiver.dataMessage (C:\Users\Césinha\Downloads\karma\node_modules\ws\lib\receiver.js:422:14)
    at Receiver.getData (C:\Users\Césinha\Downloads\karma\node_modules\ws\lib\receiver.js:352:17)
    at Receiver.startLoop (C:\Users\Césinha\Downloads\karma\node_modules\ws\lib\receiver.js:138:22)
    at Receiver._write (C:\Users\Césinha\Downloads\karma\node_modules\ws\lib\receiver.js:74:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Receiver.Writable.write (_stream_writable.js:318:11)
    at TLSSocket.socketOnData (C:\Users\Césinha\Downloads\karma\node_modules\ws\lib\websocket.js:864:35)
    at TLSSocket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by Karang** [comment]
The problem is in your code. The block you give as a parameter should have a position property.

**Comment by ycesinha-schneider** [comment]
@Karang Is correct? bot.lookAt("-102 62 254")

**Comment by rom1504** [comment]
No, look at take a Vec3 instance

**Comment by ycesinha-schneider** [comment]
bot.lookAt(block.position.offset(0.5, 0.5, 0.5), false, () => {
                              ^

TypeError: Cannot read property 'offset' of undefined
    at Bot.activateBlock (C:\Users\Césinha\Downloads\karma\node_modules\mineflayer\lib\plugins\inventory.js:175:31)
    at Client.<anonymous> (C:\Users\Césinha\Downloads\karma\main.js:37:25)
    at Client.emit (events.js:310:20)
    at MessageCreateHandler.handle (C:\Users\Césinha\Downloads\karma\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Césinha\Downloads\karma\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (C:\Users\Césinha\Downloads\karma\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (C:\Users\Césinha\Downloads\karma\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:17)
    at WebSocket.onMessage (C:\Users\Césinha\Downloads\karma\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:310:20)
    at Receiver.receiverOnMessage (C:\Users\Césinha\Downloads\karma\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:310:20)
    at Receiver.dataMessage (C:\Users\Césinha\Downloads\karma\node_modules\ws\lib\receiver.js:422:14)
    at Receiver.getData (C:\Users\Césinha\Downloads\karma\node_modules\ws\lib\receiver.js:352:17)
    at Receiver.startLoop (C:\Users\Césinha\Downloads\karma\node_modules\ws\lib\receiver.js:138:22)
    at Receiver._write (C:\Users\Césinha\Downloads\karma\node_modules\ws\lib\receiver.js:74:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Receiver.Writable.write (_stream_writable.js:318:11)
    at TLSSocket.socketOnData (C:\Users\Césinha\Downloads\karma\node_modules\ws\lib\websocket.js:864:35)
    at TLSSocket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)

@rom1504 code:

 bot.lookAt(v("-103", "62", "254"))
                    bot.activateBlock('64') = id 64 = door

**Comment by rom1504** [comment]
Yeah I already answered.
You need to use the API.
The computer doesn't do what you think, it can only do what you write.

Look at the API and examples

**Comment by ycesinha-schneider** [comment]
@rom1504 i used a api "vec3"

**Comment by ycesinha-schneider** [comment]
@rom1504 Hello, i found a code for this, but I don't know what to put in the Class phase

Code:

bot.openBlock()

**Comment by ImHarvol** [comment]
If you want to Punch a note block, open a door, etc, use [bot.activateBlock(block, [callback])
](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botactivateblockblock-callback)
```js
bot.activateBlock(bot.blockAt(vec3(-102, 62, 254)), () => {
  console.log('Done!')
})
```
I think it also works for opening chests.

---

I don't see why whould you use [bot.openBlock(block, Class)](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botopenblockblock-class) but some classes are: mineflayer.Dispenser, mineflayer.Chest, mineflayer.EnchantmentTable and mineflayer.Furnace

**Comment by rom1504** [comment]
Solved
