### ISSUE TITLE
PartialReadError: Deserialization error for play.toClient 

### ISSUE THREAD

**Issue by Thomas-Vos00** [PrismarineJS/mineflayer#1016]
## Versions
 - mineflayer: latest
 - server: vanilla/spigot/paper unknown
 - node: 12.17.0

## Detailed description of a problem
A clear and concise description of what the problem is.

When trying to join the subserver creative on play.minesuperior.com using /gserver ms-creative-1 I get the following error:

PartialReadError: Deserialization error for play.toClient : Read error for undefined : Missing characters in string, found size is 40761 expected size was 3325017

This error occurs as soon as u join the subserver. The bot does actually join creative for a bit.

## Current code
```js
var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
  host: "play.minesuperior.com", // optional
  port: 25565,       // optional
  username: "username", // email and password are required only for
  password: 'password',          // online-mode=true servers
  version: '1.14.4'                 // false corresponds to auto version detection (that's the default), put for example "1.8.8" if you need a specific version
});

function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
  

bot.once('login', function() {
    console.log("Bot has logged in");
    
});
bot.once('spawn', () => {
    console.log('spawned')
    sleep(2000).then(()=>bot.chat('/gserver ms-survival-1'))
})
bot.on('end',function(){
    console.log('ending')
})
bot.on('chat', function(username, message) {
  if (username === bot.username) return;
  console.log(message)
});
bot.on('kicked',() => console.log('igotkicked'))
bot.on('error', err => console.log(err))
````

**Comment by rom1504** [comment]
Can you put the full error

**Comment by Thomas-Vos00** [comment]
PartialReadError: Deserialization error for play.toClient : Read error for undefined : Missing characters in string, found size is 40761 expected size was 3325017
    at new ExtendableError (C:\Users\thoma\Desktop\guessbot\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (C:\Users\thoma\Desktop\guessbot\node_modules\protodef\src\utils.js:70:5)
    at Object.string (eval at compile (C:\Users\thoma\Desktop\guessbot\node_modules\protodef\src\compiler.js:289:12), <anonymous>:48:15)
    at eval (eval at compile (C:\Users\thoma\Desktop\guessbot\node_modules\protodef\src\compiler.js:289:12), <anonymous>:1686:65)
    at eval (eval at compile (C:\Users\thoma\Desktop\guessbot\node_modules\protodef\src\compiler.js:289:12), <anonymous>:1764:11)
    at Object.packet_declare_recipes (eval at compile (C:\Users\thoma\Desktop\guessbot\node_modules\protodef\src\compiler.js:289:12), <anonymous>:1769:9)
    at eval (eval at compile (C:\Users\thoma\Desktop\guessbot\node_modules\protodef\src\compiler.js:289:12), <anonymous>:1916:70)
    at packet (eval at compile (C:\Users\thoma\Desktop\guessbot\node_modules\protodef\src\compiler.js:289:12), <anonymous>:1921:9)
    at CompiledProtodef.read (C:\Users\thoma\Desktop\guessbot\node_modules\protodef\src\compiler.js:110:12)
    at e.message (C:\Users\thoma\Desktop\guessbot\node_modules\protodef\src\compiler.js:145:49)
    at tryCatch (C:\Users\thoma\Desktop\guessbot\node_modules\protodef\src\utils.js:50:16)
    at CompiledProtodef.parsePacketBuffer (C:\Users\thoma\Desktop\guessbot\node_modules\protodef\src\compiler.js:145:29)
    at FullPacketParser.parsePacketBuffer (C:\Users\thoma\Desktop\guessbot\node_modules\protodef\src\serializer.js:67:23)
    at FullPacketParser._transform (C:\Users\thoma\Desktop\guessbot\node_modules\protodef\src\serializer.js:73:21)
    at FullPacketParser.Transform._read (C:\Users\thoma\Desktop\guessbot\node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at FullPacketParser.Transform._write (C:\Users\thoma\Desktop\guessbot\node_modules\readable-stream\lib\_stream_transform.js:164:83)
    at doWrite (C:\Users\thoma\Desktop\guessbot\node_modules\readable-stream\lib\_stream_writable.js:409:139)
    at writeOrBuffer (C:\Users\thoma\Desktop\guessbot\node_modules\readable-stream\lib\_stream_writable.js:398:5)
    at FullPacketParser.Writable.write (C:\Users\thoma\Desktop\guessbot\node_modules\readable-stream\lib\_stream_writable.js:307:11)
    at Decompressor.ondata (C:\Users\thoma\Desktop\guessbot\node_modules\readable-stream\lib\_stream_readable.js:681:20)
    at Decompressor.emit (events.js:315:20)
    at addChunk (C:\Users\thoma\Desktop\guessbot\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\thoma\Desktop\guessbot\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at Decompressor.Readable.push (C:\Users\thoma\Desktop\guessbot\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at Decompressor.Transform.push (C:\Users\thoma\Desktop\guessbot\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at Unzip.cb (C:\Users\thoma\Desktop\guessbot\node_modules\minecraft-protocol\src\transforms\compression.js:69:14)
    at Unzip.zlibBufferOnEnd (zlib.js:149:10)
    at Unzip.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  partialReadError: true,
  field: 'play.toClient'
}

**Comment by Thomas-Vos00** [comment]
By the way! in the code I have ms-survival-1 I see now.. survival has the same error as creative so it doesn't matter. Just so u know!

Also: Do not join ms-kitpvp-1!!!! it will get ur acc banned. The bot does not give an error tho!

**Comment by rom1504** [comment]
It seems like a server bug, not sure what we should do about it.

**Comment by hiiminit** [comment]
Had same issue, when changed version in code from 1.15.2 to 1.12.2 error went away.
