### ISSUE TITLE
Inventory.js    TypeError: Cannot read property 'fishing_bobber' of undefined

### ISSUE THREAD

**Issue by MikeMottonix** [PrismarineJS/mineflayer#1017]
What can i do?
node version is 14.3.0
the code:

/*
 * This is one of the simplest examples.
 *
 * We created a simple bot that echoes back everything that is said on chat.
 *
 * It's not very useful yet, but you can use this as a starting point
 * to create your own bot.
 */
const mineflayer = require('mineflayer')

//if (process.argv.length < 4 || process.argv.length > 6) {
//  console.log('Usage : node echo.js <host> <port> [<name>] [<password>]')
//  process.exit(1)
//}

const bot = mineflayer.createBot({
  host: "SERVER",
  port: 25565,
  username: "EMAIL",
  password: "PASSWORD",
  version: 1.15
})
bot.on('chat', (username, message) => {
  if (username === bot.username) return
  console.log(message)
})

**Comment by MikeMottonix** [comment]
The Error:

MC-Hacks/bot/node_modules/mineflayer/lib/plugins/inventory.js:20
    bobberId = mcData.entitiesByName.fishing_bobber.id
                                     ^

TypeError: Cannot read property 'fishing_bobber' of undefined
    at inject (/home/enzo/MC-Hacks/bot/node_modules/mineflayer/lib/plugins/inventory.js:20:38)
    at /home/enzo/MC-Hacks/bot/node_modules/mineflayer/lib/plugin_loader.js:26:7
    at Array.forEach (<anonymous>)
    at injectPlugins (/home/enzo/MC-Hacks/bot/node_modules/mineflayer/lib/plugin_loader.js:25:13)
    at Bot.onInjectAllowed (/home/enzo/MC-Hacks/bot/node_modules/mineflayer/lib/plugin_loader.js:12:5)
    at Object.onceWrapper (events.js:421:28)
    at Bot.emit (events.js:315:20)
    at next (/home/enzo/MC-Hacks/bot/node_modules/mineflayer/index.js:119:12)
    at Bot.connect (/home/enzo/MC-Hacks/bot/node_modules/mineflayer/index.js:107:37)
    at Object.createBot (/home/enzo/MC-Hacks/bot/node_modules/mineflayer/index.js:81:7)
    at Object.<anonymous> (/home/enzo/MC-Hacks/bot/afk.js:16:24)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by rom1504** [comment]
Use version 1.15.2

**Comment by S0LDR** [comment]
What do you mean @rom1504, node version or mc version?

**Comment by S0LDR** [comment]
@MikeMottonix try installing mineflayer 2.15.0
npm i mineflayer@2.15.0
it worked for me

**Comment by rom1504** [comment]
now fixed, please use mineflayer 2.17.0
