### ISSUE TITLE
Bot freezes on LAN Multiplayer via /publish

### ISSUE THREAD

**Issue by NJay15** [PrismarineJS/mineflayer#1039]
I tried to test my bot (the example echo bot) on my LAN world. When I opened the world using "Open to LAN", everything worked as expected. But when I used /publish to open the world to LAN (which is quite handy as you can set the port manually), the bot joined the world and didn't respond to its environment i.e. didn't take damage or knockback when hit, didn't fall etc. Only when the event it listened to fired (the chat event), it handled the event and immediately left. I tried different ports but all tests yielded the same results. Again, when using the menu button "Open to LAN" everything worked just normal, but a random port was chosen.

**Comment by wvffle** [comment]
What errors do you get?

**Comment by NJay15** [comment]
Error: write ECONNABORTED
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Cipheriv.ondata (_stream_readable.js:717:22)
    at Cipheriv.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Cipheriv.Readable.push (_stream_readable.js:212:10)
    at Cipheriv.Transform.push (_stream_transform.js:152:32)
    at Cipheriv._transform (internal/crypto/cipher.js:135:8)
    at Cipheriv.Transform._read (_stream_transform.js:191:10)
    at Cipheriv.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Cipheriv.Writable.write (_stream_writable.js:318:11)
    at Framer.ondata (node_modules\readable-stream\lib\_stream_readable.js:681:20)
    at Framer.emit (events.js:315:20)
    at addChunk (node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at Framer.Readable.push (node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at Framer.Transform.push (node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at Framer._transform (node_modules\minecraft-protocol\src\transforms\framing.js:20:10)
    at Framer.Transform._read (node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at Framer.Transform._write (node_modules\readable-stream\lib\_stream_transform.js:164:83)
    at doWrite (node_modules\readable-stream\lib\_stream_writable.js:409:139)
    at writeOrBuffer (node_modules\readable-stream\lib\_stream_writable.js:398:5)
    at Framer.Writable.write (node_modules\readable-stream\lib\_stream_writable.js:307:11)
    at Compressor.ondata (node_modules\readable-stream\lib\_stream_readable.js:681:20)
    at Compressor.emit (events.js:315:20)
    at addChunk (node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at Compressor.Readable.push (node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at Compressor.Transform.push (node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at Compressor._transform (node_modules\minecraft-protocol\src\transforms\compression.js:35:12)
    at Compressor.Transform._read (node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at Compressor.Transform._write (node_modules\readable-stream\lib\_stream_transform.js:164:83)
    at doWrite (node_modules\readable-stream\lib\_stream_writable.js:409:139)
    at writeOrBuffer (node_modules\readable-stream\lib\_stream_writable.js:398:5)
    at Compressor.Writable.write (node_modules\readable-stream\lib\_stream_writable.js:307:11)
    at Serializer.ondata (node_modules\readable-stream\lib\_stream_readable.js:681:20)
    at Serializer.emit (events.js:315:20)
    at addChunk (node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at Serializer.Readable.push (node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at Serializer.Transform.push (node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at Serializer._transform (node_modules\protodef\src\serializer.js:22:10)
    at Serializer.Transform._read (node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at Serializer.Transform._write (node_modules\readable-stream\lib\_stream_transform.js:164:83)
    at doWrite (node_modules\readable-stream\lib\_stream_writable.js:409:139)
    at writeOrBuffer (node_modules\readable-stream\lib\_stream_writable.js:398:5)
    at Serializer.Writable.write (node_modules\readable-stream\lib\_stream_writable.js:307:11)
    at Client.write (node_modules\minecraft-protocol\src\client.js:213:21)
    at sendPacketPositionAndLook (node_modules\mineflayer\lib\plugins\physics.js:104:17)
    at updatePosition (node_modules\mineflayer\lib\plugins\physics.js:131:7)
    at Timeout.doPhysics [as _onTimeout] (node_modules\mineflayer\lib\plugins\physics.js:64:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  errno: 'ECONNABORTED',
  code: 'ECONNABORTED',
  syscall: 'write'
}

**Comment by rom1504** [comment]
that means you were kicked
