### ISSUE TITLE
 bot.addchatpattern is not a function

### ISSUE THREAD

**Issue by beartravels** [PrismarineJS/mineflayer#1057]
## Versions
 - mineflayer: 2.19.2
 - server: paper 1.15.2 
 - node: 12.18.0

Bot.chataddpattern not a function

##  bot.addchatpattern is not a function
From terminal:
/home/bear/Jerry/index.js:25
  if (bot.addchatpattern ('^hi','^Hi','^helo','^hello','^Hello','^whats up'))
          ^

TypeError: bot.addchatpattern is not a function
    at Bot.<anonymous> (/home/bear/Jerry/index.js:25:11)
    at Bot.emit (events.js:315:20)
    at checkForChatPatterns (/home/bear/Jerry/node_modules/mineflayer/lib/plugins/chat.js:54:60)
    at Client.<anonymous> (/home/bear/Jerry/node_modules/mineflayer/lib/plugins/chat.js:70:5)
    at Client.emit (events.js:315:20)
    at FullPacketParser.<anonymous> (/home/bear/Jerry/node_modules/minecraft-protocol/src/client.js:87:12)
    at FullPacketParser.emit (events.js:315:20)
    at addChunk (/home/bear/Jerry/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/bear/Jerry/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (/home/bear/Jerry/node_modules/readable-stream/lib/_stream_readable.js:241:10)

from index.js
//When someone talks do stuff
bot.on('chat', function(username, message){		//On Chat event, get username and message contents
  const msg = message;

  if (username === bot.username) return;		//If person talking is bot then do nothing

  if (bot.addchatpattern ('^hi','^Hi','^helo','^hello','^Hello','^whats up'))
{
dosomething(bot.chat("Hello"));							//Then reply with Hello
}

  //bot.chat(message);							//DISABLED    say back what the person said in chat (Echo)
});

**Comment by rom1504** [comment]
I'm thinking we should remove add chat pattern completely, it just confuses
people.

Just use regex yourself

**Comment by beartravels** [comment]
that is regex

i thouhgt'
