### ISSUE TITLE
parsing error for minecraft data for entity metadata of firework rocket

### ISSUE THREAD

**Issue by MrZillaGold** [PrismarineJS/mineflayer#1065]
## Versions
 - mineflayer: 2.19.2
 - server: ![image](https://user-images.githubusercontent.com/42776347/84776566-cee9e380-b023-11ea-973c-bedf33822ee7.png)
 - node: 14.4.0

## Detailed description of a problem
 When reading bot.entities, an error occurs if there is a firework entity near the player.

Video: https://youtu.be/Ozsyil-6mMw

Error: 
```js
TypeError: Deserialization error for play.toClient : Read error for undefined : Cannot destructure property 'value' of 'ctx.entityMetadataItem(...)' as it is und
efined.
    at eval (eval at compile (C:\Users\Пронин Егор\Desktop\AlexBot\node_modules\protodef\src\compiler.js:243:12), <anonymous>:198:24)
    at Object.entityMetadata (eval at compile (C:\Users\Пронин Егор\Desktop\AlexBot\node_modules\protodef\src\compiler.js:243:12), <anonymous>:200:9)
    at Object.packet_entity_metadata (eval at compile (C:\Users\Пронин Егор\Desktop\AlexBot\node_modules\protodef\src\compiler.js:243:12), <anonymous>:1377:75)
    at eval (eval at compile (C:\Users\Пронин Егор\Desktop\AlexBot\node_modules\protodef\src\compiler.js:243:12), <anonymous>:1913:70)
    at packet (eval at compile (C:\Users\Пронин Егор\Desktop\AlexBot\node_modules\protodef\src\compiler.js:243:12), <anonymous>:1940:9)
    at CompiledProtodef.read (C:\Users\Пронин Егор\Desktop\AlexBot\node_modules\protodef\src\compiler.js:64:12)
    at e.message (C:\Users\Пронин Егор\Desktop\AlexBot\node_modules\protodef\src\compiler.js:99:49)
    at tryCatch (C:\Users\Пронин Егор\Desktop\AlexBot\node_modules\protodef\src\utils.js:50:16)
    at CompiledProtodef.parsePacketBuffer (C:\Users\Пронин Егор\Desktop\AlexBot\node_modules\protodef\src\compiler.js:99:29)
    at FullPacketParser.parsePacketBuffer (C:\Users\Пронин Егор\Desktop\AlexBot\node_modules\protodef\src\serializer.js:67:23) {
  field: 'play.toClient'
}
```

## Current code
```js
bot.on("login", () => {
  setInterval(() => {
            console.log(bot.entities)
        }, 1000)
})
```

**Comment by rom1504** [comment]
confirmed

**Comment by rom1504** [comment]
this seems to be an issue with protodef compiler, if I disable it (by putting compiler = false there https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/src/transforms/serializer.js#L15), not getting errors

this is what should be parsed :

```
read packet play.entity_metadata +3ms
  minecraft-protocol {
  minecraft-protocol   "entityId": 268,
  minecraft-protocol   "metadata": [
  minecraft-protocol     {
  minecraft-protocol       "key": 0,
  minecraft-protocol       "type": 0,
  minecraft-protocol       "value": 0
  minecraft-protocol     },
  minecraft-protocol     {
  minecraft-protocol       "key": 1,
  minecraft-protocol       "type": 1,
  minecraft-protocol       "value": 300
  minecraft-protocol     },
  minecraft-protocol     {
  minecraft-protocol       "key": 2,
  minecraft-protocol       "type": 5
  minecraft-protocol     },
  minecraft-protocol     {
  minecraft-protocol       "key": 3,
  minecraft-protocol       "type": 7,
  minecraft-protocol       "value": false
  minecraft-protocol     },
  minecraft-protocol     {
  minecraft-protocol       "key": 4,
  minecraft-protocol       "type": 7,
  minecraft-protocol       "value": false
  minecraft-protocol     },
  minecraft-protocol     {
  minecraft-protocol       "key": 5,
  minecraft-protocol       "type": 7,
  minecraft-protocol       "value": false
  minecraft-protocol     },
  minecraft-protocol     {
  minecraft-protocol       "key": 6,
  minecraft-protocol       "type": 18,
  minecraft-protocol       "value": 0
  minecraft-protocol     },
  minecraft-protocol     {
  minecraft-protocol       "key": 7,
  minecraft-protocol       "type": 6,
  minecraft-protocol       "value": {
  minecraft-protocol         "present": false
  minecraft-protocol       }
  minecraft-protocol     },
  minecraft-protocol     {
  minecraft-protocol       "key": 8,
  minecraft-protocol       "type": 17,
  minecraft-protocol       "value": 0
  minecraft-protocol     },
  minecraft-protocol     {
  minecraft-protocol       "key": 9,
  minecraft-protocol       "type": 7,
  minecraft-protocol       "value": false
  minecraft-protocol     }
  minecraft-protocol   ]
  minecraft-protocol } +0ms
```

**Comment by rom1504** [comment]
I believe that doing https://github.com/PrismarineJS/node-minecraft-protocol/issues/718 is the best way to improve our tests to catch this kind of issue (and fix). I'll give it a try

**Comment by rom1504** [comment]
```
There's a Firework Rocket at (637.15, 65.78683412075043, 780.4339747428894)
TypeError: Deserialization error for play.toClient : Read error for undefined : Cannot destructure property `value` of 'undefined' or 'null'.
    at eval (eval at compile (mineflayer/node_modules/protodef/src/compiler.js:243:12), <anonymous>:199:15)
    at Object.entityMetadata (eval at compile (mineflayer/node_modules/protodef/src/compiler.js:243:12), <anonymous>:201:9)
    at Object.packet_entity_metadata (eval at compile (mineflayer/node_modules/protodef/src/compiler.js:243:12), <anonymous>:1392:75)
    at eval (eval at compile (mineflayer/node_modules/protodef/src/compiler.js:243:12), <anonymous>:1947:70)
    at packet (eval at compile (mineflayer/node_modules/protodef/src/compiler.js:243:12), <anonymous>:1974:9)
    at CompiledProtodef.read (mineflayer/node_modules/protodef/src/compiler.js:64:12)
    at e.message (mineflayer/node_modules/protodef/src/compiler.js:99:49)
    at tryCatch (mineflayer/node_modules/protodef/src/utils.js:50:16)
    at CompiledProtodef.parsePacketBuffer (mineflayer/node_modules/protodef/src/compiler.js:99:29)
    at FullPacketParser.parsePacketBuffer (mineflayer/node_modules/protodef/src/serializer.js:68:23) {
  field: 'play.toClient'
}
```
i confirm this still happens

better fix it...

**Comment by Karang** [comment]
I found the issue: https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.15.2/protocol.json#L4 which gets compiled to:
```
optvarint: (buffer, offset) => {
    ctx.varint
}
```
Which of course gives undefined. I made a PR https://github.com/ProtoDef-io/node-protodef/pull/109 that solves it

**Comment by rom1504** [comment]
now fixed, just run `npm update --depth 9999`
