### ISSUE TITLE
minecraft-protocol mistake

### ISSUE THREAD

**Issue by xASTRONOWx** [PrismarineJS/mineflayer#1075]
I tried to create a bot for mc 1.15.2 on macbook, macos Catalina. In console a got this problem:
```
ivansiskin@MacBook-Pro-Ivan ~ % cd /Users/ivansiskin/Desktop/bot
ivansiskin@MacBook-Pro-Ivan bot % node index 
Chunk size is 255 but only 1 was read ; partial packet : {}; buffer :1bfc017b227472616e736c617465223a22646973636f6e6e6563742e67656e65726963526561736f6e222c2277697468223a5b22496e7465726e616c20457863657074696f6e3a20696f2e6e657474792e68616e646c65722e636f6465632e4465636f646572457863657074696f6e3a206a6176612e6c616e672e496e6465784f75744f66426f756e6473457863657074696f6e3a20726561646572496e646578283129202b206c656e677468283129206578636565647320777269746572496e6465782831293a20506f6f6c6564556e736166654469726563744279746542756628726964783a20312c20776964783a20312c206361703a203129225d7d
/Users/ivansiskin/Desktop/bot/node_modules/minecraft-protocol/src/transforms/framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read property 'length' of undefined
    at FullPacketParser.<anonymous> (/Users/ivansiskin/Desktop/bot/node_modules/minecraft-protocol/src/client.js:85:15)
    at FullPacketParser.emit (events.js:315:20)
    at addChunk (/Users/ivansiskin/Desktop/bot/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/Users/ivansiskin/Desktop/bot/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (/Users/ivansiskin/Desktop/bot/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (/Users/ivansiskin/Desktop/bot/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at FullPacketParser._transform (/Users/ivansiskin/Desktop/bot/node_modules/protodef/src/serializer.js:81:10)
    at FullPacketParser.Transform._read (/Users/ivansiskin/Desktop/bot/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at FullPacketParser.Transform._write (/Users/ivansiskin/Desktop/bot/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/Users/ivansiskin/Desktop/bot/node_modules/readable-stream/lib/_stream_writable.js:409:139)
ivansiskin@MacBook-Pro-Ivan bot % 

```

**Comment by rom1504** [comment]
Can you fill up the context as specified by the template please

**Comment by xASTRONOWx** [comment]
I did
