### ISSUE TITLE
Deserialization error on use of a Firework.

### ISSUE THREAD

**Issue by MrKinauJr** [PrismarineJS/mineflayer#1093]
[X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.22.0
 - server: vanilla/spigot/paper 1.15.2 spigot
 - node: v14.3.0

## Detailed description of a problem
If i use a firework (basic without any stars) i get a Deserialization error. 

## Error Message (No Code)
```
TypeError: Deserialization error for play.toClient : Read error for undefined : Cannot destructure property 'value' of 'ctx.entityMetadataItem(...)' as it is undefined.
    at eval (eval at compile (C:\NodeJSPrograms\MCBot\node_modules\protodef\src\compiler.js:243:12), <anonymous>:198:24)
    at Object.entityMetadata (eval at compile (C:\NodeJSPrograms\MCBot\node_modules\protodef\src\compiler.js:243:12), <anonymous>:200:9)
    at Object.packet_entity_metadata (eval at compile (C:\NodeJSPrograms\MCBot\node_modules\protodef\src\compiler.js:243:12), <anonymous>:1377:75)
    at eval (eval at compile (C:\NodeJSPrograms\MCBot\node_modules\protodef\src\compiler.js:243:12), <anonymous>:1913:70)
    at packet (eval at compile (C:\NodeJSPrograms\MCBot\node_modules\protodef\src\compiler.js:243:12), <anonymous>:1940:9)
    at CompiledProtodef.read (C:\NodeJSPrograms\MCBot\node_modules\protodef\src\compiler.js:64:12)
    at e.message (C:\NodeJSPrograms\MCBot\node_modules\protodef\src\compiler.js:99:49)
    at tryCatch (C:\NodeJSPrograms\MCBot\node_modules\protodef\src\utils.js:50:16)
    at CompiledProtodef.parsePacketBuffer (C:\NodeJSPrograms\MCBot\node_modules\protodef\src\compiler.js:99:29)
    at FullPacketParser.parsePacketBuffer (C:\NodeJSPrograms\MCBot\node_modules\protodef\src\serializer.js:68:23) {
  field: 'play.toClient'
}
```

## Expected behavior
No error.

**Comment by Leftier** [comment]
Duplicate of #1065

**Comment by MrKinauJr** [comment]
then nvm. should have searched first.
