### ISSUE TITLE
bot.clickWindow error catch

### ISSUE THREAD

**Issue by TheDeaX-Lab** [PrismarineJS/mineflayer#1109]
[ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.22.0
 - server: paper
 - node: 14.4.0

## Detailed description of a problem
```
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -32768 and <= 32767. Received 32768
    at checkInt (internal/buffer.js:63:11)
    at writeU_Int16BE (internal/buffer.js:823:3)
    at Buffer.writeInt16BE (internal/buffer.js:885:10)
    at Object.writer [as i16] (/home/deax/NodeProjects/bots/node_modules/protodef/src/datatypes/numeric.js:69:25)
    at Object.packet_window_click (eval at compile (/home/deax/NodeProjects/bots/node_modules/protodef/src/compiler.js:243:12), <anonymous>:254:25)
    at eval (eval at compile (/home/deax/NodeProjects/bots/node_modules/protodef/src/compiler.js:243:12), <anonymous>:525:64)
    at packet (eval at compile (/home/deax/NodeProjects/bots/node_modules/protodef/src/compiler.js:243:12), <anonymous>:552:9)
    at CompiledProtodef.write (/home/deax/NodeProjects/bots/node_modules/protodef/src/compiler.js:70:12)
    at e.message (/home/deax/NodeProjects/bots/node_modules/protodef/src/compiler.js:90:25)
    at tryCatch (/home/deax/NodeProjects/bots/node_modules/protodef/src/utils.js:50:16) {
  code: 'ERR_OUT_OF_RANGE',
  field: 'play.toServer'
}
```

## Current code
```js
bot.clickWindowPromise = (slot, button, mode) => {
            return new Promise((resolve, reject) => {
                bot.clickWindow(slot, button, mode, err => {
                    if (err) {
                        reject(err)
                    } else {
                        resolve()
                    }
                })
            })
        }

async function clearChestSellMelonsPutChest(chestBlockClear, chestBlockPut) {
            chest_selling = true
            let chestClear
            let chestPut
            let free_slots
            let window

            while (chest_selling) {
                free_slots = bot.inventory.slots.filter((r, i) => r === null && 9 <= i && i < 45).length
                chestClear = await bot.openChestPromise(chestBlockClear);
                await chestClear.withdrawPromise(103, null, free_slots * 64)
                await chestClear.closePromise()

                window = await bot.waitWindowPromise((window) => {
                    if (window.title.indexOf("Магазин обменник") > -1) {
                        return true
                    } else {
                        return false
                    }
                }, () => bot.chat("/shop exchanger2"))

                await bot.clickWindowPromise(15, 2, 3)
                await bot.closeWindowPromise(window)

                chestPut = await bot.openChestPromise(chestBlockPut);
                await chestPut.depositPromise(388, null, 36 * 64)
                await chestPut.closePromise()
                await sleepPromise(1000)
            }
        }
```

**Comment by rom1504** [comment]
not clear what's the problem
