### ISSUE TITLE
Bumping into 1.16.1 walls

### ISSUE THREAD

**Issue by Frettarix** [PrismarineJS/mineflayer#1172]
[ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest
 - server: 1.16.1

##Describe the issue
I was fighting with my bot and hit him back into a wall (1.16.1)
![image](https://user-images.githubusercontent.com/47563851/88105091-aa91a180-cba3-11ea-978e-dd8a44b31832.png)
This resulted in the following:
```
...node_modules\prismarine-physics\index.js:73
            for (const shape of block.shapes) {
                                      ^

TypeError: block.shapes is not iterable
    at getSurroundingBBs (...node_modules\prismarine-physics\index.js:73:39)
    at moveEntity (...node_modules\prismarine-physics\index.js:117:28)
    at moveEntityWithHeading (...node_modules\prismarine-physics\index.js:291:7)
    at Object.Physics.physics.simulatePlayer (...node_modules\prismarine-physics\index.js:450:5)
    at Timeout.doPhysics [as _onTimeout] (...node_modules\mineflayer\lib\plugins\physics.js:61:17)
```

## Expected behavior
Bot just collides with the wall like a normal object.

## Additional context
Since 1.16.0 walls have changed and now update differently when placed on top of each other or next to each other (for instance when connecting with glass panels)

**Comment by rom1504** [comment]
can you run `npm update --depth 999` and try again?

**Comment by Frettarix** [comment]
Updated, the bot crashed as soon as it collided with a wall 2x2:
![image](https://user-images.githubusercontent.com/47563851/88106210-67383280-cba5-11ea-896b-c1930ea207fa.png)

**Comment by Karang** [comment]
1.16 shapes in mc-data were copied from 1.15 and the chain bounding box was updated manually. We don't have a good procedure to extract block shapes. 1.15 was done manually with a custom mod. If wall shapes changed from 1.15 to 1.16, then they have not been updated. I suggest opening the issue in mc-data.

**Comment by sefirosweb** [comment]
I have same issue with "lantern", I see they no have a shappes and throw an error,

On 1.14/blockCollisionShapes.json I don't see that items, for that I understood the issues comes from here, and i need to add shapes, 

But i'm trying to understand https://github.com/PrismarineJS/minecraft-data/blob/ab0eb327664a04107d1ac6663bf5f826fc80bc3b/doc/blockCollisionShapes.md but is a bit complex @_@

How you can calculate the shapes? (try and error?)

**Comment by nevercast** [comment]
This will affect doors also. Ideally Mineflayer's pathfinding would know when a block is not a full block and account for the spare room in that block to determine the position to occupy. To save computation during pathfinding time this could be computed when block shapes are generated as block.freeSpace or something.
