### ISSUE TITLE
Error: schema is invalid: data.definitions['childrenValues'] should be object,boolean

### ISSUE THREAD

**Issue by gauthier-th** [PrismarineJS/mineflayer#1177]
## Versions
 - mineflayer: 2.24.0
 - node: 12.9.0

## Problem
When I require mineflayer, I got an unexpected error.
This error only occurs on a single project. I managed to reproduce it by reinstalling my project with the same code. Mineflayer is only a very small part of my project, so I don't know what code to send. This error does not occur on other projects with a similar mineflayer/nodejs configuration, and I have no idea of what could I made wrong.

## Code
```js
const mineflayer = require('mineflayer');
```

## Error :
```
$ref: keywords ignored in schema at path "#/properties/maxLength"
$ref: keywords ignored in schema at path "#/properties/minLength"
$ref: keywords ignored in schema at path "#/allOf/0"
$ref: keywords ignored in schema at path "#/properties/additionalItems"
$ref: keywords ignored in schema at path "#/properties/items/anyOf/0"
$ref: keywords ignored in schema at path "#/properties/items/anyOf/1"
$ref: keywords ignored in schema at path "#/items"
$ref: keywords ignored in schema at path "#/properties/maxItems"
$ref: keywords ignored in schema at path "#/properties/minItems"
$ref: keywords ignored in schema at path "#/properties/contains"
$ref: keywords ignored in schema at path "#/properties/maxProperties"
$ref: keywords ignored in schema at path "#/properties/minProperties"
$ref: keywords ignored in schema at path "#/properties/required"
$ref: keywords ignored in schema at path "#/properties/additionalProperties"
$ref: keywords ignored in schema at path "#/properties/definitions/additionalProperties"
$ref: keywords ignored in schema at path "#/properties/properties/additionalProperties"
$ref: keywords ignored in schema at path "#/properties/patternProperties/additionalProperties"
$ref: keywords ignored in schema at path "#/properties/dependencies/additionalProperties/anyOf/0"
$ref: keywords ignored in schema at path "#/properties/dependencies/additionalProperties/anyOf/1"
$ref: keywords ignored in schema at path "#/properties/propertyNames"
$ref: keywords ignored in schema at path "#/properties/type/anyOf/0"
$ref: keywords ignored in schema at path "#/properties/type/anyOf/1/items"
$ref: keywords ignored in schema at path "#/properties/if"
$ref: keywords ignored in schema at path "#/properties/then"
$ref: keywords ignored in schema at path "#/properties/else"
$ref: keywords ignored in schema at path "#/properties/allOf"
$ref: keywords ignored in schema at path "#/properties/anyOf"
$ref: keywords ignored in schema at path "#/properties/oneOf"
$ref: keywords ignored in schema at path "#/properties/not"
C:\myprojet\\node_modules\ajv\lib\ajv.js:178
    else throw new Error(message);
         ^

Error: schema is invalid: data.definitions['childrenValues'] should be object,boolean
    at Ajv.validateSchema (C:\myprojet\\node_modules\ajv\lib\ajv.js:178:16)
    at Ajv._addSchema (C:\myprojet\\node_modules\ajv\lib\ajv.js:307:10)
    at Ajv.addSchema (C:\myprojet\\node_modules\ajv\lib\ajv.js:137:29)
    at Validator.createAjvInstance (C:\myprojet\\node_modules\protodef-validator\index.js:14:14)
    at new Validator (C:\myprojet\\node_modules\protodef-validator\index.js:6:10)
    at new ProtoDef (C:\myprojet\\node_modules\protodef\src\protodef.js:47:35)
    at Object.<anonymous> (C:\myprojet\\node_modules\protodef\src\index.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
```

**Comment by gauthier-th** [comment]
Fixed: The error was caused by extending native objects (Array and Object).
