### ISSUE TITLE
how i can see chat clickevent

### ISSUE THREAD

**Issue by fhjkregjlkhgjhre** [PrismarineJS/mineflayer#1227]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: lastest
 - server: vanilla
 - node: lastest

## Detailed description of a question
How i can see what is on the clickevent (like commands and urls)

**Comment by IdanHo** [comment]
```js
msg.clickEvent.action
```

**Comment by fhjkregjlkhgjhre** [comment]
> 
> 
> ```js
> msg.clickEvent.action
> ```

ty

**Comment by wvffle** [comment]
Is there a reason you've just reopened the issue?

**Comment by fhjkregjlkhgjhre** [comment]
> 
> 
> Is there a reason you've just reopened the issue?

im testing and i hit the wrong button :/

**Comment by fhjkregjlkhgjhre** [comment]
> 
> 
> ```js
> msg.clickEvent.action
> ```

and this didnt work gives me this error
```js
ERRO ->  TypeError: Cannot read property 'action' of undefined

2020-08-09T20:06:38.469172+00:00 app[worker.1]:     at Bot.<anonymous> (/app/main.js:49:33)

2020-08-09T20:06:38.469172+00:00 app[worker.1]:     at Bot.emit (events.js:315:20)

2020-08-09T20:06:38.469174+00:00 app[worker.1]:     at Client.<anonymous> (/app/node_modules/mineflayer/lib/plugins/chat.js:69:9)

2020-08-09T20:06:38.469174+00:00 app[worker.1]:     at Client.emit (events.js:315:20)

2020-08-09T20:06:38.469174+00:00 app[worker.1]:     at FullPacketParser.<anonymous> (/app/node_modules/minecraft-protocol/src/client.js:89:12)

2020-08-09T20:06:38.469175+00:00 app[worker.1]:     at FullPacketParser.emit (events.js:315:20)

2020-08-09T20:06:38.469175+00:00 app[worker.1]:     at addChunk (/app/node_modules/readable-stream/lib/_stream_readable.js:298:12)

2020-08-09T20:06:38.469175+00:00 app[worker.1]:     at readableAddChunk (/app/node_modules/readable-stream/lib/_stream_readable.js:280:11)

2020-08-09T20:06:38.469176+00:00 app[worker.1]:     at FullPacketParser.Readable.push (/app/node_modules/readable-stream/lib/_stream_readable.js:241:10)
```

**Comment by fhjkregjlkhgjhre** [comment]
i guess i need to do this `msg.json.clickevent.action`?

**Comment by IdanHo** [comment]
that means that message doesnt have a clickEvent, you have to check first if it does via 
```js
if (msg.clickEvent) { }
```
prismarine-chat parses the json itself, you dont have to access it directly.

**Comment by fhjkregjlkhgjhre** [comment]
> 
> 
> that means that message doesnt have a clickEvent, you have to check first if it does via
> 
> ```js
> if (msg.clickEvent) { }
> ```
> 
> prismarine-chat parses the json itself, you dont have to access it directly.

ok

**Comment by wvffle** [comment]
If you want to access raw messages then you can use some low level stuff:

```js
bot._client.on('chat', (packet) => {
  const msg = JSON.parse(packet.message)
  // msg is now a raw json message
})
```

**Comment by fhjkregjlkhgjhre** [comment]
> 
> 
> If you want to access raw messages then you can use some low level stuff:
> 
> ```js
> bot._client.on('chat', (packet) => {
>   const msg = JSON.parse(packet.message)
>   // msg is now a raw json message
> })
> ```
> 
> **Edit:** Also, if you have a parsed `ChatMessage` instance (from `message` or `chat` events), you can use `msg.json` to access the raw json message

ok

**Comment by fhjkregjlkhgjhre** [comment]
i guess thats all ty for the help
