### ISSUE TITLE
PartialReadError: Deserialization error for play.toClient ERROR

### ISSUE THREAD

**Issue by Ownslo** [PrismarineJS/mineflayer#1277]
Hello I'm simply trying to create a simple bot that selects a lobby, or a game skyblock from a window.

It works fine logging the data, but when I try to bot.clickWindow I get a error. 
Here is the error:

```
PartialReadError: Deserialization error for play.toClient : Read error for undefined : Missing characters in string, found size is 40799 expected size was 420740033
    at new ExtendableError (C:\Users\Nikki\Desktop\npm\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (C:\Users\Nikki\Desktop\npm\node_modules\protodef\src\utils.js:70:5)
    at Object.string (eval at compile (C:\Users\Nikki\Desktop\npm\node_modules\protodef\src\compiler.js:245:12), <anonymous>:47:15)
    at eval (eval at compile (C:\Users\Nikki\Desktop\npm\node_modules\protodef\src\compiler.js:245:12), <anonymous>:1733:71)
    at eval (eval at compile (C:\Users\Nikki\Desktop\npm\node_modules\protodef\src\compiler.js:245:12), <anonymous>:1816:11)
    at Object.packet_declare_recipes (eval at compile (C:\Users\Nikki\Desktop\npm\node_modules\protodef\src\compiler.js:245:12), <anonymous>:1821:9)
    at eval (eval at compile (C:\Users\Nikki\Desktop\npm\node_modules\protodef\src\compiler.js:245:12), <anonymous>:1967:70)
    at packet (eval at compile (C:\Users\Nikki\Desktop\npm\node_modules\protodef\src\compiler.js:245:12), <anonymous>:1972:9)
    at CompiledProtodef.read (C:\Users\Nikki\Desktop\npm\node_modules\protodef\src\compiler.js:64:12)
    at e.message (C:\Users\Nikki\Desktop\npm\node_modules\protodef\src\compiler.js:99:49) {
  name: 'PartialReadError',
  partialReadError: true,
  field: 'play.toClient'
}
```

Here is my script: 

```
const Item = require("prismarine-item")("1.8");
const delay = require('delay')
const mineflayer = require('mineflayer')
const mcData = require("minecraft-data")("1.8.8")


var bot = mineflayer.createBot({
    host: 'bedwars.games',
    port: 25565, // optional
    username: 'MYUSERNAME',
    version: '1.16.1'
})


bot.once('login', () => {
    console.log('Spawned.')
    bot.chat('/login PASSWORD')

    console.log('Logged in')
    //bot.setControlState('jump', true)

    setTimeout(function() {
        bot.setQuickBarSlot(4)
        console.log('Activating Compass.')
        bot.activateItem()

    }, 3000);

})

bot.on('windowOpen', (window) => {
    console.log('Activated Compass')
    bot.clickWindow(13, 1, 0, (err) => {
        console.log(err);
    });
    //console.log(window.selectedItem);
    console.log(window.slots[13]);
    //bot.equip(window.selectedItem,"hand");
})

bot.on('windowClose', (window) => {
    console.log('Window Closed')
})
```

Can someone help me understand and fix this error? Thank you.

**Comment by rom1504** [comment]
Can you please say what is special about this server ? (spigot, plugins, ...)

**Comment by JavaMan7** [comment]
if this is hypixel then they run a costume server . there recommended version to use is 1.8. they do this because  of the combat update in 1.9.

**Comment by ng1905** [comment]
@rom1504 happen to see this exact same issue on another server: Spigot 1.16.1 running ViaVersion (https://www.spigotmc.org/resources/viaversion.19254/) and their "plugins" ViaBackwards and ViaRewind. Forcing version 1.8 solved the issue for me, maybe it'll help
