### ISSUE TITLE
Need help with my code

### ISSUE THREAD

**Issue by Tragafantas** [PrismarineJS/mineflayer#1294]
- [x] I have carefully read the [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) and it does not contain an answer to my question.
- [x] I have carefully read the [API documentation](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md) and it does not contain an answer to my question.
- [x] I have carefully read the [examples](https://github.com/PrismarineJS/mineflayer/tree/master/examples) and they do not contain an answer to my question.

## Versions
 - mineflayer: 2.28.1
 - server: tested in vanilla and paper 
 - node: 12.18.3

## Clear question
I was making a code for and AFK Bot and ran into a problem, the bot had some code from reconnect.js, and it conflicts with bot.nearestEntity. When I kick the bot, bot.nearestEntity keeps running and it crashes the bot. Sorry if the code's a little messy, it's my first one.

## What did you try yet?

When to the API to look at bot.nearestEntity but I didn't quite understand it.

## Your current code

```js

const mineflayer = require('mineflayer')
const mineflayerViewer = require('prismarine-viewer').mineflayer
const { spawn } = require('child_process')
const { stringify } = require('querystring')
var bot

if (process.argv.length < 4 || process.argv.length > 6) {
  console.log('Usage : node reconnector.js <host> <port> [<name>] [<password>]')
  process.exit(1)
}

function createBot () {
  bot = mineflayer.createBot({
    host: process.argv[2],
    port: parseInt(process.argv[3]),
    username: process.argv[4] ? process.argv[4] : 'reconnector',
    password: process.argv[5]
  })

  bot.on('error', (err) => console.log(err))
  bot.on('end', createBot)
}

createBot()

//WEB VIEWER
bot.once('spawn', () => {
  mineflayerViewer(bot, { port: 3000 })

  const path = [bot.entity.position.clone()]
  bot.on('move', () => {
    if (path[path.length - 1].distanceTo(bot.entity.position) > 1) {
      path.push(bot.entity.position.clone())
      bot.viewer.drawLine('path', path)
    }
  })
})



//CHAT
bot.once('chat', function (username, message) {
  if (username === bot.username) return
  setTimeout(function() {
  bot.chat('Sono un Bot per stare AFK')
}, 1000)})

bot.on('chat', function (username, message) {
  if (username === bot.username) return
    console.log('\x1b[37m','<CHAT>',username,':',message,'\x1b[0m')
})

bot.on('chat', function (username, message) {
  if (username !== bot.username) return
    console.log('\x1b[37m','<CHAT>','AFKBOT',':',message,'\x1b[0m')
})



//KICK & ERRORS
bot.on('kicked', (reason, loggedIn) => console.log('\x1b[32m','<STATUS>\x1b[0m','\x1b[31mI got kicked for','\x1b[0m',reason, loggedIn))
bot.on('error', err => console.log('\x1b[32m','<STATUS>','\x1b[0m',err))



//LOOKING
bot.once('spawn', function () {
  setInterval(() => {
      const entity = bot.nearestEntity()
      if (entity !== null) {
        if (entity.type === 'player') {
        bot.lookAt(entity.position.offset(0, 1.6, 0))
        } else if (entity.type === 'mob') {
          bot.lookAt(entity.position)
        }
      }
  }, 50)
})



//EVENTS
bot.on('death', () => {
  console.log('\x1b[32m','<STATUS>\x1b[0m','\x1b[31mI died','\x1b[0m')
})

bot.once('spawn', () => {
  console.log('\x1b[32m','<STATUS>','Correctly spawned','\x1b[0m')
})

bot.on('respawn', () => {
  console.log('\x1b[32m','<STATUS>','Correctly respawned','\x1b[0m')
})

bot.on('login', () => {
  console.log('\x1b[32m','<STATUS>','Correctly logged in','\x1b[0m')
})

bot.once('health', () => {
  console.log('\x1b[32m','<STATUS>',`I have ${bot.health} health.`,'\x1b[0m')
})

bot.on('health', () => {
  if (bot.health <= 5)
    console.log('\x1b[32m','<STATUS>\x1b[0m',`\x1b[33mMy remaining health is ${bot.health}.`,'\x1b[0m')
})



//WORLD
bot.once('time', () => {
  setTimeout(function() {
  console.log('\x1b[36m','<WORLD>','Current time: ' + bot.time.timeOfDay,'\x1b[0m')
}, 1000)})

bot.on('entityHurt', (entity) => {
  if (entity.type === 'player') {
    if (entity.username !== bot.username) 
      console.log('\x1b[36m','<WORLD>\x1b[0m',`\x1b[33m${entity.username} got hurt, beware`,'\x1b[0m')
    else
      console.log('\x1b[36m','<WORLD>\x1b[0m',`\x1b[33mI've got hurt, beware`,'\x1b[0m')
  }
})

bot.on('playerJoined', (player) => {
  setTimeout(function() {
  if (player.username !== bot.username) {
    console.log('\x1b[36m','<WORLD>\x1b[0m',`\x1b[32m${player.username} joined`,'\x1b[0m')
  }
}, 3000)})

bot.on('playerLeft', (player) => {
  if (player.username === bot.username) return
  console.log('\x1b[36m','<WORLD>\x1b[0m',`\x1b[32m${player.username} left`,'\x1b[0m')
})
```

**Comment by rom1504** [comment]
what is your error

**Comment by Tragafantas** [comment]
Ah yeah sorry

E:\test\Bot\AFK.js:69
      const entity = bot.nearestEntity()
                         ^

TypeError: bot.nearestEntity is not a function
    at Timeout._onTimeout (E:\test\Bot\AFK.js:69:26)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by rom1504** [comment]
Ok the issue is coming from your use of the reconnect function. 
When the bot disconnect you need to disable all your intervals then re enable it and re listen to all your events (just put the whole code inside create Bot)

**Comment by Tragafantas** [comment]
Ok thank you
