### ISSUE TITLE
How to fix this? PartialReadError: Deserialization error for play.toClient : Read error for undefined : Missing characters in string, found size is 40799 expected size was 420740033

### ISSUE THREAD

**Issue by gettyt** [PrismarineJS/mineflayer#1301]
`PartialReadError: Deserialization error for play.toClient : Read error for undefined : Missing characters in string, found size is 40799 expected size was 420740033
    at new ExtendableError (C:\Users\mamas\Documents\MinecraftBots\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (C:\Users\mamas\Documents\MinecraftBots\node_modules\protodef\src\utils.js:70:5)
    at Object.string (eval at compile (C:\Users\mamas\Documents\MinecraftBots\node_modules\protodef\src\compiler.js:245:12), <anonymous>:47:15)
    at eval (eval at compile (C:\Users\mamas\Documents\MinecraftBots\node_modules\protodef\src\compiler.js:245:12), <anonymous>:1733:71)
    at eval (eval at compile (C:\Users\mamas\Documents\MinecraftBots\node_modules\protodef\src\compiler.js:245:12), <anonymous>:1816:11)
    at Object.packet_declare_recipes (eval at compile (C:\Users\mamas\Documents\MinecraftBots\node_modules\protodef\src\compiler.js:245:12), <anonymous>:1821:9)
    at eval (eval at compile (C:\Users\mamas\Documents\MinecraftBots\node_modules\protodef\src\compiler.js:245:12), <anonymous>:1967:70)
    at packet (eval at compile (C:\Users\mamas\Documents\MinecraftBots\node_modules\protodef\src\compiler.js:245:12), <anonymous>:1972:9)
    at CompiledProtodef.read (C:\Users\mamas\Documents\MinecraftBots\node_modules\protodef\src\compiler.js:64:12)
    at e.message (C:\Users\mamas\Documents\MinecraftBots\node_modules\protodef\src\compiler.js:99:49) {
  partialReadError: true,
  field: 'play.toClient'`

**Comment by wvffle** [comment]
Please, stick to the issue template
