### ISSUE TITLE
server packet error?

### ISSUE THREAD

**Issue by qqqZXzz123** [PrismarineJS/mineflayer#1451]
\mineflayer-2.32.0\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at prepareJson (\mineflayer-2.32.0\node_modules\mineflayer\lib\plugins\blocks.js:58:27)
    at addBlockEntity (\mineflayer-2.32.0\node_modules\mineflayer\lib\plugins\blocks.js:68:43)
    at Client.<anonymous> (\mineflayer-2.32.0\node_modules\mineflayer\lib\plugins\blocks.js:446:5)
    at Client.emit (events.js:315:20)
    at FullPacketParser.<anonymous> (\mineflayer-2.32.0\node_modules\minecraft-protocol\src\client.js:89:12)
    at FullPacketParser.emit (events.js:315:20)
    at addChunk (\mineflayer-2.32.0\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (\mineflayer-2.32.0\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (\mineflayer-2.32.0\node_modules\readable-stream\lib\_stream_readable.js:241:10)

**Comment by rom1504** [comment]
Fill up the template
