### ISSUE TITLE
How can i do bot which dig 5 blocks only to up, that  blocks updating do by piston?

### ISSUE THREAD

**Issue by KR1470R** [PrismarineJS/mineflayer#1459]
Hi there!
My goal make bot which dig 5 blocks only to up and new blocks that piston will do in  the same vector.
I tryed do something like this:
```
bot.on("spawn", () => {
    bot.setQuickBarSlot(0)
    bot.look(0, 90)
    if (bot.blockAt(new Vec3(bot.entity.position.x, bot.entity.position.y+2, bot.entity.position.z)).type != 0) {
      console.log("Defined 1 block")
      bot.dig(bot.blockAt(new Vec3(bot.entity.position.x, bot.entity.position.y+2, bot.entity.position.z)), err => { // 1 block diging
        if (err) throw err;
        if (bot.blockAt(new Vec3(bot.entity.position.x, bot.entity.position.y+3, bot.entity.position.z)).type != 0) {
          console.log("Defined 2 block")
          bot.dig(bot.blockAt(new Vec3(bot.entity.position.x, bot.entity.position.y+3, bot.entity.position.z)), err1 => { // 2 block diging
            if (err1) throw err1;
            if (bot.blockAt(new Vec3(bot.entity.position.x, bot.entity.position.y+4, bot.entity.position.z)).type != 0) {
              bot.dig(bot.blockAt(new Vec3(bot.entity.position.x, bot.entity.position.y + 4, bot.entity.position.z)), err2 => { // 3 block diging
                if (err2) throw err2;
                if (bot.blockAt(new Vec3(bot.entity.position.x, bot.entity.position.y+5, bot.entity.position.z)).type != 0) {
                  bot.dig(bot.blockAt(new Vec3(bot.entity.position.x, bot.entity.position.y + 5, bot.entity.position.z)), err3 => { // 4 block diging
                    if (err3) throw err3;
                    if (bot.blockAt(new Vec3(bot.entity.position.x, bot.entity.position.y+6, bot.entity.position.z)).type != 0) {
                      bot.dig(bot.blockAt(new Vec3(bot.entity.position.x, bot.entity.position.y + 6, bot.entity.position.z)), err4 => { // 5 block diging
                        if (err4) throw err4;
                      })
                    }
                  })
                }
              })
            }
          })
        }
      })
    }
})

```

That's kinda of working, but only one time and doesn't what i want, imma tryed do another way but that's not it.
I need that him updates new blocks and dig it.
Please explain me how i can do it?

**Comment by goncharovchik** [comment]
ухади

**Comment by imharvol** [comment]
I imagine it may be for a cobblestone generator, there are blocks being push constantly.

This might work but it doesn't listen for block updates. 
```js

next()

function next() {
  // Determine which block we should mine by checking the 5 blocks right above the bot
  for (let i = 2; i < 5+2; i++) {
    const block = bot.blockAt(bot.entity.position.floored().offset(0, i, 0))
    if (block !== null) { // If it hasn't been mined already
      bot.dig(block, next)
    }
  }
}
```

**Comment by imharvol** [comment]
This should listen also to block updates:

```js
next()

function next(err) {
  if (err) throw err

  bot.on('blockUpdate', blockUpdateHandler)
  
  // Determine which block we should mine by checking the 5 blocks right above the bot
  for (let i = 2; i < 5+2; i++) {
    const block = bot.blockAt(bot.entity.position.floored().offset(0, i, 0))
    if (block !== null) { // If it hasn't been mined already
      bot.dig(block, () => {
        bot.removeListener('blockUpdate', blockUpdateHandler)
      })
    }
  }

  function blockUpdateHandler (oldBlock, newBlock) {
    // If while digging a block appears between the bot and the block that is being mined, we should stop digging that block and call next again so the block that just appeared is the one mined (just as happens when you loop up and hold the mouse click)
    if (newBlock.position.x === bot.targetDigBlock.position.x 
      && newBlock.position.z === bot.targetDigBlock.position.z
      && newBlock.position.y <= bot.targetDigBlock.position.y) {
      bot.stopDigging()
      bot.removeListener('blockUpdate', blockUpdateHandler)
      next()
    }
  }
}
```

**Comment by KR1470R** [comment]
@imharvol Thanks for answering!
But, when bot have started diging i have this error occurupted:
```
/node_modules/minecraft-protocol/src/transforms/framing.js:67
          } else { throw e }
                   ^

Error: Digging aborted
    at Bot.bot.stopDigging (/node_modules/mineflayer/lib/plugins/digging.js:55:12)
    at Bot.blockUpdateHandler (/src/index.js:143:15)
    at Bot.emit (node:events:341:22)
    at emitBlockUpdate (/node_modules/mineflayer/lib/plugins/blocks.js:267:9)
    at updateBlockState (/node_modules/mineflayer/lib/plugins/blocks.js:296:5)
    at Client.<anonymous> (/node_modules/mineflayer/lib/plugins/blocks.js:389:5)
    at Client.emit (node:events:329:20)
    at FullPacketParser.<anonymous> (/node_modules/minecraft-protocol/src/client.js:89:12)
    at FullPacketParser.emit (node:events:329:20)
    at addChunk (/node_modules/readable-stream/lib/_stream_readable.js:298:12)

```
