### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by lubek-dc** [PrismarineJS/mineflayer#1571]
Versions
 - mineflayer: 2.40.1
 - server: spigot 1.16.2
 - node: index.js

Hello im have this error on code
1.
TypeError: Cannot read property 'protocol' of null
    at createProtocol (C:\Users\Borys\Desktop\Minecraft bot\node_modules\minecraft-protocol\src\transforms\serializer.js:23:39)
    at createSerializer (C:\Users\Borys\Desktop\Minecraft bot\node_modules\minecraft-protocol\src\transforms\serializer.js:37:25)
    at Client.setSerializer (C:\Users\Borys\Desktop\Minecraft bot\node_modules\minecraft-protocol\src\client.js:42:23)
    at Client.set state [as state] (C:\Users\Borys\Desktop\Minecraft bot\node_modules\minecraft-protocol\src\client.js:113:10)
    at C:\Users\Borys\Desktop\Minecraft bot\node_modules\minecraft-protocol\src\client\autoVersion.js:43:18
    at Client.<anonymous> (C:\Users\Borys\Desktop\Minecraft bot\node_modules\minecraft-protocol\src\ping.js:39:7)
    at Object.onceWrapper (events.js:422:26)
    at Client.emit (events.js:315:20)
    at FullPacketParser.<anonymous> (C:\Users\Borys\Desktop\Minecraft bot\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (events.js:315:20)
2.
C:\Users\Borys\Desktop\Minecraft bot\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }

code : [link](https://pastebin.com/kSWa1sN1)

**Comment by lubek-dc** [comment]
Done im added Version: 1.16.2, to thecode
