### ISSUE TITLE
mineflayer crashing if someone interacts with blocks nearby

### ISSUE THREAD

**Issue by SwiftFizz** [PrismarineJS/mineflayer#1626]
## Versions
 - mineflayer: 2.41.0
 - server: spigot/paper 1.12.2
 - node: v14.15.4
## Description of the problem

I play on a server where there is a plugin called Orebfuscator that turns ores, chests and other things in to stone when you aren't close to it, to stop X-Ray cheats.

The issue is that if somebody opens a chest in the bots render distance the bot crashes.
I think this is because mineflayer is trying to get the chest type however it is a stone block and there is no chest to get the type of.

```
C:\Users\Samuel\Desktop\Snitch\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getChestType (C:\Users\Samuel\Desktop\Snitch\node_modules\mineflayer\lib\plugins\block_actions.js:39:45)
    at Client.<anonymous> (C:\Users\Samuel\Desktop\Snitch\node_modules\mineflayer\lib\plugins\block_actions.js:69:27)
    at Client.EventEmitter.emit (domain.js:467:12)
    at FullPacketParser.<anonymous> (C:\Users\Samuel\Desktop\Snitch\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (events.js:315:20)
    at FullPacketParser.EventEmitter.emit (domain.js:467:12)
    at addChunk (C:\Users\Samuel\Desktop\Snitch\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\Samuel\Desktop\Snitch\node_modules\readable-stream\lib\_stream_readable.js:280:11)
PS C:\Users\Samuel\Desktop\Snitch> node index.js
```

**Comment by SwiftFizz** [comment]
Fixed the issue by adding a null check at the start of the code 
```
 function getChestType (chestBlock) { // Returns 'single', 'right' or 'left'
    if (bot.supportFeature('doesntHaveChestType')) {
      const facing = parseChestMetadata(chestBlock).facing

      // We have to check if the adjacent blocks in the perpendicular cardinals are the same type
      if(facing == null) return;
      const perpendicularCardinals = Object.keys(FACING_MAP[facing])
      for (const cardinal of perpendicularCardinals) {
        const cardinalOffset = CARDINALS[cardinal]
        if (bot.blockAt(chestBlock.position.plus(cardinalOffset)).type === chestBlock.type) {
          return FACING_MAP[cardinal][facing]
        }
      }

      return 'single'
    } else {
      return parseChestMetadata(chestBlock).type
    }
  }
```

**Comment by rom1504** [comment]
Can you PR the fix ?

**Comment by u9g** [comment]
Is this pr'd? If not, this is an easy pr.

**Comment by Karang** [comment]
Its done

**Comment by ShakalHook** [comment]
The same error occurred
