### ISSUE TITLE
Cannot read property 'id' of undefined after server teleport

### ISSUE THREAD

**Issue by SimplyPancake** [PrismarineJS/mineflayer#1644]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: most recent version as of today
 - server: Paper (waterfall)
 - node: 15.7.0

## Detailed description of a problem
After teleporting to another server (for example from a hub to a survival server), mineflayer waits around for 10 seconds and then prints this error message:
```
C:\Users\Daniel\Desktop\Projecten\toxicmc\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read property 'id' of undefined
    at confirmTransaction (C:\Users\Daniel\Desktop\Projecten\toxicmc\node_modules\mineflayer\lib\plugins\inventory.js:465:29)
    at Client.<anonymous> (C:\Users\Daniel\Desktop\Projecten\toxicmc\node_modules\mineflayer\lib\plugins\inventory.js:566:5)
    at Client.emit (node:events:379:20)
    at FullPacketParser.<anonymous> (C:\Users\Daniel\Desktop\Projecten\toxicmc\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (node:events:379:20)
    at addChunk (C:\Users\Daniel\Desktop\Projecten\toxicmc\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\Daniel\Desktop\Projecten\toxicmc\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (C:\Users\Daniel\Desktop\Projecten\toxicmc\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (C:\Users\Daniel\Desktop\Projecten\toxicmc\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at FullPacketParser._transform (C:\Users\Daniel\Desktop\Projecten\toxicmc\node_modules\protodef\src\serializer.js:89:10)
```

## Your current code
```js

const mineflayer = require('mineflayer')
const mineflayerViewer = require('prismarine-viewer').mineflayer
const sc = require("sponge-case");
const navigatePlugin = require('mineflayer-navigate')(mineflayer);

const readline = require("readline");
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

const bot = mineflayer.createBot({
  host: 'minecraft.scouting.nl',
  port: 25565,
  username: 'xxxxx',
	password: 'xxxxxx',
  version: "1.16.4", // false corresponds to auto version detection (that's the default), put for example "1.8.8" if you need a specific version
  auth: 'mojang' // optional; by default uses mojang, if using a microsoft account, set to 'microsoft'
})

navigatePlugin(bot);

bot.once('spawn', () => {
  // mineflayerViewer(bot, { port: 3007, firstPerson: true })
})

toggleTextTroll = false

function lookAtNearestPlayer() {
	const playerFilter = (entity) => entity.type === 'player'
	const playerEntity = bot.nearestEntity(playerFilter)
	
	if (!playerEntity) {
		return;
	}

	const pos = playerEntity.position.offset(0, 1.7, 0)
	bot.lookAt(pos)
}


bot.on('chat', function(username, message) {
	if (toggleTextTroll) {
		if (username != bot.username) {
			bot.chat(sc.spongeCase(message));
		}
	}
})

// Log errors and kick reasons:
bot.on('kicked', (reason, loggedIn) => console.log(reason, loggedIn))
bot.on('error', err => console.log(err))


```

## Expected behavior
Expected behaviour is for mineflayer to just sit around doing nothing and NOT crashing.

**Comment by u9g** [comment]
What mc version is the server?

**Comment by SimplyPancake** [comment]
The server version is 1.16.4.

**Comment by u9g** [comment]
> The server version is 1.16.4.
> 
> I would also like to point out that the coordinate mapping is not updated after teleporting, however the players' position is correct.

Mineflayer-navigate is deprecated, switch to mineflayer-pathfinder. https://github.com/PrismarineJS/mineflayer-navigate/blob/master/README.md
