### ISSUE TITLE
uncaught error with multiple bots.

### ISSUE THREAD

**Issue by Hotdog-Sama** [PrismarineJS/mineflayer#1686]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper #.#.#
 - node: #.#.#

## Detailed description of a problem
im trying to make a multiple-bot pvp swarm bot, i got multiple bots but now im getting weird uncaught errors, i have the latest version, and i also updated all the libraries.
it also errors, somewhat randomly? like sometimes it will work, but other times it wont.
they also time out, after a while, like, they log off.
also this:

Debugger attached.
```
node:events:355
      throw er; // Unhandled 'error' event
      ^
Waiting for the debugger to disconnect...
Error: Server rejected transaction.
    at clickWindow (c:\Users\King_Periwinkle\node_modules\mineflayer\lib\plugins\inventory.js:473:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async moveSlotItem (c:\Users\King_Periwinkle\node_modules\mineflayer\lib\plugins\inventory.js:486:5)
    at async equip (c:\Users\King_Periwinkle\node_modules\mineflayer\lib\plugins\simple_inventory.js:126:5)
Emitted 'error' event on process instance at:
    at emitUnhandledRejectionOrErr (node:internal/event_target:639:11)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:464:9)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:18:26)
    at MessagePort.callbackTrampoline (node:internal/async_hooks:132:14)
```

and im getting spammed by this:
```
 Failed to retrieve block id, probably exp bottle TypeError: Cannot use 'in' operator to search for 'itemId' in 0
```

## What did you try yet?

yes, i somewhat carefully looked thru the api.
i tried multiple.js from pathfinder, it returned the uncaught error again.

## Your current code
```js
const mineflayer = require('mineflayer')
const { pathfinder, Movements, goals} = require('mineflayer-pathfinder')
const { GoalInvert, GoalFollow } = require('mineflayer-pathfinder').goals
const pvp = require('mineflayer-pvp').plugin
const armorManager = require('mineflayer-armor-manager')
mineflayer.multiple = (bots, constructor) => {
  const { Worker, isMainThread, workerData } = require('worker_threads')
  if (isMainThread) {
    const threads = []
    for (const i in bots) {
      threads.push(new Worker(__filename, { workerData: bots[i] }))
    }
  } else {
    constructor(workerData)
  }
}

const bots = []
for (let i = 0; i < 5; i++) {
  bots.push({ username: `Bot${i}` })
}

mineflayer.multiple(bots, ({ username }) => {
  const bot = mineflayer.createBot({ username, port: 53610 })

  bot.loadPlugin(pathfinder)
  bot.loadPlugin(pvp)
  bot.loadPlugin(armorManager)

  bot.on('playerCollect', (collector, itemDrop) => {
    if (collector !== bot.entity) return
  
    setTimeout(() => {
      const sword = bot.inventory.items().find(item => item.name.includes('sword'))
      if (sword) bot.equip(sword, 'hand')
    }, 150)
  })
  
  bot.on('playerCollect', (collector, itemDrop) => {
    if (collector !== bot.entity) return
  
    setTimeout(() => {
      const shield = bot.inventory.items().find(item => item.name.includes('shield'))
      if (shield) bot.equip(shield, 'off-hand')
    }, 250)
  })
  
  let guardPos = null
  
  function guardArea (pos) {
    guardPos = pos.clone()
  
    if (!bot.pvp.target) {
      moveToGuardPos()
    }
  }
  
  function stopGuarding () {
    guardPos = null
    bot.pvp.stop()
    bot.pathfinder.setGoal(null)
  }
  
  function moveToGuardPos () {
    const mcData = require('minecraft-data')(bot.version)
    bot.pathfinder.setMovements(new Movements(bot, mcData))
    bot.pathfinder.setGoal(new goals.GoalBlock(guardPos.x, guardPos.y, guardPos.z))
  }
  
  bot.on('stoppedAttacking', () => {
    if (guardPos) {
      moveToGuardPos()
    }
  })
  
  bot.on('physicTick', () => {
    if (bot.pvp.target) return
    if (bot.pathfinder.isMoving()) return
  
    const entity = bot.nearestEntity()
    if (entity) bot.lookAt(entity.position.offset(0, entity.height, 0))
  })
  
  bot.on('physicTick', () => {
    if (!guardPos) return
  
    const filter = e => e.type === 'mob' && e.position.distanceTo(bot.entity.position) < 16 &&
                        e.mobType !== 'Armor Stand' // Mojang classifies armor stands as mobs for some reason?
  
    const entity = bot.nearestEntity(filter)
    if (entity) {
      bot.pvp.attack(entity)
    }
  })
  
  bot.on('chat', (username, message) => {
    if (message === 'guard') {
      const player = bot.players[username]
  
      if (!player) {
        bot.chat("I can't see you.")
        return
      }
  
      bot.chat('I will guard that location.')
      guardArea(player.entity.position)
    }
  
    if (message === 'fight me') {
      const player = bot.players[username]
  
      if (!player) {
        bot.chat("I can't see you.")
        return
      }
  
      bot.chat('Prepare to fight!')
      bot.pvp.attack(player.entity)
    }
  
    if (message === 'stop') {
      bot.chat('I will no longer guard this area.')
      stopGuarding()
    }
  
    if (message === 'hp') {
      bot.chat(bot.health)
    }
  
  })
})
```

## Expected behavior
me to be able to use multiple bots at the same time.

## Additional context
i dont think so, tell me if i missed anything.

**Comment by sefirosweb** [comment]
Hi @Hotdog-Sama on my case i used a diferent threads for do it,

I used child process:


index.js
```js

const cp = require('child_process')
const path = require('path')

function startBot (botName, password) {
  const command = 'node ' + path.join(__dirname, 'start_bot') + ' ' + botName
  cp.exec(command, (err, stdout, stderr) => {
    if (err) {
      console.log(`Error: ${err}`)
      console.log(`Bot broken: ${botName}`)
      console.log(`Restarting bot ${botName}...`)
      setTimeout(() => startBot(botName, password), 1000)
      return
    }

    if (stdout) {
      console.log(`Stdout: ${stdout}`)
    }

    if (stderr) {
      console.log(`Stderr: ${stderr}`)
    }
  })
}

const botsToStart = [
  { username: 'Miner1' },
  { username: 'Guard' },
]

let i = 0
function runNextBot () {
  const botToStart = botsToStart[i]
  i++
  if (i <= botsToStart.length) {
    setTimeout(() => {
      startBot(botToStart.username)
      runNextBot()
    }, 3000) //I recommended you wait for dont stuck the server they can detect too many connections at same time

  }
};

runNextBot()

```

start_bot.js
```js
const botName = process.argv[2]
const botPassword = process.argv[3]

createNewBot(botName, botPassword)

function createNewBot (botName, botPassword = '') {
  const bot = mineflayer.createBot({
    username: botName,
    host: config.server,
    port: config.port
  })
  bot.once('spawn', () => {
...
    })
```

**Comment by extremeheat** [comment]
> Hi @Hotdog-Sama on my case i used a diferent threads for do it,
> 
> I used child process:
> 
> index.js
> 
> ```js
> const cp = require('child_process')
> const path = require('path')
> 
> function startBot (botName, password) {
>   const command = 'node ' + path.join(__dirname, 'start_bot') + ' ' + botName
>   cp.exec(command, (err, stdout, stderr) => {
>     if (err) {
>       console.log(`Error: ${err}`)
>       console.log(`Bot broken: ${botName}`)
>       console.log(`Restarting bot ${botName}...`)
>       setTimeout(() => startBot(botName, password), 1000)
>       return
>     }
> 
>     if (stdout) {
>       console.log(`Stdout: ${stdout}`)
>     }
> 
>     if (stderr) {
>       console.log(`Stderr: ${stderr}`)
>     }
>   })
> }
> 
> const botsToStart = [
>   { username: 'Miner1' },
>   { username: 'Guard' },
> ]
> 
> let i = 0
> function runNextBot () {
>   const botToStart = botsToStart[i]
>   i++
>   if (i <= botsToStart.length) {
>     setTimeout(() => {
>       startBot(botToStart.username)
>       runNextBot()
>     }, 3000) //I recommended you wait for dont stuck the server they can detect too many connections at same time
> 
>   }
> };
> 
> runNextBot()
> ```
> 
> start_bot.js
> 
> ```js
> const botName = process.argv[2]
> const botPassword = process.argv[3]
> 
> createNewBot(botName, botPassword)
> 
> function createNewBot (botName, botPassword = '') {
>   const bot = mineflayer.createBot({
>     username: botName,
>     host: config.server,
>     port: config.port
>   })
>   bot.once('spawn', () => {
> ...
>     })
> ```

Those aren’t threads. Those are separate processes.

**Comment by sefirosweb** [comment]
Yes I'm sorry that's what I wanted to say,

I understood you want to call more one bot in same process for shared some variables?

If one bot stucks or have an a bug (this happens alot) maybe can crash all bots

**Comment by Hotdog-Sama** [comment]
oh, hmm intereseting, ill try it

**Comment by Hotdog-Sama** [comment]
wow, it actually works! thanks @sefirosweb!!!!
