### ISSUE TITLE
MCData cannot read property "value" of null

### ISSUE THREAD

**Issue by JJCprodeveloper** [PrismarineJS/mineflayer#1698]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest version
 - server: vanilla/spigot/paper paper
 - node: idk

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?
i was building a follow bot that follows players with pathfinder plugin
but this is not most important
BECUASE it already fails at the line 
     const mcData = require('minecraft-data')(bot.version);
## What did you try yet?
     const mcData = require('minecraft-data')(bot.version);
Did you try any method from the API?
i tried making bot.version 1.16.5 to make it most updated but it has not use
Did you try any example? Any error from those?

## Your current code
```js
C:\Users\jjcde\AppData\Roaming\npm\afkbot\node_modules\prismarine-biome\index.js:6
  biomes = require('minecraft-data')(mcVersion).biomes
                                               ^

TypeError: Cannot read property 'biomes' of null
    at loader (C:\Users\jjcde\AppData\Roaming\npm\afkbot\node_modules\prismarine-biome\index.js:6:48)
    at loader (C:\Users\jjcde\AppData\Roaming\npm\afkbot\node_modules\prismarine-block\index.js:7:39)
    at new Movements (C:\Users\jjcde\AppData\Roaming\npm\afkbot\node_modules\mineflayer-pathfinder\lib\movements.js:67:46)
    at init (C:\Users\jjcde\AppData\Roaming\npm\afkbot\index.js:36:26)
    at Object.<anonymous> (C:\Users\jjcde\AppData\Roaming\npm\afkbot\index.js:15:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
/*
Some code here, replace this
*/


```

## Expected behavior
I JUST WANTED IT TO LOAD PERFECTLY 

## Additional context
HELP PLS I AM SO HELPLESS I NEED TO GET THIS DONE QUICKLY 
I WILL GIVE YOU MY MINECRAFT DOG SO PLS BE QUICK ;-;

**Comment by Karang** [comment]
How do you set the bot version ?

PS: caps lock won't help you...

**Comment by Hotdog-Sama** [comment]
lmfao "i will give you my minecraft dog"

**Comment by Zn10plays** [comment]
Try updating mcData to the latest, by running:

>npm i minecraft-data@latest
