### ISSUE TITLE
Bot that saves chat

### ISSUE THREAD

**Issue by ntloff** [PrismarineJS/mineflayer#1753]
how 2 save all chat messages 2 .txt file?

**Comment by DrMoraschi** [comment]
Use fs to write to a txt file on "chat" event

**Comment by ntloff** [comment]
```
internal/fs/utils.js:779
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of ChatMessage
    at Object.writeFile (fs.js:1436:5)
    at EventEmitter.<anonymous> (C:\Users\test\Desktop\sp\bot.js:61:6)
    at EventEmitter.emit (events.js:315:20)
    at Client.<anonymous> (C:\Users\test\Desktop\sp\node_modules\mineflayer\lib\plugins\chat.js:79:9)
    at Client.emit (events.js:315:20)
    at FullPacketParser.<anonymous> (C:\Users\test\Desktop\sp\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (events.js:315:20)
    at addChunk (C:\Users\test\Desktop\sp\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\test\Desktop\sp\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (C:\Users\test\Desktop\sp\node_modules\readable-stream\lib\_stream_readable.js:241:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
code:
```
bot.on('message', message => {
  fs.writeFile('c:\\logs.txt', message, err => {
    if (err) {
      console.error(err)
      return
    }
  })
```

**Comment by ntloff** [comment]
code used 4m https://nodejs.dev/learn/writing-files-with-nodejs

**Comment by DrMoraschi** [comment]
Its message.toString()

**Comment by ntloff** [comment]
this code replaces all file content
how 2 save all chat

**Comment by ntloff** [comment]
il use Append to a file?

**Comment by ntloff** [comment]
k ty it worx
