### ISSUE TITLE
I am geting this error since i updated mineflayer

### ISSUE THREAD

**Issue by CyberVictoryMan** [PrismarineJS/mineflayer#1765]
```D:\Coding Stuff\MinecraftBOt\node_modules\mineflayer\index.js:63
  options.username = options.username ?? 'Player'
                                       ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\Coding Stuff\MinecraftBOt\code.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
```
code is the same example 
pls help me

**Comment by extremeheat** [comment]
Update your node version

**Comment by CyberVictoryMan** [comment]
sowwy for the silly question :)
