### ISSUE TITLE
  options.username = options.username ?? '  SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by WolfGames** [PrismarineJS/mineflayer#1802]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.4.0
 - server: vanilla/spigot/paper 1.13.2
 - node: 12.19.0

## Detailed description of a problem

I see this error on bot console: path\to\bot\node_modules\mineflayer\index.js:63
  options.username = options.username ?? 'Player'
                                       ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\Minecraft\NODE\Testbot\main.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)

## What did you try yet?

Did you try any method from the API?
i copied code from README
Did you try any example? Any error from those?

## Your current code
```js

/*
console.log("init")

const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: 'localhost',             // minecraft server ip
  username: 'lololol', // minecraft username
  //password: '12345678',          // minecraft password, comment out if you want to log into online-mode=false servers
  // port: 25565,                // only set if you need a port that isn't 25565
  version: "1.13.2",             // only set if you need a specific version or snapshot (ie: "1.8.9" or "1.16.5"), otherwise it's set automatically
  // auth: 'mojang'              // only set if you need microsoft auth, then set this to 'microsoft'
})

bot.on('chat', (username, message) => {
  if (username === bot.username) return
  bot.chat(message)
})

// Log errors and kick reasons:
bot.on('kicked', console.log)
bot.on('error', console.log)
*/


```

## Expected behavior
when i run bot i see error on console.
path\to\bot\Testbot\node_modules\mineflayer\index.js:63
  options.username = options.username ?? 'Player'
                                       ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:931:16)
    at Module._compile (internal/modules/cjs/loader.js:979:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\Minecraft\NODE\Testbot\main.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)

**Comment by Moondarker** [comment]
https://github.com/PrismarineJS/mineflayer#installation

**Comment by extremeheat** [comment]
I think an npm install script could be added to check the node version then print an error during the install, should avoid a lot of these issues

**Comment by Moondarker** [comment]
Good idea, @extremeheat

**Comment by rom1504** [comment]
We have https://github.com/PrismarineJS/mineflayer/blob/master/index.js#L1

We have strict engine in package.json which already gives an error on wrong node versions

What's missing is to not expose this index.js but instead one that works on all node and import the current one.

That way people on old node can load the index which will tell them to update

**Comment by Moondarker** [comment]
> What's missing is to not expose this index.js but instead one that works on all node and import the current one.

Can't that be done in the first lines of `index.js`? Just throw an error and exit if the version is too old

**Comment by Moondarker** [comment]
Nvm, it's already there ,_,

**Comment by rom1504** [comment]
Actually just noticed https://github.com/PrismarineJS/mineflayer/blob/master/package.json#L18 isn't strict, it should be

**Comment by Moondarker** [comment]
It is, at least in .npmrc

**Comment by rom1504** [comment]
Yeah but actually that doesn't do what we want

https://stackoverflow.com/a/41620850/1658314 has all the information

So we can either do what I said with another index or do this as a postinstall script like extremeheat said

**Comment by WolfGames** [comment]
I updated node is and it works but I forgot to close issue
