### ISSUE TITLE
make the bot work with coordinates

### ISSUE THREAD

**Issue by Msgumor** [PrismarineJS/mineflayer#1860]
bot.on('login', function() {
	console.log("connected.");
	bot.chat('Hello')
    bot.navigate.to(bot.entity.position.offset(9, 62, -42))
});

Error:
/home/container/node_modules/minecraft-protocol/src/transforms/framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read property 'to' of undefined
    at EventEmitter.<anonymous> (/home/container/index.js:16:18)
    at EventEmitter.emit (node:events:381:22)
    at Client.<anonymous> (/home/container/node_modules/mineflayer/lib/plugins/game.js:43:9)
    at Client.emit (node:events:381:22)
    at FullPacketParser.<anonymous> (/home/container/node_modules/minecraft-protocol/src/client.js:91:12)
    at FullPacketParser.emit (node:events:369:20)
    at addChunk (/home/container/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/container/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (/home/container/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (/home/container/node_modules/readable-stream/lib/_stream_transform.js:139:32)

**Comment by DrMoraschi** [comment]
mineflayer-navigate is deprecated, use mineflayer-pathfinder instead, and probably you didn't load the plugin

**Comment by Msgumor** [comment]
the error is the same

**Comment by Msgumor** [comment]
and how to make the bot move along the coordinates as you type

**Comment by DrMoraschi** [comment]
As I said, use mineflayer-pathfinder

**Comment by Msgumor** [comment]
but through it the same error.

**Comment by DrMoraschi** [comment]
What's your updated code

**Comment by Msgumor** [comment]
const Discord = require('discord.js');
const mineflayer = require('mineflayer')
const pathfinder = require('mineflayer-pathfinder')
const client = new Discord.Client();

const bot = mineflayer.createBot({
  host: '127.0.0.1', // host
  port: 25565,     // port
  username: 'Bot', // username
  version: '1.12.2'                 // version.
})

bot.on('login', function() {
	console.log("connected.");
	bot.chat('!Hello')
    bot.navigate.to(bot.entity.position.offset(9, 62, -42))
});

**Comment by DrMoraschi** [comment]
You are not loading pathfinder, look at the examples, also bot.navigate won't exist, it would be bot.pathfinder

**Comment by Msgumor** [comment]
C:\Users\User\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^

TypeError: bot.pathfinder.to is not a function
    at EventEmitter.<anonymous> (C:\Users\User\Desktop\bots.js:20:20)
    at EventEmitter.emit (events.js:327:22)
    at Client.<anonymous> (C:\Users\User\node_modules\mineflayer\lib\plugins\game.js:43:9)
    at Client.emit (events.js:327:22)
    at FullPacketParser.<anonymous> (C:\Users\User\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (events.js:315:20)
    at addChunk (C:\Users\User\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\User\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (C:\Users\User\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (C:\Users\User\node_modules\readable-stream\lib\_stream_transform.js:139:32)

**Comment by Msgumor** [comment]
const Discord = require('discord.js');
const mineflayer = require('mineflayer')
const pathfinder = require('mineflayer-pathfinder').pathfinder
const Movements = require('mineflayer-pathfinder').Movements
const { GoalNear } = require('mineflayer-pathfinder').goals
const client = new Discord.Client();

const bot = mineflayer.createBot({
host: '127.0.0.1', // host
port: 25565, // port
username: 'Bot', // username
version: '1.12.2' // version.
})

bot.loadPlugin(pathfinder)

bot.on('login', function() {
	console.log("connected.");
	bot.chat('!Hello')
    bot.pathfinder.to(bot.entity.position.offset(9, 62, -42))

**Comment by BlueBurgersTDD** [comment]
bot.pathfinder.setGoal(new GoalNear(x, y, z, 1))
