### ISSUE TITLE
Error when starting bot

### ISSUE THREAD

**Issue by MilanTheMen009** [PrismarineJS/mineflayer#2052]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.8.9
 - server: paper 1.16.x-1.17.x
 - node: 14.17.2

## Detailed description of a problem
I am getting an error when i try to start my bot, its not because a syntax error, this is the error:
```
/home/opc/EternalPracticeBot/node_modules/minecraft-protocol/src/transforms/framing.js:67
          } else { throw e }
                   ^

Error: Version 1.17.1 is not supported.
    at Client.next (/home/opc/EternalPracticeBot/node_modules/mineflayer/lib/loader.js:107:13)
    at Object.onceWrapper (events.js:481:28)
    at Client.emit (events.js:375:28)
    at /home/opc/EternalPracticeBot/node_modules/minecraft-protocol/src/client/autoVersion.js:53:12
    at Client.<anonymous> (/home/opc/EternalPracticeBot/node_modules/minecraft-protocol/src/ping.js:39:7)
    at Object.onceWrapper (events.js:482:26)
    at Client.emit (events.js:375:28)
    at FullPacketParser.<anonymous> (/home/opc/EternalPracticeBot/node_modules/minecraft-protocol/src/client.js:91:12)
    at FullPacketParser.emit (events.js:375:28)
    at addChunk (/home/opc/EternalPracticeBot/node_modules/readable-stream/lib/_stream_readable.js:298:12)
```

## What did you try yet?
I tried reinstalling Node and Mineflayer
And i searched the internet for a fix

## Your current code
```js


const mineflayer = require('mineflayer')
var lasttime = -1;
var moving = 0;
var connected = 0;
var actions = [ 'forward', 'back', 'left', 'right']
var lastaction;
var pi = 3.14159;
var moveinterval = 2;
var maxrandom = 5;
var bot = mineflayer.createBot({
  host: 'eternalpractice.minefort.com',
  port: 25565,
  username: 'Account_Email',
  password: 'Account_Password'
})
function getRandomArbitrary(min, max) {
       return Math.random() * (max - min) + min;

}
bot.on('login',function(){
	console.log("Logged In")
});
bot.on('time', function() {
    if (connected <1) {
        return;
    }
    if (lasttime<0) {
        lasttime = bot.time.age;
    } else {
        var randomadd = Math.random() * maxrandom * 20;
        var interval = moveinterval*20 + randomadd;
        if (bot.time.age - lasttime > interval) {
            if (moving == 1) {
                bot.setControlState(lastaction,false);
                moving = 0;
                lasttime = bot.time.age;
            } else {
                var yaw = Math.random()*pi - (0.5*pi);
                var pitch = Math.random()*pi - (0.5*pi);
                bot.look(yaw,pitch,false);
                lastaction = actions[Math.floor(Math.random() * actions.length)];
                bot.setControlState(lastaction,true);
                moving = 1;
                lasttime = bot.time.age;
                bot.activateItem();
            }
        }
    }
});

bot.on('spawn',function() {
    connected=1;
});



```

## Expected behavior
The bot to join the server and move around

## Additional context
None

**Comment by TheBlueBurger** [comment]
It says the error: `Error: Version 1.17.1 is not supported.`.
You could either
- Wait until 1.17.1 support is released
- Add Protocolsupport or a similar plugin and add the version option to the `createBot` function

**Comment by MilanTheMen009** [comment]
Thanks! Added the version option to the createBot function and it works now!
