### ISSUE TITLE
ERROR: chatmessage.fromnotch()

### ISSUE THREAD

**Issue by Torono909** [PrismarineJS/mineflayer#2144]
error: C:\Users\hi\Desktop\Projects\Bots\Artica\node_modules\mineflayer\lib\plugins\chat.js:108                                                  
    const msg = ChatMessage.fromNotch(packet.message)                
                            ^                                        
                                                                     
TypeError: ChatMessage.fromNotch is not a function                   
    at Client.<anonymous> (C:\Users\hi\Desktop\Projects\Bots\Artica\node_modules\mineflayer\lib\plugins\chat.js:108:29)                   
    at Client.emit (events.js:315:20)                                
    at FullPacketParser.<anonymous> (C:\Users\hi\Desktop\Projects\Bots\Artica\node_modules\minecraft-protocol\src\client.js:91:12)        
    at FullPacketParser.emit (events.js:315:20)                      
    at addChunk (C:\Users\hi\Desktop\Projects\Bots\Artica\node_modules\minecraft-protocol\node_modules\readable-stream\lib\_stream_readable.js:298:12)                                                         
    at readableAddChunk (C:\Users\hi\Desktop\Projects\Bots\Artica\node_modules\minecraft-protocol\node_modules\readable-stream\lib\_stream_readable.js:280:11)                                                 
    at FullPacketParser.Readable.push (C:\Users\hi\Desktop\Projects\Bots\Artica\node_modules\minecraft-protocol\node_modules\readable-stream\lib\_stream_readable.js:241:10)                                   
    at FullPacketParser.Transform.push (C:\Users\hi\Desktop\Projects\Bots\Artica\node_modules\minecraft-protocol\node_modules\readable-stream\lib\_stream_transform.js:139:32)                                 
    at FullPacketParser._transform (C:\Users\hi\Desktop\Projects\Bots\Artica\node_modules\minecraft-protocol\node_modules\protodef\src\serializer.js:89:10)                                                    
    at FullPacketParser.Transform._read (C:\Users\hi\Desktop\Projects\Bots\Artica\node_modules\minecraft-protocol\node_modules\readable-stream\lib\_stream_transform.js:177:10)   
code: `const mineflayer = require('mineflayer')
const vec3 = require('vec3')
const bot = mineflayer.createBot({
	host: '78.46.105.177',
	port: 25895,
	username: '_Crystal_',
	version: '1.17.1'
});

bot.loadPlugin(vec3)

bot.on('login', function(packet) {
	bot.chat("https://discord.gg/jVu2SGNUnp")
	bot.chat("Type $help for help!")
})

bot.on('chat', (username, message) => {
	if (message === '$rules') {
		bot.chat("Fuck Off")
	}
		if (message === '$opme') {
		bot.chat("Opped " + username)
	}
		if (message === '$say ' + message) {
		bot.chat("...")
		bot.quit()
		bot.end()
	}
	if (message === '$kill') {
		bot.chat("/kill")
	}
	if (message === '$schematicate') {
	bot.chat("Schematica plugin is not installed on this server")
	}
	if (message === '$the-biggest-math-question') {
		bot.chat("math question: 100 % 100 / 1000 - 1000000 + 9999999 / 199876687867 % 75765876895675896 * 99999999999999999999999999999999999999999999999")
		bot.chat(100 % 100 / 1000 - 1000000 + 9999999 / 199876687867 % 75765876895675896 * 99999999999999999999999999999999999999999999999)
	}
	if (message === '$tpy') {
		bot.chat("/tpy Chocolate_Twit")
	}
	if (message === '$end') {
		bot.end()
	}
	if (message === '$tptome') {
		bot.chat("/tpa " + username)
	}
	if (message === "$skin yuseifudo") {
		bot.chat("/skin set yuseifudo")
	}
	if (message === "$warp home") {
		bot.chat("/gwarp home")
	}
	if (message === "are you fucking gay _Crystal_?") {
		bot.chat("/msg " + username + "Your Mom Dosent Like You Your a dissapointment to your mom bitch")
	}
	if (message === "$help") {
		bot.chat("$help [Shows A List Of Commands], $tptome [I Will Teleport To You When You Use This Commad], $the-biggest-math-question [biggest math question], $rules [rules]")
	}
	if (message === "Your IP changed please login again") {
	bot.chat("/login ptmine")
	}
	console.log("[" + username + "]" + message)
})
bot.on('kicked', (reason) => {
	console.log("I Was Kicked Because Of " + reason)
})
bot.on('killed', (username) => {
	console.log("I Was Killed By " + username)
})
bot.on('left', () => {
	bot.end()
})
bot.on('chat', (message) => {
	if (message === '$endcrystalme') {
		/*const surround = bot.place*/
		console.log("[_Crystal_] I CANT ENDER CRYSTAL HIMMMMM")
		/* /* *\ means ignore line also the upper thing is ignore line*/
	}
})`

**Comment by Torono909** [comment]
HELP pls
