### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by IceTank** [PrismarineJS/mineflayer#2186]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.11.0
 - server: vanilla / any?
 - node: 14

## Detailed description of a problem
When the server is lagging and the bot tries to place a block if can result in this

```
(node:12924) UnhandledPromiseRejectionWarning: Error: Event blockUpdate:(-70361, 64, -63508) did not fire within timeout of 5000ms
    at onceWithCleanup (D:\NodeJS\mineflayer-pathfinder\node_modules\mineflayer\lib\promise_utils.js:72:26)
    at placeBlockWithOptions (D:\NodeJS\mineflayer-pathfinder\node_modules\mineflayer\lib\plugins\place_block.js:13:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async placeBlock (D:\NodeJS\mineflayer-pathfinder\node_modules\mineflayer\lib\plugins\place_block.js:24:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 
To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:12924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Expected behavior
Not crashing the process

**Comment by u9g** [comment]
try catch it?

**Comment by IceTank** [comment]
Hm my bad mistake some debugging for an actual error. I though that it would for some reason not catch the timeout for placing blocks.

**Comment by sefirosweb** [comment]
@IceTank  how did you resolve the issue?

I'm tryng to place blocks but the bots breaks fromo latests mineflayer version 3.11,

I tried with promises & await,

```js
try {
        await this.bot.placeBlock(block, vec3(0, 1, 0))
      } catch (err) {
        console.log(err)
      }

// -- and --

  this.bot.placeBlock(block, vec3(0, 1, 0))
        .then(() => {
          resolve()
        })
        .catch((err) => {
          console.log(err)
        })
```
