### ISSUE TITLE
Crash (even with try catch) on unsupported version

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer#2191]
- [X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest
 - server: vanilla/spigot/paper unsupported
 - node: v16.4.0

## Detailed description of a problem
When the bot encounters a server with an unsupported version, it straight up crashes EVERYTHING.
One is not able to try catch because of how https://github.com/PrismarineJS/mineflayer/blob/master/lib/loader.js is coded (at line 108 is the crash).
I think 

## Your current code
```js
try {		// Does not work https://github.com/PrismarineJS/mineflayer/blob/master/lib/loader.js line 108 crashes whole dc bot.
			const bot = Mineflayer.createBot({
				host: address.host,
				port: address.port,
				username: cred.email,
				password: cred.password,
				auth: cred.auth
			})

			setTimeout(() => {
				if(bot) {
					bot.end()
					resolve(new Error(`Bot timed out. ${address.host}`))
				}
			}, timeout)

			bot.once('login', () => {
				bot.end()
				resolve(false)
			})

			bot.on('error', function (err) {
				bot.end()
				resolve(err)
			})

			bot.on('kicked', function (reason, loggedIn) {
				bot.end()
				if(reason.toString().includes('white') && reason.toString().includes('list')) {
					resolve(true)
				} else {
					resolve(new Error(`Kicked: ${reason.toString()} ${address.host}`))
				}
			})

			bot.on('chat', function (username, message) {
				// No no no console.log(`${username}, ${message}`)
			})
		} catch (err) {
			resolve(err as Error)
		}
```

## Expected behavior
I should be able to try catch this error. I am looking forward to any kind of help, thanks for the library!

```
Error: Version 1.7.10 is not supported.
    at Client.next (/home/sinan/minecraft/minecraft-bot/node_modules/mineflayer/lib/loader.js:108:13)
    at Object.onceWrapper (node:events:513:28)
    at Client.emit (node:events:406:35)
    at /home/sinan/minecraft/minecraft-bot/node_modules/minecraft-protocol/src/client/autoVersion.js:53:12
    at Client.<anonymous> (/home/sinan/minecraft/minecraft-bot/node_modules/minecraft-protocol/src/ping.js:39:7)
    at Object.onceWrapper (node:events:514:26)
    at Client.emit (node:events:394:28)
    at FullPacketParser.<anonymous> (/home/sinan/minecraft/minecraft-bot/node_modules/minecraft-protocol/src/client.js:91:12)
    at FullPacketParser.emit (node:events:394:28)
    at addChunk (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at FullPacketParser._transform (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/src/serializer.js:89:10)
    at FullPacketParser.Transform._read (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at FullPacketParser.Transform._write (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:164:83)
```

**Comment by SinanAkkoyun** [comment]
I am not complaining about that mineflayer currently does not support 1.17+. I just need to know how to try catch this error without prechecking the versions

Thank you!

**Comment by u9g** [comment]
> I am not complaining about that mineflayer currently does not support 1.17+. I just need to know how to try catch this error without prechecking the versions
> 
> Thank you!

mineflayer does support 1.17+, thats 1.7.10

**Comment by SinanAkkoyun** [comment]
> > I am not complaining about that mineflayer currently does not support 1.17+. I just need to know how to try catch this error without prechecking the versions
> > Thank you!
> 
> mineflayer does support 1.17+, thats 1.7.10

I see, do you know how to catch that error thrown at line 110 of loader.js?

**Comment by SinanAkkoyun** [comment]
Is there any fix or solution to the problem that the whole app crashes on unsupported versions?

**Comment by u9g** [comment]
Just tested this:
```js
const mineflayer = require('mineflayer')

try {
  const bot = mineflayer.createBot({ version: '1.7.10' })
} catch (e) {
  console.log('caught')
  console.error(e)
}

console.log('keep going')
```
and it catches just fine and runs keep going

**Comment by SinanAkkoyun** [comment]
I am so sorry for opening that issue, for some reason it now works fine and I can catch it myself... Thank you and thanks for the awesome lib!
