### ISSUE TITLE
ChatMessage.fromNotch is not a function

### ISSUE THREAD

**Issue by SinanAkkoyun** [PrismarineJS/mineflayer#2195]
- [X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest
 - server: vanilla/spigot/paper 1.16.4
 - node: latest

## Detailed description of a problem
When my bot tries to join a 1.16.4 server, it crashes with the exception:
TypeError: ChatMessage.fromNotch is not a function

## Your current code
```js
new Promise(async (resolve, reject) => {
	try {
		console.log(`Now connecting to ${address.host}:${address.port}`)
		const bot = Mineflayer.createBot({
			host: address.host,
			port: address.port,
			username: cred.email,
			password: cred.password,
			auth: cred.auth
		})

		setTimeout(() => {
			if(bot) {
				bot.end()
				resolve(new Error(`Bot timed out. ${address.host}`))
			}
		}, timeout)

		bot.once('login', () => {
			bot.end()
			resolve(false)
		})

		bot.on('error', function (err) {
			bot.end()
			resolve(err)
		})

		bot.on('kicked', function (reason, loggedIn) {
			bot.end()
			if(reason.toString().includes('white') && reason.toString().includes('list')) {
				resolve(true)
			} else {
				resolve(new Error(`Kicked: ${reason.toString()} ${address.host}`))
			}
		})
	} catch (err) {
		resolve(err as Error)
	}
```

## Expected behavior
It should not throw the error

```
TypeError: ChatMessage.fromNotch is not a function
    at Client.<anonymous> (/home/sinan/minecraft/minecraft-bot/node_modules/mineflayer/lib/plugins/chat.js:108:29)
    at Client.emit (node:events:394:28)
    at FullPacketParser.<anonymous> (/home/sinan/minecraft/minecraft-bot/node_modules/minecraft-protocol/src/client.js:91:12)
    at FullPacketParser.emit (node:events:394:28)
    at addChunk (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at FullPacketParser._transform (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/src/serializer.js:89:10)
    at FullPacketParser.Transform._read (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at FullPacketParser.Transform._write (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at FullPacketParser.Writable.write (/home/sinan/minecraft/minecraft-bot/node_modules/protodef/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Decompressor.ondata (/home/sinan/minecraft/minecraft-bot/node_modules/minecraft-protocol/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at Decompressor.emit (node:events:394:28)
[ERROR] 18:35:55 TypeError: ChatMessage.fromNotch is not a function
```

Thanks for any help

Also, the try catch does not catch that error and my whole application crashes

**Comment by u9g** [comment]
`npm update --depth 999`, if that doesn't work run: `npm uninstall mineflayer` then `npm install mineflayer`
