### ISSUE TITLE
TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.

### ISSUE THREAD

**Issue by Trentyn** [PrismarineJS/mineflayer#2229]
TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at Client._validateOptions (C:\Users\Alex\Desktop\S-b\node_modules\discord.js\src\client\Client.js:544:13)
    at new Client (C:\Users\Alex\Desktop\S-b\node_modules\discord.js\src\client\Client.js:73:10)
    at Object.<anonymous> (C:\Users\Alex\Desktop\S-b\index.js:3:16)   
    at Module._compile (internal/modules/cjs/loader.js:1072:14)       
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)  
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  [Symbol(code)]: 'CLIENT_MISSING_INTENTS'

**Comment by u9g** [comment]
Please try googling the phrase before making an issue, If you google, “Valid intents must be provided for the Client.”, you will see that it is solved in the first result and that it isn’t part of mineflayer.
