### ISSUE TITLE
An invalid destination host was provided while using SOCKS5

### ISSUE THREAD

**Issue by oblivioness** [PrismarineJS/mineflayer#2343]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
+-- mineflayer@3.11.2
`-- socks@2.6.1
 - server: spigot (git-Spigot-cbd1a1b-009d8af) (latest)

## Detailed description of a problem
SO, I checked if the destination was really invalid, but it was working when I took off proxy.
And the proxies are working, I checked them.

```
SocksClientError: An invalid destination host was provided.
    at Object.validateSocksClientOptions (C:\Users\admin\Documents\minecraft-stress-tester\node_modules\socks\build\common\helpers.js:23:15)
    at C:\Users\admin\Documents\minecraft-stress-tester\node_modules\socks\build\client\socksclient.js:43:27
    at new Promise (<anonymous>)
    at Function.createConnection (C:\Users\admin\Documents\minecraft-stress-tester\node_modules\socks\build\client\socksclient.js:40:16)
    at Object.connect (C:\Users\admin\Documents\minecraft-stress-tester\index.js:15:16)
    at C:\Users\admin\Documents\minecraft-stress-tester\node_modules\minecraft-protocol\src\ping.js:76:13
    at new Promise (<anonymous>)
    at ping (C:\Users\admin\Documents\minecraft-stress-tester\node_modules\minecraft-protocol\src\ping.js:34:10)
    at cbPing (C:\Users\admin\Documents\minecraft-stress-tester\node_modules\minecraft-protocol\src\ping.js:10:23)
    at module.exports (C:\Users\admin\Documents\minecraft-stress-tester\node_modules\minecraft-protocol\src\client\autoVersion.js:12:3) {
  options: {
    proxy: {
      host: '72.210.252.137',
      port: 4145,
      type: 5
    },
    command: 'connect',
    destination: { host: 'my ip was here', port: '25565' }
  }
}
```

## Your current code
```js
const mineflayer = require('mineflayer')

const {host, port} = require('./config.json')

const {count} = require('./config.json')
const {prefix} = require('./config.json')

const SocksClient = require('socks').SocksClient;

let bots = []

for (let i = 0; i < count; i++) {
    bots.push(mineflayer.createBot({
		connect: (client) => {
			SocksClient.createConnection({
			  proxy: {
				host: '72.210.252.137',
				port: 4145,
				type: 5,
			  },
			  command: 'connect',
			  destination: {
				host: host,
				port: port,
			  }
			}, (err, info) => {
			  if (err) {
				console.log(err)
				return
			  }
			  client.setSocket(info.socket)
			  client.emit('connect')
			})
		},

        port: port,
        username: `${prefix}${between(1, 99999)}`,
    }))
}

module.exports = {
    bots: bots
}

function between(min, max) {
    return Math.floor(
        Math.random() * (max - min) + min
    )
}
```

I want it to connect to server >:(

**Comment by U5B** [comment]
Is the ip a SRV record? (e.g a domain?)
passing in a SRV ip will not automatically resolve the ip, you will need to resolve the ip yourself
https://github.com/PrismarineJS/node-minecraft-protocol/blob/010d6b229c88b7cc0d7c51efb01a5ea510bdb58a/src/client/tcp_dns.js#L21
See how mineflayer/node-minecraft-protocol does it.
