### ISSUE TITLE
Help plzz~

### ISSUE THREAD

**Issue by AdminHcat** [PrismarineJS/mineflayer#2370]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot 1.18.1  (client 1.16.5  )
 - node: v16.13.1

"dependencies": {
    "mineflayer": "^3.13.0",
    "mineflayer-armor-manager": "^1.4.2",
    "mineflayer-auto-auth": "^1.0.0",
    "mineflayer-auto-eat": "^2.3.3",
    "mineflayer-collectblock": "^1.3.4",
    "mineflayer-pathfinder": "^1.8.0",
    "mineflayer-pvp": "^1.0.2",
    "mineflayer-tool": "^1.1.0"
  }

## Your current code
https://pastebin.com/WW0k79qH

Log
https://pastebin.com/Xa54ZFAh
https://pastebin.com/Magy18q4

**Comment by Pix3lPirat3** [comment]
Move all the plug-in and event listeners into the createBot function that way when it does END those event listeners are registered on the new process

**Comment by AdminHcat** [comment]
> Move all the plug-in and event listeners into the createBot function that way when it does END those event listeners are registered on the new process

I try to put everything into the createbot function, but an error is still reported


(node:15356) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 diggingAborted listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:465:17)
    at EventEmitter.addListener (node:events:487:10)
    at resetPath (C:\Users\Hcat\Desktop\McFishBot\Bot\node_modules\_mineflayer-pathfinder@1.8.0@mineflayer-pathfinder\index.js:95:11)
    at EventEmitter.monitorMovement (C:\Users\Hcat\Desktop\McFishBot\Bot\node_modules\_mineflayer-pathfinder@1.8.0@mineflayer-pathfinder\index.js:334:7)
    at EventEmitter.emit (node:events:402:35)
    at Timeout.doPhysics [as _onTimeout] (C:\Users\Hcat\Desktop\McFishBot\Bot\node_modules\_mineflayer@3.13.1@mineflayer\lib\plugins\physics.js:66:13)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
(node:15356) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 diggingCompleted listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:465:17)
    at EventEmitter.addListener (node:events:487:10)
    at resetPath (C:\Users\Hcat\Desktop\McFishBot\Bot\node_modules\_mineflayer-pathfinder@1.8.0@mineflayer-pathfinder\index.js:96:11)
    at EventEmitter.monitorMovement (C:\Users\Hcat\Desktop\McFishBot\Bot\node_modules\_mineflayer-pathfinder@1.8.0@mineflayer-pathfinder\index.js:334:7)
    at EventEmitter.emit (node:events:402:35)
    at Timeout.doPhysics [as _onTimeout] (C:\Users\Hcat\Desktop\McFishBot\Bot\node_modules\_mineflayer@3.13.1@mineflayer\lib\plugins\physics.js:66:13)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

**Comment by AdminHcat** [comment]
I found that after running this function,  reported error after waiting 30 seconds

function guardArea (pos) {
  guardPos = pos.clone()

}

**Comment by AdminHcat** [comment]
There's no problem with single player games

**Comment by AdminHcat** [comment]
And  If this code is added, an error will be reported

bot.on('playerJoined', (player) => {
  bot.chat("["+player+"]" + " 加入了游戏")
})

Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:220:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:220:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by AdminHcat** [comment]
Playerjoin is invalid and sometimes conflicts with playerjleft

**Comment by rom1504** [comment]
not enough info
