### ISSUE TITLE
PartialReadError: Read error for undefined

### ISSUE THREAD

**Issue by o0F-0oF** [PrismarineJS/mineflayer#2398]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.14.1
 - server: git-Paper-129 (MC: 1.18.1) 
 - node: 17.3.0

## Detailed description of a problem
The bot joins the server, throws an error and then leaves the server

## What did you try yet?

Did you try any method from the API? no
Did you try any example? Any error from those?
I am using an example right now and it is still throwing the error

## Your current code
```py
import time
from javascript import require, On
mineflayer = require('mineflayer')
pathfinder = require('mineflayer-pathfinder')

RANGE_GOAL = 1
BOT_USERNAME = ''

bot = mineflayer.createBot({ 'host': '144.217.10.50', 'port': 25562, 'username': BOT_USERNAME, 'passowrd': '', 'hideErrors': False, 'version': 1.17, 'auth' : 'microsoft' })


bot.loadPlugin(pathfinder.pathfinder)
print("Started mineflayer")

@On(bot, 'spawn')
def handle(*args):
  print("I spawned 👋")
  mcData = require('minecraft-data')(bot.version)
  movements = pathfinder.Movements(bot, mcData)
  bot.pathfinder.setMovements(movements)
  #bot.pathfinder.setGoal(pathfinder.goals.GoalNear(pos.x, pos.y, pos.z, RANGE_GOAL))

@On(bot, "end")
def handle(*args):
  print("Bot ended!", args)
```

## Expected behavior
it joins the server and stays until I stop running the code

## Additional context
I am using py don't know if that has something to do with it

this is the error it is throwing
```
PartialReadError: Read error for undefined : undefined
    at new ExtendableError (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\utils.js:70:5)
    at Object.readVarInt [as varint] (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\datatypes\utils.js:69:45)
    at eval (eval at compile (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\compiler.js:258:12), <anonymous>:1465:36)
    at Object.packet_entity_destroy (eval at compile (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\compiler.js:258:12), <anonymous>:1470:9)
    at eval (eval at compile (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2109:68)
    at packet (eval at compile (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2158:9)
    at CompiledProtodef.read (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\compiler.js:70:12)
    at e.message (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\compiler.js:111:49)
    at tryCatch (C:\Users\aaaaaaaaaaaaaaaaaaaa\node_modules\protodef\src\utils.js:50:16)
```

**Comment by u9g** [comment]
the problem is with PrismarineJS/minecraft-data , would you mind opening the issue there with the same error?

**Comment by o0F-0oF** [comment]
thank you I will do that
