### ISSUE TITLE
I get this error when running "node main.js"

### ISSUE THREAD

**Issue by 2198djh19** [PrismarineJS/mineflayer#2455]
Error:

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\me\poop\node_modules\minecraft-protocol\src\datatypes\minecraft.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)

code:

const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
    host: process.argv[2],
    port: parseInt(process.argv[3]),
    username: process.argv[4],
    password: process.argv[5]
})

**Comment by IceTank** [comment]
The error is a syntax error as you are trying to run a .js file with invalid formating. The code you posted seams fine. Some off the following might have happened: 
1. You did not save your file and the actual file contains a syntax error
2. Some other code you did not post includes the error
3. You are running the wrong file
This is not an issue with mineflayer but a bug in your code. If you want faster replies to your issues and better help I suggest you join the PrismarineJS discord. It is linked at the top of the github page as a one of the banners that says `chat on discord`.
