### ISSUE TITLE
Error with bot.on and bot.once

### ISSUE THREAD

**Issue by 1ProCrafters** [PrismarineJS/mineflayer#2470]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.18.0
 - server: vanilla 1.17.1
 - node: 16.13.1

## Detailed description of a problem
I am expermenting with functions and it worked fine with this but as soon as I ran it again with bot.once it gave me a error

## What did you try yet?
I tried to search for this error but could not find anything:
Error:
TypeError: Cannot read properties of undefined (reading 'once')
    at Object.<anonymous> (C:\Users\idiot\Documents\GitHub\ProCraftersBots\main\ResourceBots\individual.js:684:7)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\idiot\Documents\GitHub\ProCraftersBots\main\ResourceBots\index.js:6:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)

Current code  
bot.once('spawn', onLogin)
bot.on('spawn', onSpawn)
bot.on('physicTick', onTick)
bot.on('chat', onChatMessage)

## Expected behavior
I have some function I want to trigger but it gives me a error about bot.once and bot.on

**Comment by rom1504** [comment]
The problem is not in the code you provided
Send more
