### ISSUE TITLE
Microsoft auth on Heroku doesn't work

### ISSUE THREAD

**Issue by Dani3l3-24** [PrismarineJS/mineflayer#2490]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.18.0
 - server: paper 1.12.2
 - node: 16.13.2

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
What are you building? What problem are you trying to solve?

I've made a bot, it uses microsoft authentication; when I run it on my pc it works fine, but when I run it on heroku, it throws and invalid credentials error.

## What did you try yet?

Checking if the email and password where correct on heroku

Did you try any method from the API?
Did you try any example? Any error from those?

Same error with the default example

## Expected behavior

It should work the same as if I would run it on my pc

**Comment by extremeheat** [comment]
What does the error say? Post the full error from when you run your program.

**Comment by Dani3l3-24** [comment]
Sign in failed, try removing the password field

2022-02-20T16:32:14.359947+00:00 app[web.1]: 

2022-02-20T16:32:14.368244+00:00 app[web.1]: /app/node_modules/@xboxreplay/errors/dist/index.js:25

2022-02-20T16:32:14.368249+00:00 app[web.1]:     unauthorized: (message = 'Unauthorized', reason = 'UNAUTHORIZED') => new XboxReplayError(message, {

2022-02-20T16:32:14.368249+00:00 app[web.1]:                                                                          ^

2022-02-20T16:32:14.368250+00:00 app[web.1]: 

2022-02-20T16:32:14.368250+00:00 app[web.1]: XboxReplayError: Invalid credentials.

2022-02-20T16:32:14.368251+00:00 app[web.1]:     at Object.unauthorized (/app/node_modules/@xboxreplay/errors/dist/index.js:25:74)

2022-02-20T16:32:14.368251+00:00 app[web.1]:     at /app/node_modules/@xboxreplay/xboxlive-auth/dist/core/live/index.js:71:32

2022-02-20T16:32:14.368252+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)

2022-02-20T16:32:14.368252+00:00 app[web.1]:     at async XboxTokenManager.doReplayAuth (/app/node_modules/prismarine-auth/src/TokenManagers/XboxTokenManager.js:132:31)

2022-02-20T16:32:14.368252+00:00 app[web.1]:     at async MicrosoftAuthFlow.getXboxToken (/app/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:116:20)

2022-02-20T16:32:14.368253+00:00 app[web.1]:     at async retry.xbl.forceRefresh (/app/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:157:22)

2022-02-20T16:32:14.368253+00:00 app[web.1]:     at async retry (/app/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:23:14)

2022-02-20T16:32:14.368254+00:00 app[web.1]:     at async MicrosoftAuthFlow.getMinecraftJavaToken (/app/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:156:7)

2022-02-20T16:32:14.368254+00:00 app[web.1]:     at async Object.authenticate (/app/node_modules/minecraft-protocol/src/client/microsoftAuth.js:17:44) {

2022-02-20T16:32:14.368255+00:00 app[web.1]:   __XboxReplay__: true,

2022-02-20T16:32:14.368255+00:00 app[web.1]:   details: { statusCode: 401, reason: 'UNAUTHORIZED' }

2022-02-20T16:32:14.368255+00:00 app[web.1]: }

**Comment by extremeheat** [comment]
Did you read the error?

**Comment by Dani3l3-24** [comment]
Yeah, 'invalid credentials'

**Comment by extremeheat** [comment]
Let’s try that again. Did you read the first line?

**Comment by Dani3l3-24** [comment]
ok
