### ISSUE TITLE
1.18.2 paper server throws Unsupported brand channel name when trying to join

### ISSUE THREAD

**Issue by IceTank** [PrismarineJS/mineflayer#2536]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: current master
 - server: paper 1.18.2
 - node: 16

## Detailed description of a problem
Trying to join a 1.18.2 server with mineflayer will cause it to disconnect with the following error ```text
D:\NodeJS\mineflayer\lib\plugins\game.js:22
    throw new Error('Unsupported brand channel name')
    ^

Error: Unsupported brand channel name
    at getBrandCustomChannelName (D:\NodeJS\mineflayer\lib\plugins\game.js:22:11)
    at inject (D:\NodeJS\mineflayer\lib\plugins\game.js:54:24)
    at D:\NodeJS\mineflayer\lib\plugin_loader.js:41:7
    at Array.forEach (<anonymous>)
    at injectPlugins (D:\NodeJS\mineflayer\lib\plugin_loader.js:40:16)
    at EventEmitter.onInjectAllowed (D:\NodeJS\mineflayer\lib\plugin_loader.js:12:5)
    at Object.onceWrapper (node:events:639:28)
    at EventEmitter.emit (node:events:520:28)
    at next (D:\NodeJS\mineflayer\lib\loader.js:124:9)
    at Object.createBot (D:\NodeJS\mineflayer\lib\loader.js:105:34)
```


## Your current code
```js
require('mineflayer').createBot()
```

## Expected behavior
No crash

**Comment by IceTank** [comment]
Nvm I was on the wrong mineflayer branch
