### ISSUE TITLE
Request blocked by CloudFlare

### ISSUE THREAD

**Issue by wubushanyan** [PrismarineJS/mineflayer#2556]
## Versions
 - mineflayer: 4.2.0
 - server: paper
 - node: 16.14.0

## Error Code
`root@VM-20-7-debian:~/node_modules# node bot2.js 
Error: Request blocked by CloudFlare
    at call (/root/node_modules/yggdrasil/src/utils.js:23:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async auth (/root/node_modules/yggdrasil/src/Client.js:18:12)
Error: Request blocked by CloudFlare
    at call (/root/node_modules/yggdrasil/src/utils.js:23:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async auth (/root/node_modules/yggdrasil/src/Client.js:18:12)
Error: Request blocked by CloudFlare
    at call (/root/node_modules/yggdrasil/src/utils.js:23:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async auth (/root/node_modules/yggdrasil/src/Client.js:18:12)
root@VM-20-7-debian:~/node_modules# ^C
`

##  code
```js

/*
const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
	host:'XXX',  
	//port:'25565',
	username:'XXX',
	password:'XXX',
	auth:'mojang'
}) 


bot.on('chat', (username, message) => {
  //if (username === bot.username) return
if (username === 'XXX' &&  message.search(/XXX/i)!== -1)
  {
	bot.chat(message.replace(/XXX: /i,"/") )
	console.log(message)
	}
})


function createBot () {
  const bot = mineflayer.createBot({
    host:'XXX',
	//port:'25565',
	username:'XXX',
	password:'XXX',
	auth:'mojang'
  })

  bot.on('error', (err) => console.log(err))
  bot.on('end', createBot)
}

createBot () 
*/


```

Why I run the js get this error,Can anyone help me？

 (ps:I didn't learn JS，just copy the examples  :）   )

**Comment by u9g** [comment]
You're logging in to quickly

**Comment by wubushanyan** [comment]
> You're logging in to quickly
can u tell me how to fix it .Sorry Im so stupid      :(

**Comment by u9g** [comment]
dont log in so many accounts in a short amount of time, or you have an ip blocked by cloudflare
