### ISSUE TITLE
weird behaviour of bot.writeBook

### ISSUE THREAD

**Issue by NxPe3ak** [PrismarineJS/mineflayer#2605]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 3.18.0
 - server: paper 1.18.2
 - node: 16.0.0

## Detailed description of a problem
When i try using bot.writeBook, i get this error:
TypeError: Serialization error for play.toServer : SizeOf error for undefined : Cannot read properties of undefined (reading 'length')
    at eval (eval at compile (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\protodef\src\compiler.js:258:12), <anonymous>:300:39)
    at Object.packet_edit_book (eval at compile (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\protodef\src\compiler.js:258:12), <anonymous>:305:9)
    at eval (eval at compile (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\protodef\src\compiler.js:258:12), <anonymous>:805:58)
    at packet (eval at compile (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\protodef\src\compiler.js:258:12), <anonymous>:852:9)
    at CompiledProtodef.sizeOf (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\protodef\src\compiler.js:89:14)
    at e.message (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\protodef\src\compiler.js:96:40)
    at tryCatch (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\protodef\src\utils.js:50:16)
    at CompiledProtodef.createPacketBuffer (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\protodef\src\compiler.js:96:20)
    at Serializer.createPacketBuffer (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\protodef\src\serializer.js:12:23)
    at Serializer._transform (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\protodef\src\serializer.js:18:18) {
  field: 'play.toServer'
}

## What did you try yet?

tried calling bot.writeBook again, for some reason it didn't cause the error again. instead, this error appeared

        if (!sourceItem) throw new Error(`Can't find ${mcDataEntry.name} in slots [${sourceStart} - ${sourceEnd}], (item id: ${itemType})`)
                               ^

Error: Can't find writable_book in slots [9 - 45], (item id: 942)
    at transferOne (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\mineflayer\lib\plugins\inventory.js:256:32)
    at clickDest (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\mineflayer\lib\plugins\inventory.js:298:17)
    at async transferOne (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\mineflayer\lib\plugins\inventory.js:261:7)
    at async clickDest (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\mineflayer\lib\plugins\inventory.js:298:11)
    at async transferOne (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\mineflayer\lib\plugins\inventory.js:261:7)
    at async transfer (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\mineflayer\lib\plugins\inventory.js:242:5)
    at async toss (C:\Users\Пользователь\Desktop\workspace\avitobot\node_modules\mineflayer\lib\plugins\simple_inventory.js:41:5)

## Your current code
```js
const txt = [
  'Объект №: SCP-682  Класс объекта: Кетер  Особые условия содержания: SCP-682 должен быть уничтожен в ближайшее возможное время. На данный момент у команд SCP нет средств, способных уничтожить',
  'SCP-682, имеется возможность только нанести ему массивные физические повреждения. SCP-682 должен содержаться в комнате размерами 5х5х5 м, покрытой изнутри армированными кислотоустойчивыми стальными плитами толщиной в 25,4 см. Комната должна быть',
  'наполнена соляной кислотой до полного погружения и обездвиживания SCP-682. Любые попытки SCP-682 двигаться, говорить или выйти из заключения должны быть пресечены.  Персоналу запрещается разговаривать с',
  'SCP-682, в целях предотвращения озлобления объекта. Сотрудники, не имеющие соответствующего разрешения и предпринимающие попытки коммуникации с SCP-682, будут отстранены силой.  Из-за частых попыток побега, сложности',
  'содержания и обезвреживания и высокой степени опасности для Фонда, SCP-682 должен содержаться в [УДАЛЕНО]. Фонд обязуется следить за тем, чтобы территория в радиусе 50 км была безлюдной.  Описание: SCP-682 -',
  'крупное рептилообразное существо неизвестного происхождения. По-видимому, оно чрезвычайно разумно, было замечено его сложное общение с SCP-079 во время их непродолжительного контакта. Похоже, что SCP-682 ненавидит всё живое,',
  'что было выражено в нескольких сеансах общения во время его содержания. (См. приложение 682-B).  У SCP-682 постоянно наблюдается чрезвычайно высокая сила, скорость и быстрые рефлексы, хотя их точные значения зависят от его состояния. Тело',
  'SCP-682 растет и меняется с большой скоростью, увеличиваясь или уменьшаясь в размере во время потребления объектом материи. SCP-682 получает энергию из всего, что он поглощает, как органического, так и неорганического. Пищеварение',
  'осуществляется при помощи нескольких фильтрующих жабр, находящихся внутри ноздрей SCP-682, способных поглотить полезные вещества из любого раствора, что позволяет ему постоянно восстанавливаться из кислоты, в которой он находится. Регенеративные',
  'способности SCP-682 и его сопротивляемость поразительны: SCP-682 способен двигаться и говорить при повреждениях, распространяющихся на 87% тела.  В случае побега SCP-682 все доступные Мобильные Оперативные Группы',
  'должны заняться его выслеживанием и поимкой, причем группы, состоящие менее чем из семи (7) человек, не допускаются к участию. На настоящий момент (██-██-████) количество попыток побега достигло семнадцати (17) , количество успешных',
  'попыток достигло шести (6). (См. приложение 682-D).  Приложение 682-B: Содержание части записи ██████.  <Начало записи, начиная с 00ч-21м-52с>  Д-р █████: Теперь скажи, почему ты',
  'убил тех фермеров?  SCP-682: (Нет ответа)  Д-р █████: Если ты сейчас не ответишь, мы лишим тебя такой возможности и поместим тебя обратно в…  SCP-682: (Неразборчиво)',
  ' Д-р █████: Пардон? (Хочет пододвинуть микрофон)  SCP-682: (Неразборчиво)  Д-р █████: Говори. (Обращаясь к D-085) Пододвинь микрофон ближе к нему.  SCP-682: …они были',
  '(Неразборчиво)…  Д-р █████: (Обращаясь к D-085) Этот микрофон на максимальной громкости, пододвинь его ближе!  Служащий D-085: Его пасть раздроблена, посмотрите! Он не может гово… (Крики и всхлипы)',
  ' SCP-682: (По-видимому, разрывает тело D-085) …они были… отвратительны…  Д-р █████: (Покидает помещение)  <Конец записи>  Приложение 682-D: Побеги SCP-682:',
  ' 1: Первое происшествие, ██-██-████: Остановлено агентом ██████████, агентом ████, агентом ████████ (мертв), служащим D-129 (мертв), служащим D-027 (мертв), служащим D-173 (мертв), служащим D-200 (мертв),',
  'служащим D-193 (мертв).  2: Второе происшествие, ██-██-████: Остановлено агентом ████, агентом ██████, доктором ████████, служащим D-124, служащим D-137 (мертв), служащим D-201 (мертв), служащим',
  'D-202 (мертв), служащим D-203 (мертв).  3: Третье происшествие, ██-██-████: Остановлено агентом ████████, мастер-серж. ██████, агентом ██████████, агентом ████████ (мертв), служащим D-018 (мертв),',
  'служащим D-211 (мертв), служащим D-216.  4: Четвертое происшествие, ██-██-████: Остановлено агентом ████████, штаб-серж. ██████████, техник-серж. ████████, солд. ████, солд. ████████, лейт.',
  '████████████, штаб-серж. ██████████ (мертв), полк. ██████████ (мертв), солд. ██████ (мертв), солд. ██████ (мертв), агентом ██████ (мертв).  5: Пятое происшествие, ██-██-████: Остановлено служащим',
  'D-221, агентом ████████ (мертв), агентом ██████████ (мертв), агентом ██████████ (мертв), служащим D-028 (мертв), служащим D-111 (мертв), служащим D-281 (мертв), служащим D-209 (мертв).  6: Шестое происшествие,',
  '██-██-████: Остановлено агентом ████████████, агентом ████, служащим D-291 (пропал без вести), агентом █████ (мертв), агентом ███████████ (мертв), служащим D-299 (мертв), служащим D-277 (мертв), служащим D-278 (мертв), служащим',
  'D-279 (мертв).  Приложение 682-E: Об уничтожении:  Протокол события 682-E18: д-р ████████ пытается использовать SCP-409 против SCP-682. Генерал ████, генерал ██████ и д-р ████████ наблюдают. ',
  '0400: Воздействие. SCP-682 начал разрываться в месте контакта, что вызвало большие повреждения в этом месте. SCP-682 спрашивал несколько раз, чем это было вызвано.  0800: Начинается кристаллизация, распространяется',
  'намного медленнее, чем обычно.  1200: SCP-682 проявляет признаки сильной боли, начинаются припадки.  1300: Кристаллизация останавливается на 62% преобразования тела. Кристаллизованные',
  'области взрываются, нанося массивные повреждения SCP-682  1400: SCP-682 восстанавливается после воздействия, несмотря на отсутствие конечностей и органов. SCP-682 начинает регенерацию и утверждает, что попытается убить и',
  'съесть всех, кто участвовал в событии 682-E18.  SCP-682 теперь имеет иммунитет к SCP-409. Использование других SCP для уничтожения SCP-682 должно сначала быть протестировано на образцах SCP-682 перед полномасштабным',
  'применением.  В соответствии с рекомендациями д-р ██████████ (см. документ 27b-6), д-р ██████ и д-р ██████ запросили разрешение на попытку уничтожения SCP-682 с помощью SCP-689. Запрос ожидает подтверждения ████████████.',
  ' Д-р Гирс высказал предположение, что можно использовать SCP-182 для общения с SCP-682. SCP-182 выразил нежелание участвовать, и отказался войти в место содержания SCP-682, если это возможно.'
]

const mineflayer = require('mineflayer');

const bot = mineflayer.createBot({
    host: 'mc.darkmine.ru',
    username: 'avito',
    port: 25565
})

bot.once('spawn', () => {
    bot.addChatPattern('pm', /^\[([^\s]+)\s\-\>\sme\]\s(.*)/, {parse: true})

    bot.on('chat:pm', ([[ username, msg ]]) => {
        const args = msg.split(' ')
        const cmd = args.shift()
        switch (cmd) {
            case 'writebook':
                // async context intended
                (async function () {
                    await sleep(50)
                    await bot.writeBook(36, txt)
                    await sleep(50)
                    bot.toss(942, null)
                })()
                break
            default:
                break
        }
    })
})
```

## Expected behavior
i expected the book to be written and dropped(the book is in 36th slot)

**Comment by MrAwesome** [comment]
I did a little tracking down - it looks like this is coming from this call:

https://github.com/PrismarineJS/mineflayer/blob/9497b67d85082317bf7bf7a19427ed9371cb2f49/lib/plugins/book.js#L19

Just a guess since I'm new to all this, but could this be from the format of the edit book packet changing? It looks like it's different between 1.17 and now:

https://github.com/PrismarineJS/minecraft-data/blob/c417c9c124c704dcf41821dff6b4341a738df8ad/data/pc/1.17/protocol.json#L4524

https://github.com/PrismarineJS/minecraft-data/blob/c417c9c124c704dcf41821dff6b4341a738df8ad/data/pc/1.18.2/protocol.json#L4659
