### ISSUE TITLE
1.8.9 chunk errors

### ISSUE THREAD

**Issue by Taxalo** [PrismarineJS/mineflayer#2614]
Hey, I was testing some things on the bot when I realised that whenever I put a wooden sign (on a wall or on the ground) it crashes.

This is the error it gives me:

```
node:internal/buffer:86
  throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 10239. Received 10583
    at new NodeError (node:internal/errors:371:5)
    at boundsError (node:internal/buffer:86:9)
    at Buffer.readUInt8 (node:internal/buffer:252:5)
    at readUInt4LE (C:\Users\deivi\WebstormProjects\sigmaBot\node_modules\uint4\index.js:23:23)
    at writeUInt4LE (C:\Users\deivi\WebstormProjects\sigmaBot\node_modules\uint4\index.js:34:28)
    at Section.setSkyLight (C:\Users\deivi\WebstormProjects\sigmaBot\node_modules\prismarine-chunk\src\pc\1.8\section.js:123:5)
    at Chunk.setSkyLight (C:\Users\deivi\WebstormProjects\sigmaBot\node_modules\prismarine-chunk\src\pc\1.8\chunk.js:145:33)
    at Chunk.setBlock (C:\Users\deivi\WebstormProjects\sigmaBot\node_modules\prismarine-chunk\src\pc\1.8\chunk.js:79:42)
    at Client.<anonymous> (C:\Users\deivi\WebstormProjects\sigmaBot\node_modules\mineflayer\lib\plugins\blocks.js:406:12)
    at Client.emit (node:events:394:28) {
  code: 'ERR_OUT_OF_RANGE'
}
```

The bot.version is 1.8.9, I have tried doing this with a bot without any listener or functions and it happens again.

It just crashes when there is a sign close or when you place a sign. Same error every time. Removing the sign makes the bot not crash when loading the chunk.

**Comment by rom1504** [comment]
What kind of server

**Comment by Taxalo** [comment]
It was a non vanilla server, factions servers. If IP is needed I will provide it.

**Comment by Kashalls** [comment]
> It was a non vanilla server, factions servers. If IP is needed I will provide it.

We're going to need more information like what software the remote server is running. Can you test this to see if it happens on vanilla or papermc servers? Is this just specifically wooden signs facing one direction?

**Comment by hard-shutdown** [comment]
bump

**Comment by frej4189** [comment]
Fixed with https://github.com/PrismarineJS/prismarine-chunk/pull/209

Can be closed
