### ISSUE TITLE
Not able to log in with micorsoft account

### ISSUE THREAD

**Issue by Jakonix** [PrismarineJS/mineflayer#2625]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.3.0
 - server: fabric 1.18.2
 - node: 14.19.2

## Detailed description of a problem
When i try to use my microsoft account for mineflayer bot
it dosn't eant to work.

## What did you try yet?

Tryed solution for a similiar issue.

## Your current code
  GNU nano 2.9.8                       index.js                                 

const { mineflayer: mineflayerViewer } = require('prismarine-viewer')
const mineflayer = require('mineflayer')
const bot = mineflayer.createBot({
username:*********@*****.com',
password:'**********',
auth:'microsoft',
host:'localhost',
port:25565
})

function Attack (){
const entity = bot.nearestEntity()
if(!entity)return
const pos = entity.position;
if(i==30){
bot.lookAt(pos)
bot.attack(entity,() => {
bot.chat('hit');
});

## Expected behavior
Bot logs into server with microsoft account

## Additional context
error messege

"Sign in failed, try removing the password field

(node:1234473) UnhandledPromiseRejectionWarning: XboxReplayError: Invalid credentials.
    at Object.unauthorized (/home/bot/node_modules/@xboxreplay/errors/dist/index.js:25:74)
    at /home/bot/node_modules/@xboxreplay/xboxlive-auth/dist/core/live/index.js:71:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async XboxTokenManager.doReplayAuth (/home/bot/node_modules/prismarine-auth/src/TokenManagers/XboxTokenManager.js:133:31)
    at async MicrosoftAuthFlow.getXboxToken (/home/bot/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:117:20)
    at async retry.xbl.forceRefresh (/home/bot/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:157:22)
    at async retry (/home/bot/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:24:14)
    at async MicrosoftAuthFlow.getMinecraftJavaToken (/home/bot/node_modules/prismarine-auth/src/MicrosoftAuthFlow.js:156:7)
    at async Object.authenticate (/home/bot/node_modules/minecraft-protocol/src/client/microsoftAuth.js:17:44)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1234473) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1234473) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
"

**Comment by LucienHH** [comment]
Have you tried removing the password field?

**Comment by Jakonix** [comment]
Ok thank you very much it worked.
