### ISSUE TITLE
bot.supportFeature is not a function

### ISSUE THREAD

**Issue by Fikow195** [PrismarineJS/mineflayer#2653]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: curent version
 - server: vanilla/spigot/paper vanilla 1.12.2
 - node: 16.15.1

## Detailed description of a problem
I can't run any code
with this error:
`c:\Users\Жека\node_modules\mineflayer\lib\plugins\book.js:10
  if (bot.supportFeature('editBookIsPluginChannel')) {
          ^

TypeError: bot.supportFeature is not a function
    at inject (c:\Users\Жека\node_modules\mineflayer\lib\plugins\book.js:10:11)
    at c:\Users\Жека\node_modules\mineflayer\lib\plugin_loader.js:41:7
    at Array.forEach (<anonymous>)
    at injectPlugins (c:\Users\Жека\node_modules\mineflayer\lib\plugin_loader.js:40:16)
    at EventEmitter.onInjectAllowed (c:\Users\Жека\node_modules\mineflayer\lib\plugin_loader.js:12:5)
    at Object.onceWrapper (node:events:641:28)
    at EventEmitter.emit (node:events:527:28)
    at next (c:\Users\Жека\node_modules\mineflayer\lib\loader.js:124:9)
    at Object.createBot (c:\Users\Жека\node_modules\mineflayer\lib\loader.js:104:34)
    at Object.<anonymous> (c:\Users\Жека\Desktop\pvpBot2\index.js:6:24)`
before this error everything was good

## What did you try yet?
reinstall mineflayer and node js

## Your current code
```js
any code
/*
Some code here, replace this
*/


```

## Expected behavior
working bot

## Additional context
before moment when error arrived i tried to run this bot: https://github.com/Catalyst-42/mineflyaer-digger-bot/blob/main/README_RU.md

**Comment by Fikow195** [comment]
I just deleted ALL node js and this helped me
