### ISSUE TITLE
chest.deposit() not working when using Python

### ISSUE THREAD

**Issue by timof123** [PrismarineJS/mineflayer#2657]
My code:
```
mineflayer = require('mineflayer')

bot = mineflayer.createBot({
    'host': '******',
    'port': 25565,
    'username': '******',
    'version': '1.12'
    })

@On(bot, 'login')
def handle(*args):
    items_inventory = bot.inventory.slots
    chest = bot.openContainer(bot.blockAt(vec3(2463,64,-525)))
    if chest:
        for item in items_inventory:
            if item != None:
                chest.deposit(item.type, None, item.count)

    chest.close()
```

This code should transfer all items from the inventory to the chest. But the script throws an error:
```
javascript.errors.JavaScriptError: ('deposit', "TypeError: Cannot read property 'type' of null\n    at clickDest (/usr/local/lib/node_modules/mineflayer/lib/plugins/inventory.js:263:51)\n    at transferOne (/usr/local/lib/node_modules/mineflayer/lib/plugins/inventory.js:260:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async transfer (/usr/local/lib/node_modules/mineflayer/lib/plugins/inventory.js:241:5)\n    at async Window.window.deposit (/usr/local/lib/node_modules/mineflayer/lib/plugins/inventory.js:338:7)\n    at async Bridge.call (/usr/local/lib/python3.8/site-packages/javascript/js/bridge.js:136:17)\n    at async Bridge.onMessage (/usr/local/lib/python3.8/site-packages/javascript/js/bridge.js:226:7)")

[JSE] (node:1614) UnhandledPromiseRejectionWarning
[JSE] (Use `node --trace-warnings ...` to show where the warning was created)
[JSE] (node:1614) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[JSE] (node:1614) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

What is the problem? I've tried enabling async/await but it doesn't help.

**Comment by Fikow195** [comment]
Sorry but i can help you. But everything in mineflayer working bad at python, i just tried to migrate into JavaScript and mineflayer programming become easier

**Comment by extremeheat** [comment]
Please update the javascript module and see if this still happens:

```js
pip uninstall javascript
pip install javascript
```
