### ISSUE TITLE
bots being disconnect with keepalive timeout

### ISSUE THREAD

**Issue by ham1255** [PrismarineJS/mineflayer#2673]
- [ x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.3.0
 - server: paper 1.18.2  and paper 1.19 (viaversion and viabackwards)
 - node: 14.16.0

## Detailed description of a problem
I have little knowledge in js but as i am not new to programming world, anyways while testing my spigot plugin, i decided to make group of
bots of 250 players using code i included below, but they will get disconnected from server with keepalive timeout,
but since library does not support 1.19 yet so installed viabackwards to allow the bots to logins so i thought its the issue so
i made brand new paper 1.18.2 server pretty much untouched let bot login to it same exact issue occures. 
```
[16:38:27 WARN]: -GBotFarmer258 was kicked due to keepalive timeout!
[16:38:27 INFO]: -GBotFarmer258 lost connection: Timed out
[16:38:27 INFO]: -GBotFarmer258 left the game
[16:38:27 WARN]: -GBotFarmer256 was kicked due to keepalive timeout!
[16:38:27 INFO]: -GBotFarmer256 lost connection: Timed out
[16:38:27 INFO]: -GBotFarmer256 left the game
[16:38:27 WARN]: -GBotFarmer259 was kicked due to keepalive timeout!
[16:38:27 INFO]: -GBotFarmer259 lost connection: Timed out
[16:38:27 INFO]: -GBotFarmer259 left the game
```
```
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at Framer.ondata (/home/mohammed/WebstormProjects/gbotminions/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at Framer.emit (events.js:315:20)
    at addChunk (/home/mohammed/WebstormProjects/gbotminions/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/mohammed/WebstormProjects/gbotminions/node_modules/readable-stream/lib/_stream_readable.js:280:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at Framer.ondata (/home/mohammed/WebstormProjects/gbotminions/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at Framer.emit (events.js:315:20)
    at addChunk (/home/mohammed/WebstormProjects/gbotminions/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/mohammed/WebstormProjects/gbotminions/node_modules/readable-stream/lib/_stream_readable.js:280:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at Framer.ondata (/home/mohammed/WebstormProjects/gbotminions/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at Framer.emit (events.js:315:20)
    at addChunk (/home/mohammed/WebstormProjects/gbotminions/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/mohammed/WebstormProjects/gbotminions/node_modules/readable-stream/lib/_stream_readable.js:280:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at Framer.ondata (/home/mohammed/WebstormProjects/gbotminions/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at Framer.emit (events.js:315:20)
    at addChunk (/home/mohammed/WebstormProjects/gbotminions/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/mohammed/WebstormProjects/gbotminions/node_modules/readable-stream/lib/_stream_readable.js:280:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}


```
but i discovered that lowering the number to between 16-1 will not disconnect.
## What did you try yet?
made sure server isn't lagging by killings mobs nearby

## Your current code
```js

const mineflayer = require('mineflayer')

const baseUserNAME = "-GBotFarmer";

class GBotMinion {
    constructor(username) {
        this.host = "localhost";
        this.username = username;
    }

    initBot() {
        this.bot = mineflayer.createBot({
            host: this.host,
            username: this.username
        });
        this.initAi();
    }
    initAi() {
    }
}

let bots = [];
for (let i = 0; i < 260; i++) {
    const botClass = new GBotMinion(baseUserNAME + i)
    botClass.initBot();
    bots.push(botClass);
}

```

## Expected behavior
being online without disconnection

## Additional context
it seems like when they join they have no knockback at all

**Comment by amoraschi** [comment]
260 bots is probably too much for your PC, so it doesn't have resources to actually send the keepAlive packet

**Comment by ham1255** [comment]
pretty much i9 9900k can do it

**Comment by IceTank** [comment]
This is because you are connecting all bots at the same time. The node.js event loop will fill up and prevent any scheduled task like keep alive from being processed. Use worker threads to host multiple bots and you won't run into this issue. Or if you only want bots to login you can use the much lighter node-minecraft-protocol.

**Comment by ham1255** [comment]
i guess it was that case then thanks.
