### ISSUE TITLE
1.18.2 issue i am having for some reason

### ISSUE THREAD

**Issue by ignasbbbb** [PrismarineJS/mineflayer#2689]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest of report
 - server: vanilla 1.18.2
 - node: 16.13.1

## Your current code
```js

/*
const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: '1.18.2 server', // minecraft server ip
  username: 'bot_boi', // minecraft username
  version: 1.18
})

bot.on('chat', (username, message) => {
  if (username === bot.username) return
  bot.chat(message)
})

// Log errors and kick reasons:
bot.on('kicked', console.log)
bot.on('error', console.log)
*/


```

## Expected behavior
Expected the bot to join the server and repeat chat

## Additional context
i get this without specifing version (auto)
TypeError: Cannot read properties of undefined (reading 'minecraftVersion')
    at c:\Users\User\node_modules\minecraft-protocol\src\client\autoVersion.js:34:42
    at c:\Users\User\node_modules\minecraft-protocol\src\ping.js:13:7
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {stack: 'TypeError: Cannot read properties of undefine…ions (node:internal/process/task_queues:96:5)', message: 'Cannot read properties of undefined (reading 'minecraftVersion')'}

**Comment by ignasbbbb** [comment]
new error when trying with " "

TypeError: Cannot read properties of null (reading 'biomes')
    at loader (c:\Users\User\node_modules\prismarine-biome\index.js:6:48)
    at loader (c:\Users\User\node_modules\prismarine-block\index.js:34:65)
    at inject (c:\Users\User\node_modules\mineflayer\lib\plugins\blocks.js:24:44)
    at c:\Users\User\node_modules\mineflayer\lib\plugin_loader.js:41:7
    at Array.forEach (<anonymous>)
    at injectPlugins (c:\Users\User\node_modules\mineflayer\lib\plugin_loader.js:40:16)
    at EventEmitter.onInjectAllowed (c:\Users\User\node_modules\mineflayer\lib\plugin_loader.js:12:5)
    at Object.onceWrapper (node:events:509:28)
    at EventEmitter.emit (node:events:390:28)
    at Client.next (c:\Users\User\node_modules\mineflayer\lib\loader.js:124:9) {stack: 'TypeError: Cannot read properties of null (re…\node_modules\mineflayer\lib\loader.js:124:9)', message: 'Cannot read properties of null (reading 'biomes')'}

**Comment by ignasbbbb** [comment]
a

**Comment by ignasbbbb** [comment]
new error when trying with " "

TypeError: Cannot read properties of null (reading 'biomes')
    at loader (c:\Users\User\node_modules\prismarine-biome\index.js:6:48)
    at loader (c:\Users\User\node_modules\prismarine-block\index.js:34:65)
    at inject (c:\Users\User\node_modules\mineflayer\lib\plugins\blocks.js:24:44)
    at c:\Users\User\node_modules\mineflayer\lib\plugin_loader.js:41:7
    at Array.forEach (<anonymous>)
    at injectPlugins (c:\Users\User\node_modules\mineflayer\lib\plugin_loader.js:40:16)
    at EventEmitter.onInjectAllowed (c:\Users\User\node_modules\mineflayer\lib\plugin_loader.js:12:5)
    at Object.onceWrapper (node:events:509:28)
    at EventEmitter.emit (node:events:390:28)
    at Client.next (c:\Users\User\node_modules\mineflayer\lib\loader.js:124:9) {stack: 'TypeError: Cannot read properties of null (re…\node_modules\mineflayer\lib\loader.js:124:9)', message: 'Cannot read properties of null (reading 'biomes')'}

**Comment by amoraschi** [comment]
Put the version in between `""` like this:
`version: "1.18"`

**Comment by ignasbbbb** [comment]
that didnt work
![image](https://user-images.githubusercontent.com/101268797/178159932-8b76053b-42ff-42bb-a1e9-7921c23b267b.png)

**Comment by ignasbbbb** [comment]
that didnt work
![image](https://user-images.githubusercontent.com/101268797/178159975-14bf3352-3554-4810-be1d-fef8f026a4ae.png)

**Comment by amoraschi** [comment]
Well at least now it tells you what's actually wrong

**Comment by ignasbbbb** [comment]
fixed by completely reinstalling node and packages
