### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'height')

### ISSUE THREAD

**Issue by ufgf** [PrismarineJS/mineflayer#2730]
- [X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.3.0
 - server: 1.12.2, `mc.reallyworld.ru`, type: **"null"** [(see this screenshot)](https://i.imgur.com/Ljjc75W.png), — the problem occurs in the lobby when "checking" the player (for the presence of some cheats?)
 - node: 17.1.0

## Detailed description of a problem
When passing the server "checking", [clientbound parameters](https://github.com/PrismarineJS/mineflayer/blob/3b9243bd2934f32fcac371e646f7064bd7c51cd6/lib/plugins/physics.js#L259) are set too early(?), what causes an unhandled exception:

```
C:\Users\ufgf\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot set properties of undefined (setting 'height')
    at Client.<anonymous> (C:\Users\ufgf\node_modules\mineflayer\lib\plugins\physics.js:260:23)
    at Client.emit (node:events:390:28)
    at FullPacketParser.<anonymous> (C:\Users\ufgf\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (node:events:390:28)
    at addChunk (C:\Users\ufgf\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\ufgf\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (C:\Users\ufgf\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:241:10)    at FullPacketParser.Transform.push (C:\Users\ufgf\node_modules\protodef\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at FullPacketParser._transform (C:\Users\ufgf\node_modules\protodef\src\serializer.js:89:10)
    at FullPacketParser.Transform._read (C:\Users\ufgf\node_modules\protodef\node_modules\readable-stream\lib\_stream_transform.js:177:10)

Node.js v17.1.0
```

## What did you try yet?
Connect to other servers, and make sure that the problem repeats itself when connecting only to this one

## Your current code
```js
const mineflayer = require("mineflayer");

const options = {
  host: "mc.reallyworld.ru",
  port: "25565",
  username: "some_nick",
  version: "1.12.2",
  checkTimeoutInterval: 60000,
};

var bot = mineflayer.createBot(options);
bot.setMaxListeners(0);
themain();

function themain() {
  bot.on("spawn", () => {
    bot.waitForTicks(60);
    console.log("bot.game.levelType: " + bot.game.levelType);
    bot.end();
  });

  bot.on("kicked", (reason) => {
    console.log("bot was kicked: " + reason);
    bot.end();
  });
}
```

## Expected behavior
The bot at least executes `console.log()` in `bot.on("spawn" ... )` or `bot.on("kicked" ... )`

**Comment by amoraschi** [comment]
Have you tried removing `checkTimeoutInterval` and `bot.setMaxListeners(0)`?

**Comment by ufgf** [comment]
> Have you tried removing `checkTimeoutInterval` and `bot.setMaxListeners(0)`?

Does not affect the reproducibility of the problem (see video)

https://user-images.githubusercontent.com/29230208/185623435-4a2f474b-1803-40be-a5ce-e8d3fd6f7a4b.mp4

**Comment by extremeheat** [comment]
Reopen if it's still an issue after `npm update --depth 9999`
