### ISSUE TITLE
Fix physics in water in 1.19

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#2796]
somehow the mc server is rejecting moves in water.

**Comment by Kashalls** [comment]
![Gif](https://owo.whats-th.is/5PiuZpr.gif)
![Gif](https://owo.whats-th.is/3XjsAKR.gif)

At first, I thought this was a pathfinder issue, but it looks to be just mineflayer.

To reproduce:
```js
const mineflayer = require('mineflayer');
const bot = mineflayer.createBot({
    host: '127.0.0.1',
    port: 25565,
    username: 'Firebender'
})
bot.once('spawn', () => {
    console.log('ready!')
})
```
1. Run index.js
2. Place water on bot standing location.
3. Server kicks for `<player> lost connection: Invalid move player packet received`

**Comment by Devvilas** [comment]
I'm having this bug too...

It gives this error...

```
Error: write ECONNABORTED
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at Framer.ondata (C:\Users\SIMÃO VILAS\Desktop\MineBot\node_modules\readable-stream\lib\internal\streams\readable.js:699:22)
    at Framer.emit (events.js:376:20)
    at addChunk (C:\Users\SIMÃO VILAS\Desktop\MineBot\node_modules\readable-stream\lib\internal\streams\readable.js:291:12)
    at readableAddChunk (C:\Users\SIMÃO VILAS\Desktop\MineBot\node_modules\readable-stream\lib\internal\streams\readable.js:267:9) {
  errno: -4079,
  code: 'ECONNABORTED',
  syscall: 'write'
}
Error: write ECONNABORTED
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at Framer.ondata (C:\Users\SIMÃO VILAS\Desktop\MineBot\node_modules\readable-stream\lib\internal\streams\readable.js:699:22)
    at Framer.emit (events.js:376:20)
    at addChunk (C:\Users\SIMÃO VILAS\Desktop\MineBot\node_modules\readable-stream\lib\internal\streams\readable.js:291:12)
    at readableAddChunk (C:\Users\SIMÃO VILAS\Desktop\MineBot\node_modules\readable-stream\lib\internal\streams\readable.js:267:9) {
  errno: -4079,
  code: 'ECONNABORTED',
  syscall: 'write'
}
```

**Comment by real-kwellercat** [comment]
same issue here.
