### ISSUE TITLE
"Error: Unsupported brand channel name" when trying to join localhost

### ISSUE THREAD

**Issue by Nachtschatten** [PrismarineJS/mineflayer#2802]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.5.0
 - server: vanilla 1.19.2
 - node: v18.10.0

## Detailed description of a problem
Just trying to connect at this point.
Steps to reproduce:
* Start a singleplayer world in Minecraft 1.19.2
* Open it to LAN
* Follow the ["lookAt_Bot"-Tutorial](https://www.youtube.com/watch?v=ltWosy4Z0Kw) until about 3:58, entering the correct port that Minecraft gave you
* Result: Bot does not connect, error message output 'Error: Unsupported brand channel name":
```
Error: Unsupported brand channel name
    at getBrandCustomChannelName (C:\Users\path\to\lookAt_Bot\node_modules\mineflayer\lib\plugins\game.js:22:11)
    at inject (C:\Users\path\to\lookAt_Bot\node_modules\mineflayer\lib\plugins\game.js:67:24)
    at C:\Users\path\to\lookAt_Bot\node_modules\mineflayer\lib\plugin_loader.js:41:7
    at Array.forEach (<anonymous>)
    at injectPlugins (C:\Users\path\to\lookAt_Bot\node_modules\mineflayer\lib\plugin_loader.js:40:16)
    at EventEmitter.onInjectAllowed (C:\Users\path\to\lookAt_Bot\node_modules\mineflayer\lib\plugin_loader.js:12:5)
    at Object.onceWrapper (node:events:627:28)
    at EventEmitter.emit (node:events:513:28)
    at Client.next (C:\Users\path\to\lookAt_Bot\node_modules\mineflayer\lib\loader.js:124:9)
    at Object.onceWrapper (node:events:627:28)
```

## What did you try yet?
* Followed the tutorial with Minecraft 1.19.2 and Mineflayer 4.5.0 => Error
* Downgraded to Minecraft 1.18.2 and Mineflayer 4.4.0 => Works

## Your current code
```js
const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
    host: 'localhost',
    port: 62399,
    username: 'lookAt_Bot'
})
```

## Expected behavior
* The bot should connect
* Ideally, a more helpful error message. What "brand channel name" causes the issue? If the issue is that 1.19.2 isn't supported yet, couldn't the error message say so?

## Additional context
(none)

**Comment by rom1504** [comment]
It should definitely fail much earlier. That seems to be a bug in
Minecraft-protocol

**Comment by darwinikii** [comment]
> It should definitely fail much earlier. That seems to be a bug in

Can we fix it temporarily by editing?

**Comment by rom1504** [comment]
It can definitely be fixed not temporarily

**Comment by darwinikii** [comment]
I don't want to wait for the fix can I fix it myself?

**Comment by rom1504** [comment]
Yes

**Comment by darwinikii** [comment]
we don't get along man i don't know how can i fix it

**Comment by darwinikii** [comment]
You must have received this error while making the 1.19.2 version of mineflayer, so you know the solution to the error.

**Comment by rom1504** [comment]
Nobody made 1.19.2 for mineflayer yet.

The fix here is to fail with a clearer error.
You can fix it by adding more prints in node-minecraft-protocol to figure
out why it's not failing, then add the right exception to make it fail

Another option you can take is help bring support to 1.19.2 in
node-minecraft-protocol, see the issue about that there

**Comment by darwinikii** [comment]
I don't have enough js knowledge for this project, I have to wait

**Comment by Andrew-Eathan** [comment]
getting this aswell

**Comment by QimieGames** [comment]
My man went from "I cant wait for all these dumbasses to work cause they are slow" to "Shits too complicated for me so ill just wait I guess"
