### ISSUE TITLE
Bot crash

### ISSUE THREAD

**Issue by Klayn1** [PrismarineJS/mineflayer#2847]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.5.1
 - server: Mirai(paper) 1.19.2

## Detailed description of a problem
bot can't register and gives problem.

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code
```js
import sys, re
from javascript import require, On, Once, console
import random

mineflayer = require("mineflayer", "latest")
pathfinder = require('mineflayer-pathfinder')

name = ["12235edtty", "534tryhtr", "532t43t", "4235467654hjgf", "DSAddasd", "gfdgsfd", "r342rt", "YOU_DIE", "DIE", "STARIK", "SMERT", "1213213", "gfdsgw5ewygewr", "t34t"]
BOT_USERNAME = random.choice(name)

bot = mineflayer.createBot({
  'host': 'ххх.ххх.хх.ххх',
  'port': хххх,
  'username': BOT_USERNAME
})

@On(bot, 'spawn')
def handle(*args):
    print("I spawned 👋")
    bot.chat("/register 1230812308 1230812308")
    movements = pathfinder.Movements(bot)

/*
Error
*/
[klayn1@klayn1 gadminebot]$ python bot.py
I spawned 👋
TypeError: Serialization error for play.toServer : SizeOf error for undefined : Cannot read properties of undefined (reading 'length')
    at Object.previousMessages (eval at compile (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/compiler.js:258:12), <anonymous>:175:37)
    at Object.packet_chat_command (eval at compile (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/compiler.js:258:12), <anonymous>:559:37)
    at eval (eval at compile (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1221:64)
    at packet (eval at compile (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1270:9)
    at CompiledProtodef.sizeOf (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/compiler.js:89:14)
    at e.message (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/compiler.js:96:40)
    at tryCatch (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/utils.js:50:16)
    at CompiledProtodef.createPacketBuffer (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/compiler.js:96:20)
    at Serializer.createPacketBuffer (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/serializer.js:12:23)
    at Serializer._transform (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/serializer.js:18:18) {
  field: 'play.toServer'
}
I spawned 👋
TypeError: Serialization error for play.toServer : SizeOf error for undefined : Cannot read properties of undefined (reading 'length')
    at Object.previousMessages (eval at compile (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/compiler.js:258:12), <anonymous>:175:37)
    at Object.packet_chat_command (eval at compile (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/compiler.js:258:12), <anonymous>:559:37)
    at eval (eval at compile (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1221:64)
    at packet (eval at compile (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1270:9)
    at CompiledProtodef.sizeOf (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/compiler.js:89:14)
    at e.message (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/compiler.js:96:40)
    at tryCatch (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/utils.js:50:16)
    at CompiledProtodef.createPacketBuffer (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/compiler.js:96:20)
    at Serializer.createPacketBuffer (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/serializer.js:12:23)
    at Serializer._transform (/home/klayn1/.local/lib/python3.10/site-packages/javascript/js/node_modules/protodef/src/serializer.js:18:18) {
  field: 'play.toServer'
}
^CException ignored in atexit callback: <bound method EventLoop.on_exit of <javascript.events.EventLoop object at 0x7f41977175b0>>
Traceback (most recent call last):
  File "/home/klayn1/.local/lib/python3.10/site-packages/javascript/events.py", line 144, in on_exit

```

**Comment by extremeheat** [comment]
#2797

**Comment by Klayn1** [comment]
> #2797

1.19.2 is not supported, as I understand it?
