### ISSUE TITLE
Error parsing `packet_entity_metadata` packet on 1.19

### ISSUE THREAD

**Issue by ShreshthTiwari** [PrismarineJS/mineflayer#2850]
PartialReadError: Read error for undefined : undefined
    at new ExtendableError (/root/minIO/dis1/node_modules/protodef/src/utils.js:63:13)
    at new PartialReadError (/root/minIO/dis1/node_modules/protodef/src/utils.js:70:5)
    at Object.readVarInt [as varint] (/root/minIO/dis1/node_modules/protodef/src/datatypes/utils.js:69:45)
    at eval (eval at compile (/root/minIO/dis1/node_modules/protodef/src/compiler.js:258:12), <anonymous>:225:59)
    at Object.entityMetadata (eval at compile (/root/minIO/dis1/node_modules/protodef/src/compiler.js:258:12), <anonymous>:228:9)
    at Object.packet_entity_metadata (eval at compile (/root/minIO/dis1/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1762:73)
    at eval (eval at compile (/root/minIO/dis1/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2382:70)
    at packet (eval at compile (/root/minIO/dis1/node_modules/protodef/src/compiler.js:258:12), <anonymous>:2412:9)
    at CompiledProtodef.read (/root/minIO/dis1/node_modules/protodef/src/compiler.js:70:12)
    at e.message (/root/minIO/dis1/node_modules/protodef/src/compiler.js:111:49)

**Comment by amoraschi** [comment]
Fill out the issue template

**Comment by ShreshthTiwari** [comment]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.5.1
 - server: spigot 1.19
 - node: 19.0.1


After joining the server 20-25 times the bot starts throwing this weird error-
```
PartialReadError: Read error for undefined : undefined
at new ExtendableError (/root/minIO/dis1/node_modules/protodef/src/utils.js:63:13)
at new PartialReadError (/root/minIO/dis1/node_modules/protodef/src/utils.js:70:5)
at Object.readVarInt [as varint] (/root/minIO/dis1/node_modules/protodef/src/datatypes/utils.js:69:45)
at eval (eval at compile (/root/minIO/dis1/node_modules/protodef/src/compiler.js:258:12), :225:59)
at Object.entityMetadata (eval at compile (/root/minIO/dis1/node_modules/protodef/src/compiler.js:258:12), :228:9)
at Object.packet_entity_metadata (eval at compile (/root/minIO/dis1/node_modules/protodef/src/compiler.js:258:12), :1762:73)
at eval (eval at compile (/root/minIO/dis1/node_modules/protodef/src/compiler.js:258:12), :2382:70)
at packet (eval at compile (/root/minIO/dis1/node_modules/protodef/src/compiler.js:258:12), :2412:9)
at CompiledProtodef.read (/root/minIO/dis1/node_modules/protodef/src/compiler.js:70:12)
at e.message (/root/minIO/dis1/node_modules/protodef/src/compiler.js:111:49)
```
and it automatically fixes after 10-15 bot restarts.


Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code
```js

/*
const minecraftBot = mineflayer.createBot({
        host: `${IP}`,
        username: `${user}`,
        //password: '12345678'
        port: (port * 1), 
        // version: false
        // auth: 'mojang' 
      });

      minecraftBot.once("spawn", async () => {
        setTimeout(async () => {
          try{
           //run codes and leave after certain time so that i dont have to manually do it
            minecraftBot.quit();
          }catch{}
        }, waitTime * 1000);
      });
*/


```

## Expected behavior
It should join the server and run all the codes inside it like jump, move, etc
but its breaking at server connection bcz i tried removing all events and still the error occured

## Additional context
Add any other context about the problem here.

**Comment by random-logic** [comment]
I am having the same issue. Hope this can be resolved soon.

**Comment by frej4189** [comment]
This is most likely a [minecraft-data](https://github.com/PrismarineJS/minecraft-data/) issue

**Comment by extremeheat** [comment]
Should have been fixed by Frej in one of the minecraft-data PRs. Reopen if it's still an issue after running `npm update --depth 9999`.
