### ISSUE TITLE
Crash while joining server on 1.8.9

### ISSUE THREAD

**Issue by InaayatDaDev** [PrismarineJS/mineflayer#2859]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.5.1
 - server: spigot 1.8.9
 - node: 14.17.3

## Detailed description of a problem
Everytime I connect to the server I crash.
Im trying to log into the server

Error:
```
C:\Users\Inaayat\Desktop\InaaMinemen\node_modules\prismarine-chat\index.js:46
      if (typeof json.text === 'string' || typeof json.text === 'number') {
                      ^

TypeError: Cannot read property 'text' of null
    at ChatMessage.parse (C:\Users\Inaayat\Desktop\InaaMinemen\node_modules\prismarine-chat\index.js:46:23)
    at new ChatMessage (C:\Users\Inaayat\Desktop\InaaMinemen\node_modules\prismarine-chat\index.js:32:12)
    at Client.<anonymous> (C:\Users\Inaayat\Desktop\InaaMinemen\node_modules\mineflayer\lib\plugins\entities.js:483:32)
    at Client.emit (events.js:375:28)
    at FullPacketParser.<anonymous> (C:\Users\Inaayat\Desktop\InaaMinemen\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (events.js:375:28)
    at addChunk (C:\Users\Inaayat\Desktop\InaaMinemen\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\Inaayat\Desktop\InaaMinemen\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (C:\Users\Inaayat\Desktop\InaaMinemen\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (C:\Users\Inaayat\Desktop\InaaMinemen\node_modules\protodef\node_modules\readable-stream\lib\_stream_transform.js:139:32)
```

## What did you try yet?

Did you try any method from the API? 
yes
Did you try any example? Any error from those?
yes

## Your current code
```js

const mineflayer = require('mineflayer');
const delay = require('delay');
const mineflayer_gui = require(`mineflayer-gui`);

var settings = {
    username: "",
    host: "as.minemen.club",
    password: "",
    version: "1.8.9",
    auth: "microsoft"
}

function sleep(ms) {
    return new Promise((resolve) => {
        setTimeout(resolve, ms);
    });
}

const bot = mineflayer.createBot(settings);

//bot.loadPlugin(mineflayer_gui);

bot.once("spawn", async () => {
    console.log('Logged in to as.minemen.club');
    bot.chat('/joinqueue as-practice');
    await sleep(1000);
    console.log('Joined as-practice');
});

bot.on('chat', (username, message) => {
    if (username === bot.username) return
    console.log(username, message);
});

bot.on('error', (e) => { console.log('Encountered an error: ' + e) });


```

## Expected behavior
I want to login to the server and for the bot to type /joinqueue as-practice

## Additional context
nope also my English is poor sorry!

**Comment by Olfi01** [comment]
I'm getting this error whenever I'm trying to send or receive a chat message

**Comment by Olfi01** [comment]
(in my case I'm trying it on a 1.19.1 server)

**Comment by extremeheat** [comment]
> (in my case I'm trying it on a 1.19.1 server)

1.19.1 is not supported. Did you not see the pinned issue?

**Comment by Olfi01** [comment]
> > (in my case I'm trying it on a 1.19.1 server)
> 
> 1.19.1 is not supported. Did you not see the pinned issue?
I did not, and I thought it was because the npm package page explicitly says it is 1.19 compatible.

**Comment by frej4189** [comment]
> > > (in my case I'm trying it on a 1.19.1 server)
> > 
> > 
> > 1.19.1 is not supported. Did you not see the pinned issue?
> 
> I did not, and I thought it was because the npm package page explicitly says it is 1.19 compatible.

It does support 1.19, but not 1.19.1+. There are some major differences with chat signing in particular

**Comment by extremeheat** [comment]
Can OP or anyone confirm this is still an issue on 1.8.9 with this server?
