### ISSUE TITLE
Cannot get version?

### ISSUE THREAD

**Issue by Taitep** [PrismarineJS/mineflayer#2888]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.0.0
 - server: paper 1.19.2
 - node: v18.12.1

## Detailed description of a problem
When I try to run my code i get the following error:
TypeError: Cannot read properties of null (reading 'version')
    at next (.\node_modules\mineflayer\lib\loader.js:108:67)
    at Object.createBot (.\node_modules\mineflayer\lib\loader.js:105:34)
    at Object.<anonymous> (.\index.js:4:24)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

## Your current code
```
const mineflayer = require('mineflayer')
const { mineflayer: mineflayerViewer } = require('prismarine-viewer')

const bot = mineflayer.createBot({
    host: 'localhost',
    username: 'TBot',
    version: '1.19.2'
})

bot.on('login', () => {
    mineflayerViewer(bot, {port: 3007, firstPerson: false})
    window.open('http://localhost:3007')
})
```

## Expected behavior
The bot should just join the server running on localhost and do nothing

## Additional context
OS: Win10

`.` is for censoring project path.

**Comment by amoraschi** [comment]
1.19.2 is not supported yet.

**Comment by Taitep** [comment]
What is latest supporten version?

**Comment by GarraBlanca2003** [comment]
1.19
