### ISSUE TITLE
Can't understand how to use proxy in Python

### ISSUE THREAD

**Issue by Justuser3310** [PrismarineJS/mineflayer#2903]
## Versions
 - mineflayer: latest
 - server: spigot 1.12.2
 - node: v16.19.0

## Detailed description of a problem
I can't understand how to connect to some server in offline mode using socks5/4

## Your current code
```python

from javascript import require

global mf, socks
mf = require('mineflayer')
socks = require('socks').SocksClient

def genbot():
	global mf
	username = 'Bot'

	proxyh = "127.0.0.1"
	proxyp = 1234

	host = "some.server"
	port = 25565


	client = socks.createConnection({
	'proxy': {
		'host': proxyh,
		'port': proxyp,
		'type': 5 },
	'command': 'connect',
	'destination': {
		'host': host,
		'port': port
}
})

	bot = mf.createBot({
	'client': client
})
	pass


genbot()


```

## Error
```bash
☕  JavaScript Error  Call to 'createBot' failed:
> genbot()
  at <module> (/home/void/Desktop/mineflayer/main.py:41)
> bot = mf.createBot({
  at genbot (/home/void/Desktop/mineflayer/main.py:35)
> 

... across the bridge ...

  at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
  at Socket.Readable.push (node:internal/streams/readable:228:10)
  at readableAddChunk (node:internal/streams/readable:289:9)
  at addChunk (node:internal/streams/readable:315:12)
  at Socket.emit (node:events:513:28)
  at Socket.<anonymous> (/home/void/.local/lib/python3.11/site-packages/javascript/js/bridge.js:275:14)
  at Bridge.onMessage (/home/void/.local/lib/python3.11/site-packages/javascript/js/bridge.js:226:25)
  at Bridge.call (/home/void/.local/lib/python3.11/site-packages/javascript/js/bridge.js:136:42)
  at Object.createBot (/home/void/.local/lib/python3.11/site-packages/javascript/js/node_modules/mineflayer/lib/loader.js:97:15)
> bot._client.on('connect', () => {
🌉 TypeError: bot._client.on is not a function
[void@linux mineflayer]$ node --version
v16.19.0
```

## Expected behavior
Connect bot with proxy to server in offline mode.

**Comment by extremeheat** [comment]
socks.createConnection's second parameter is a callback function with `err, response` parameters. With the response you need to do       client.setSocket(info.socket) and client.emit('connect') ... 

for example...
```py
bot = None
def connect_cb(client):
  def socks_cb(err, info):
    client.setSocket(info.socket)
    client.emit('connect')

  socks.createConnection({
    'proxy': {
      'host': proxyh,
      'port': proxyp,
      'type': 5 
    },
    'command': 'connect',
    'destination': {
      'host': host,
      'port': port
    }
  }, socks_cb)

bot = mf.createBot({ 'connect': connect_cb })
```

**Comment by Justuser3310** [comment]
```bash
[JSE] node:internal/process/promises:279
[JSE]             triggerUncaughtException(err, true /* fromPromise */);
[JSE]             ^
[JSE] [🐍  Python Error  JavaScript attempt to call 'some function' in Python failed:
[JSE] > callback(null, info);
[JSE]   at SocksClient.<anonymous> (/home/void/.local/lib/python3.11/site-packages/javascript/js/node_modules/socks/build/client/socksclient.js:60:21)
[JSE]   at Object.onceWrapper (node:events:628:26)
[JSE]   at SocksClient.emit (node:events:525:35)
[JSE]   at SocksClient.handleSocks5FinalHandshakeResponse (/home/void/.local/lib/python3.11/site-packages/javascript/js/node_modules/socks/build/client/socksclient.js:698:22)
[JSE]   at SocksClient.processData (/home/void/.local/lib/python3.11/site-packages/javascript/js/node_modules/socks/build/client/socksclient.js:334:22)
[JSE]   at SocksClient.onDataReceivedHandler (/home/void/.local/lib/python3.11/site-packages/javascript/js/node_modules/socks/build/client/socksclient.js:307:14)
[JSE]   at Socket.onDataReceived (/home/void/.local/lib/python3.11/site-packages/javascript/js/node_modules/socks/build/client/socksclient.js:223:46)
[JSE]   at Socket.emit (node:events:513:28)
[JSE] ... across the bridge ...
[JSE] > client.setSocket(info.socket)
[JSE]   at socks_cb (/home/void/Desktop/mineflayer/main.py:23)
[JSE] 🌉 AttributeError: 'dict' object has no attribute 'socket']
```

**Comment by extremeheat** [comment]
Turns out you don't need a callback, 
```py
  info = socks.createConnection({
    'proxy': {
      'host': proxyh,
      'port': proxyp,
      'type': 5 
    },
    'command': 'connect',
    'destination': {
      'host': host,
      'port': port
    }
  })
  client.setSocket(info.socket)
  client.emit('connect')
```

**Comment by Justuser3310** [comment]
[>>Code<<](https://hastebin.com/ekogapomiz.py)

Always error:
```bash
Traceback (most recent call last):
  File "/home/void/Desktop/mineflayer/main.py", line 41, in <module>
    info = socks.createConnection({
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/.local/lib/python3.11/site-packages/javascript/proxy.py", line 213, in __call__
    else self._exe.callProp(
         ^^^^^^^^^^^^^^^^^^^
  File "/home/void/.local/lib/python3.11/site-packages/javascript/proxy.py", line 153, in callProp
    resp = self.pcall(ffid, "call", method, args, timeout=timeout, forceRefs=forceRefs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/.local/lib/python3.11/site-packages/javascript/proxy.py", line 132, in pcall
    raise Exception(
Exception: Call to 'createConnection' timed out. Increase the timeout by setting the `timeout` keyword argument.
```
