### ISSUE TITLE
 Cannot find module

### ISSUE THREAD

**Issue by XingYuan55** [PrismarineJS/mineflayer#2920]
When I try to import it using Js, it reports an error that the module is not found. Using python also the module is not found. I reinstalled Node and reinstalled mineflayer also can't find the module. To this day I can't use it.

```node
node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module 'mineflayer'
Require stack:
- d:\py_proj\test\b.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (d:\py_proj\test\b.js:1:21)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {     
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'd:\\py_proj\\test\\b.js' ]
}

```

The full error message inside python:
```python
☕  JavaScript Error  Call to 'require' failed:
> mineflayer = require('mineflayer')
  at <module> (d:\py_proj\test\d.py:2)
>

... across the bridge ...

  at Module.require (node:internal/modules/cjs/loader:1105:19)
  at Module._load (node:internal/modules/cjs/loader:922:12)
  at Module.load (node:internal/modules/cjs/loader:1081:32)
  at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
  at Module._compile (node:internal/modules/cjs/loader:1218:14)
  at Object.<anonymous> (C:\Users\lenovo\AppData\Roaming\Python\Python38\site-packages\javascript\js\node_modules\minecraft-data\lib\supportsFeature.js:2:7)
> pc: require('../minecraft-data/data/pc/common/features.json'),
🌉 Error: Cannot find module '../minecraft-data/data/pc/common/features.json'
```

Can anyone help me? I would be grateful!!!!！！！！

（尽量使用中文回答）

**Comment by extremeheat** [comment]
Seems strange per the 
> Error: Cannot find module '../minecraft-data/data/pc/common/features.json'

line. Do you have `git` and the latest version of npm installed on your computer?

**Comment by XingYuan55** [comment]
The problem has been solved, thanks.
The problem was: I did not install mineflayer in the correct project directory.
Solution: Use cd to switch to the project directory you want to use and install it again, and it works.

**Comment by XingYuan55** [comment]
The problem has been solved, thanks.
The problem was: I did not install mineflayer in the correct project directory.
Solution: Use cd to switch to the project directory you want to use and install it again, and it works.
