### ISSUE TITLE
When teleported I get an error

### ISSUE THREAD

**Issue by GabrielMar** [PrismarineJS/mineflayer#3002]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.8.1
 - server: vanilla/spigot/paper 1.8.9
 - node: 16.17.0

## Detailed description of a problem
I was teleported to another map and got this error

## Error
```js
PATH\bot\node_modules\prismarine-chunk\src\pc\1.8\chunk.js:215
      if (data.length !== expectedSize) { throw (new Error(`Data buffer not correct size (was ${data.length}, expected ${expectedSize})`)) }
                                                 ^

Error: Data buffer not correct size (was 24832, expected 20736)
    at Chunk.load (PATH\bot\node_modules\prismarine-chunk\src\pc\1.8\chunk.js:215:50)
    at addColumn (PATH\bot\node_modules\mineflayer\lib\plugins\blocks.js:57:14)
    at Client.<anonymous> (PATH\bot\node_modules\mineflayer\lib\plugins\blocks.js:272:5)
    at Client.emit (node:events:513:28)
    at Client.emit (node:domain:489:12)
    at FullPacketParser.<anonymous> (PATH\bot\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (node:events:513:28)
    at FullPacketParser.emit (node:domain:489:12)
    at addChunk (PATH\bot\node_modules\readable-stream\lib\_stream_readable.js:279:12)
    at readableAddChunk (PATH\bot\node_modules\readable-stream\lib\_stream_readable.js:262:11)
err PATH\bot\node_modules\prismarine-chunk\src\pc\1.8\chunk.js:215
      if (data.length !== expectedSize) { throw (new Error(`Data buffer not correct size (was ${data.length}, expected ${expectedSize})`)) }
                                                 ^

Error: Data buffer not correct size (was 24832, expected 20736)
    at Chunk.load (PATH\bot\node_modules\prismarine-chunk\src\pc\1.8\chunk.js:215:50)
    at addColumn (PATH\bot\node_modules\mineflayer\lib\plugins\blocks.js:57:14)
    at Client.<anonymous> (PATH\bot\node_modules\mineflayer\lib\plugins\blocks.js:272:5)
    at Client.emit (node:events:513:28)
    at Client.emit (node:domain:489:12)
    at FullPacketParser.<anonymous> (PATH\bot\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (node:events:513:28)
    at FullPacketParser.emit (node:domain:489:12)
    at addChunk (PATH\bot\node_modules\readable-stream\lib\_stream_readable.js:279:12)
    at readableAddChunk (PATH\bot\node_modules\readable-stream\lib\_stream_readable.js:262:11)
```

**Comment by Maks-gaming** [comment]
same
