### ISSUE TITLE
Error when receiving and parsing chat

### ISSUE THREAD

**Issue by Darker** [PrismarineJS/mineflayer#301]
There's some sort of unhandled exception with this stacktrace:

```
TypeError: Cannot read property 'forEach' of undefined
    at ChatMessage.toString (C:\Users\Jakub\node_modules\mineflayer\lib\chat_message.js:181:14)
    at C:\Users\Jakub\node_modules\mineflayer\lib\chat_message.js:187:24
    at Array.forEach (native)
    at ChatMessage.toString (C:\Users\Jakub\node_modules\mineflayer\lib\chat_message.js:186:16)
    at C:\Users\Jakub\node_modules\mineflayer\lib\chat_message.js:182:24
    at Array.forEach (native)
    at ChatMessage.toString (C:\Users\Jakub\node_modules\mineflayer\lib\chat_message.js:181:15)
    at ChatMessage.getText (C:\Users\Jakub\node_modules\mineflayer\lib\chat_message.js:160:43)
    at Bot.<anonymous> (C:\Users\Jakub\node_modules\mineflayer\examples\digger.js:17:22)
    at Bot.emit (events.js:107:17)
```

It must me noted that this happens on very slow connection. I'll add more details when I have better connection. It should be handled anyway though.

**Comment by rom1504** [comment]
What kind of server are you connecting to ? Can you try to console.log the json of the message to know what goes wrong ?

**Comment by Darker** [comment]
Well I didn't manage to figure out what message was causing it. I was connecting to a Spigot server. The error was fixed by adding null check as follows:

      if(this.with!=null) {
        this.with.forEach(function(entry) {
          message += entry.toString() + " ";
        }); 
      }

on line 181 in chat_message.js. However fixing the problem didn't reveal the real cause - I don't even know what `this.with` is supposed to mean in that context.

The server I was connecting was a Spigot server. I didn't happen to see the same issue when connecting to localhost - but the remote server had a lot of chat plugins that can mess things up.

**Comment by rom1504** [comment]
related with #175 : chat support for all servers is not very easy

**Comment by rom1504** [comment]
Done
