### ISSUE TITLE
Simple mineflayer bot gives error when a player does damage

### ISSUE THREAD

**Issue by Whitelisted1** [PrismarineJS/mineflayer#3077]
- [X] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.9.0
 - server: vanilla 1.19.4
 - node: v16.16.0

## Detailed description of a problem
When a simply try to use a barebones mineflayer bot, on version 1.19.4, it gives an error whenever a player does damage

## What did you try yet?

Did you try any example? Any error from those?
Yes, I tried the autoeat example and it gave the same error

## Your current code
```js
// Simple player follow program

const mineflayer = require("mineflayer");
const { pathfinder, Movements, goals: { GoalNear, GoalFollow } } = require('mineflayer-pathfinder');

const targetPlayerUsername = "Whitelisted0_"
const settings = {
    username: "bob",
    host: "localhost",
    port: 25565,
    version: "1.19.4"
};

const bot = mineflayer.createBot(settings);
bot.loadPlugin(pathfinder);

bot.once("spawn", () => {
    bot.pathfinder.setGoal(new GoalFollow(bot.players[targetPlayerUsername].entity, 1), true);
});
```

## Expected behavior
No error when a player does damage

## Additional context
This seems to only happen when a player does damage. When I attack an entity, the bot logs the error, but when it attacks me it does not give an error.

The error is as follows:
```
PartialReadError: Read error for undefined : undefined
    at new ExtendableError (~\\node_modules\\protodef\\src\\utils.js:63:13)
    at new PartialReadError (~\\node_modules\\protodef\\src\\utils.js:70:5)
    at Object.readBool [as bool] (~\\node_modules\\protodef\\src\\datatypes\\utils.js:133:41)
    at eval (eval at compile (~\\node_modules\\protodef\\src\\compiler.js:258:12), <anonymous>:2939:29)
    at Object.packet_damage_event (eval at compile (~\\node_modules\\protodef\\src\\compiler.js:258:12), <anonymous>:2945:9)
    at eval (eval at compile (~\\node_modules\\protodef\\src\\compiler.js:258:12), <anonymous>:2984:64)
    at packet (eval at compile (~\\node_modules\\protodef\\src\\compiler.js:258:12), <anonymous>:3073:9)
    at CompiledProtodef.read (~\\node_modules\\protodef\\src\\compiler.js:70:12)
    at e.message (~\\node_modules\\protodef\\src\\compiler.js:111:49)
    at tryCatch (~\\node_modules\\protodef\\src\\utils.js:50:16)

(Note that '~' represents the pwd)
```

**Comment by IceTank** [comment]
Looks like an error protocol error in the damage event packet. Are you sure you are using the latest version? And latest dependencies? You can update with `npm update`. Are you sure the server is also 1.19.4?

**Comment by Whitelisted1** [comment]
Thanks for the advice, after running `npm update` again it seems to work fine, likely just an issue with the nodejs package not updating or something similar. Thanks for your time
