### ISSUE TITLE
Bot randomly crashes

### ISSUE THREAD

**Issue by smirnovv2007** [PrismarineJS/mineflayer#3145]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest
 - server: vanilla 1.20.1
 - node: 16

## Detailed description of a problem
Bot randomly crashes with error:
```
Error: client timed out after 30000 milliseconds
    at Timeout._onTimeout (C:\snapshot\clibot\node_modules\minecraft-protocol\src\client\keepalive.js:18:28)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Error: client timed out after 30000 milliseconds
    at Timeout._onTimeout (C:\snapshot\clibot\node_modules\minecraft-protocol\src\client\keepalive.js:18:28)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

## Your current code
```js

if (process.argv.length < 4 || process.argv.length > 6) {
  console.log('Usage : node index.js <login> <password> [<server_host>] [<server_port>]')
  process.exit(1)
}

const mineflayer = require('mineflayer')
const readline = require('node:readline')

function createBot () {
	const options = {
	  host: process.argv[4] || 'server.local',
	  username: process.argv[2],
	  auth: 'microsoft',
	  port: parseInt(process.argv[5]) || 25565,
	  password: process.argv[3]
	}

	const bot = mineflayer.createBot(options)

	const rl = readline.createInterface({
	  input: process.stdin,
	  output: process.stdout
	})

	bot.once('spawn', () => {
	  console.log(`Bot joined the game with username ${bot.username}.`)
	  rl.setPrompt('> '); rl.prompt()
	})

	bot.on('message', (message) => {
	  readline.moveCursor(process.stdout, -2, 0)
	  console.log(message.toAnsi())
	  rl.prompt()
	})

	rl.on('line', (line) => {
	  readline.moveCursor(process.stdout, 0, -1)
	  readline.clearScreenDown(process.stdout)
	  bot.chat(line.toString())
	})

	bot.on('error', (err) => console.log(err))
	bot.on('end', createBot)
}

createBot()

```

**Comment by extremeheat** [comment]
That's not a crash. You are being disconnected because the server stopped responding to the bot (could be offline or triggered by a server plugin). Try on a different server.
