### ISSUE TITLE
Bot disconnecting from server without any logs (kick or error)

### ISSUE THREAD

**Issue by numixdev** [PrismarineJS/mineflayer#3288]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.18.0
 - server:  folia
 - node: 21.5.0

## Detailed description of a problem
A clear and concise description of what the problem is, with as much context as possible.
Bot only working correctly on LAN servers. In public servers it logs with the nickname "%luckperms_highest_inherited_group_by_weight%(botname)"
What are you building? What problem are you trying to solve?
The bot can walk (so it passes the spawn hub of the server) and was supposed to message the chat after 15 seconds but nothing happends (only worked in LAN server)

## What did you try yet?
Nothing I tried fixed or enhanced it.

Did you try any method from the API?
No
Did you try any example? Any error from those?
I've got no error in the console, but with the minecraft protocol I get this when the bot disconnects:
```
Error: client timed out after 30000 milliseconds
    at Timeout._onTimeout (/home/numix/Projects/MineBot/node_modules/minecraft-protocol/src/client/keepalive.js:18:28)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Error: client timed out after 30000 milliseconds
    at Timeout._onTimeout (/home/numix/Projects/MineBot/node_modules/minecraft-protocol/src/client/keepalive.js:18:28)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```
## Your current code
```js
process.env.DEBUG = 'minecraft-protocol'
const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: 'localhost',
  port: '46141',
  username: 'LocalBot'
})

bot.once('spawn', () => {
  bot.setControlState('forward', true); // start walking

  setTimeout(() => {
    bot.setControlState('forward', false); // stop walking after 10 seconds
  }, 10000);
});

bot.once('spawn', () => {
  setTimeout(() => {
    bot.chat('hi'); // say hi after 15 seconds
  }, 15000);
});

bot.on('kicked', console.log)
bot.on('error', console.log)
```

## Expected behavior
Bot walks for 10 seconds and chat "hi" after 15

**Comment by extremeheat** [comment]
Can you provide the debug output from the console?

**Comment by numixdev** [comment]
> Can you provide the debug output from the console?

I only get this error

```
Error: client timed out after 30000 milliseconds
    at Timeout._onTimeout (/home/numix/Projects/MineBot/node_modules/minecraft-protocol/src/client/keepalive.js:18:28)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Error: client timed out after 30000 milliseconds
    at Timeout._onTimeout (/home/numix/Projects/MineBot/node_modules/minecraft-protocol/src/client/keepalive.js:18:28)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
    ```

**Comment by wgaylord** [comment]
You need to enable debugging using https://github.com/PrismarineJS/mineflayer?tab=readme-ov-file#debug to get the debug info that extremeheat is looking for.

**Comment by wgaylord** [comment]
I suspect this is due to https://github.com/PrismarineJS/mineflayer/issues/3292 but it could be its own separate issue.

**Comment by numixdev** [comment]
Ok, thanks. Will try and report here
