### ISSUE TITLE
scoreboard error

### ISSUE THREAD

**Issue by WarmyxPro** [PrismarineJS/mineflayer#3346]
const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: 'play.risecraft.xyz', // minecraft server ip
  username: 'XakEsa', // username to join as if auth is `offline`, else a unique identifier for this account. Switch if you want to change accounts
  auth: 'offline', // for offline mode servers, you can set this to 'offline'
  port: 25565,              // set if you need a port that isn't 25565
  version: "1.16.5",           // only set if you need a specific version or snapshot (ie: "1.8.9" or "1.16.5"), otherwise it's set automatically
})

bot.once('spawn', () => {
    console.log("!");
    setTimeout(() => {
        bot.chat("/register test test");
    }, 1000);
})

// Log errors and kick reasons:
bot.on('kicked', console.log)
bot.on('error', console.log)

PartialReadError: Read error for undefined : Missing characters in string, found size is 40229 expected size was 3319395
    at new ExtendableError (C:\Users\Милки\Desktop\SmartBots\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (C:\Users\Милки\Desktop\SmartBots\node_modules\protodef\src\utils.js:70:5)
    at Object.string (eval at compile (C:\Users\Милки\Desktop\SmartBots\node_modules\protodef\src\compiler.js:258:12), <anonymous>:92:15)
    at eval (eval at compile (C:\Users\Милки\Desktop\SmartBots\node_modules\protodef\src\compiler.js:258:12), <anonymous>:1949:63)
    at eval (eval at compile (C:\Users\Милки\Desktop\SmartBots\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2036:11)
    at Object.packet_declare_recipes (eval at compile (C:\Users\Милки\Desktop\SmartBots\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2041:9)
    at eval (eval at compile (C:\Users\Милки\Desktop\SmartBots\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2154:70)
    at packet (eval at compile (C:\Users\Милки\Desktop\SmartBots\node_modules\protodef\src\compiler.js:258:12), <anonymous>:2159:9)
    at CompiledProtodef.read (C:\Users\Милки\Desktop\SmartBots\node_modules\protodef\src\compiler.js:70:12)
    at e.message (C:\Users\Милки\Desktop\SmartBots\node_modules\protodef\src\compiler.js:111:49)
C:\Users\Милки\Desktop\SmartBots\node_modules\mineflayer\lib\plugins\scoreboard.js:22
        if (scoreboard.name === packet.name) {
                       ^

TypeError: Cannot read properties of undefined (reading 'name')
    at Client.<anonymous> (C:\Users\Милки\Desktop\SmartBots\node_modules\mineflayer\lib\plugins\scoreboard.js:22:24)
    at Client.emit (node:events:518:28)
    at emitPacket (C:\Users\Милки\Desktop\SmartBots\node_modules\minecraft-protocol\src\client.js:83:12)
    at FullPacketParser.<anonymous> (C:\Users\Милки\Desktop\SmartBots\node_modules\minecraft-protocol\src\client.js:112:9)
    at FullPacketParser.emit (node:events:518:28)
    at addChunk (C:\Users\Милки\Desktop\SmartBots\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:279:12)
    at readableAddChunk (C:\Users\Милки\Desktop\SmartBots\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:262:11)
    at Readable.push (C:\Users\Милки\Desktop\SmartBots\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:228:10)
    at Transform.push (C:\Users\Милки\Desktop\SmartBots\node_modules\protodef\node_modules\readable-stream\lib\_stream_transform.js:132:32)
    at FullPacketParser._transform (C:\Users\Милки\Desktop\SmartBots\node_modules\protodef\src\serializer.js:89:10)

Node.js v20.11.1

**Comment by nikitapro225** [comment]
тоже починил отключив модуль скорборд

**Comment by extremeheat** [comment]
Some scoreboard issues were fixed in 4.20.1, including https://github.com/PrismarineJS/mineflayer/pull/3324, you can update with `npm update`
