### ISSUE TITLE
 Event windowOpen did not fire within timeout of 20000ms at EventEmitter.craft (bot craft event)

### ISSUE THREAD

**Issue by Oxooi** [PrismarineJS/mineflayer#3399]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: ^4.20.1
 - server: vanilla
 - node: 21.4.0

## Detailed description of a problem
I am in the process of creating a semi-autonomous bot and am working on the "craft" part. When I ask it to craft an item that does not require crafting tables, there are no problems. But when it needs to access a table, it searches for the table, goes to the table, looks at the table, interacts with the table (its arm moves as if interacting with it), and a few seconds later I get an error message (and it does not craft the item).

```
Error: Error: Event windowOpen did not fire within timeout of 20000ms at EventEmitter.craft 
(Minecraft-Bot\node_modules\mineflayer\lib\plugins\craft.js:32:13)
 at async Object.craftHoe Minecraft-Bot\src\components\Inventory\craft\craft.js:76:5)
at async EventEmitter.<anonymous> (Minecraft-Bot\src\components\chat\chat.js:44:25)
```

## What did you try yet?
I tried to increase the timeout, 
changing the minecraft server version (1.20 > 1.16)

## Your current code
```js

async function craftItem(bot, name, amount) {
    amount = parseInt(amount, 10)
    const item = bot.registry.itemsByName[name]
    const craftingTableID = bot.registry.blocksByName.crafting_table.id

    console.log(craftingTableID);

    const craftingTable = bot.findBlock({
        matching: craftingTableID,
        maxDistance: 6

    })

    if (!craftingTable) {
        bot.chat('no crafting table found')
        return
    }

    if (item) {
        const recipe = bot.recipesFor(item.id, null, 1, craftingTable)[0];
        if (recipe) {
            let requiresTable = recipe.requiresTable === false ? null : craftingTable;

            if (requiresTable) {
                try {
                    const goal = new GoalNear(craftingTable.position.x, craftingTable.position.y, craftingTable.position.z, 1);
                    await bot.pathfinder.goto(goal);
                } catch (error) {
                    bot.chat('I can\'t go to craft table');
                }
            }

            bot.chat(`I can make ${name}`)
            try {

                const result = await bot.craft(recipe, amount, requiresTable, { timeout: 30000 });
                bot.chat(`did the recipe for ${name} ${amount} times`);
                console.log('Crafting result:', result);
            } catch (err) {
                console.error('Error during crafting:', err);
                bot.chat(`error making ${name}`)
            }
        } else {
            bot.chat(`I cannot make ${name}`)
        }
    } else {
        bot.chat(`unknown item: ${name}`)
    }
}


```

## Expected behavior
At least a window appears. and fix the error :(

**Comment by radu-gaspar** [comment]
You probably don't need this answer, it's been a while - but in my experience, the timeout error occurs when your bot is too far away from the crafting table and tries to interact with it. The bot needs to be within a 5 blocks distance away (max) to interact with anything.

When you call craft, the bot walks to the table by itself, but it seems to call the open window BEFORE he's in range.

I use my own `goto` function to wait for the bot to be near the table, then call craft.

**Comment by Omena0** [comment]
im getting this exact same error but the bot is directly next to the table.

**Comment by radu-gaspar** [comment]
> im getting this exact same error but the bot is directly next to the table.

I suggest you check the following as I've ran into these issues myself:
1. ensure it's finding and interacting with the table that's right next to it; I've had it find tables that it previously left under the ground
2. ensure there are no other opened windows, because this error is also be thrown when you've previously interacted with another block that has an inventory and wasn't closed properly (like a furnace)
3. inventory/recipe issues - providing the crafting table with the wrong recipe (for the current bot inventory) can also lead to a timeout; quickly crafting recipes without proper inventory management can also have the same timeout effect
4. if you're testing this on a server, lag can also cause timeouts, but I found this to be less likely

**Comment by Omena0** [comment]
> > im getting this exact same error but the bot is directly next to the table.
> 
> I suggest you check the following as I've ran into these issues myself:
> 
>     1. ensure it's finding and interacting with the table that's right next to it; I've had it find tables that it previously left under the ground
> 
>     2. ensure there are no other opened windows, because this error is also be thrown when you've previously interacted with another block that has an inventory and wasn't closed properly (like a furnace)
> 
>     3. inventory/recipe issues - providing the crafting table with the wrong recipe (for the current bot inventory) can also lead to a timeout; quickly crafting recipes without proper inventory management can also have the same timeout effect
> 
>     4. if you're testing this on a server, lag can also cause timeouts, but I found this to be less likely

There are no other tables, the bot has just joined the game (I made a test script that just tries to craft a wooden pickaxe), the recipe should be correct, and I'm running this on my own server which is constantly around 0.15 mspt

**Comment by radu-gaspar** [comment]
> > > im getting this exact same error but the bot is directly next to the table.
> > 
> > 
> > I suggest you check the following as I've ran into these issues myself:
> > ```
> > 1. ensure it's finding and interacting with the table that's right next to it; I've had it find tables that it previously left under the ground
> > 
> > 2. ensure there are no other opened windows, because this error is also be thrown when you've previously interacted with another block that has an inventory and wasn't closed properly (like a furnace)
> > 
> > 3. inventory/recipe issues - providing the crafting table with the wrong recipe (for the current bot inventory) can also lead to a timeout; quickly crafting recipes without proper inventory management can also have the same timeout effect
> > 
> > 4. if you're testing this on a server, lag can also cause timeouts, but I found this to be less likely
> > ```
> 
> There are no other tables, the bot has just joined the game (I made a test script that just tries to craft a wooden pickaxe), the recipe should be correct, and I'm running this on my own server which is constantly around 0.15 mspt

ok, that's good. If you want to share your code, I can have a look; also, is that timeout consistent or are you getting it occasionally?
