### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Kaleert** [PrismarineJS/mineflayer#3413]
mineflayer - lastest
MC: 1 20 6 with ViaBackwards and ViaVersion
node: 20

error:
C:\Users\Kaleert\Desktop>node bot.js
C:\Users\Kaleert\Desktop\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read properties of undefined (reading 'overworld')
    at handleRespawnPacketData (C:\Users\Kaleert\Desktop\node_modules\mineflayer\lib\plugins\game.js:46:63)
    at Client.<anonymous> (C:\Users\Kaleert\Desktop\node_modules\mineflayer\lib\plugins\game.js:80:5)
    at Client.emit (node:events:531:35)
    at emitPacket (C:\Users\Kaleert\Desktop\node_modules\minecraft-protocol\src\client.js:83:12)
    at FullPacketParser.<anonymous> (C:\Users\Kaleert\Desktop\node_modules\minecraft-protocol\src\client.js:112:9)
    at FullPacketParser.emit (node:events:519:28)
    at addChunk (C:\Users\Kaleert\Desktop\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:279:12)
    at readableAddChunk (C:\Users\Kaleert\Desktop\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:262:11)
    at Readable.push (C:\Users\Kaleert\Desktop\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:228:10)
    at Transform.push (C:\Users\Kaleert\Desktop\node_modules\protodef\node_modules\readable-stream\lib\_stream_transform.js:132:32)

file:
const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: 'localhost', // айпи майнкрафт сервера
  username: 'kaleert1', // ник бота
  auth: 'offline' // для пираток нужно заменить на 'offline'
  // port: 25565,                // прописывайте, если порт не 25565
  // version: false,             // прописывайте, если нужна конкретная версия или снапшот (например: "1.8.9" или "1.16.5"), иначе версия будет выбрана автоматически
  // password: '12345678'        // прописывайте, если хотите использовать аутентификацию через пароль (может быть ненадёжно)
})

bot.on('chat', (username, message) => {
  if (username === bot.username) return
  bot.chat(message)
})

// Логирование ошибок и причин отключения от сервера:
bot.on('kicked', console.log)
bot.on('error', console.log)
// end file

**Comment by rom1504** [comment]
Duplicate of https://github.com/PrismarineJS/mineflayer/issues/3406
