### ISSUE TITLE
Help to Debug ECONNRESET when Running in a Deno Environment

### ISSUE THREAD

**Issue by Asguho** [PrismarineJS/mineflayer#3421]
## Versions
- mineflayer: 4.20.1
- server: vanilla 1.20.2
- deno: 1.45.2

## Detailed Description of the Problem
I have been trying to run mineflayer in Deno for a while. When teaching others programming, the setup required in Deno is far less complex than setting up a Node.js environment. I fully understand that mineflayer does not officially support other runtimes such as Deno or Bun, due to the development time and testing needed.

## What Have You Tried So Far?
Deno has come a long way, and I have reported multiple inconsistencies from Node.js that prevented me from running mineflayer in Deno. However, I have now run into a dead end with the following code:
```js
import mineflayer from 'npm:mineflayer';

const bot = mineflayer.createBot({
  username: 'bot',
  host: 'localhost',
  version: '1.20.2',
  port: '2555',
});

bot.on('inject_allowed', () => {
  console.log('inject allowed');
});
bot.on('login', () => {
  console.log('Successfully logged in!');
});
bot.on('spawn', () => {
  console.log('Successfully spawned in!');
});
```
Without a Minecraft server running on localhost:2555, it produces the following error:
```bash
inject allowed
Error: connect ECONNREFUSED 127.0.0.1:2555 - Local (undefined:undefined)
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
    at __node_internal_exceptionWithHostPort (ext:deno_node/internal/errors.ts:217:10)
    at TCPConnectWrap._afterConnect [as oncomplete] (node:net:171:16)
    at TCP.afterConnect (ext:deno_node/internal_binding/connection_wrap.ts:43:11)
    at ext:deno_node/internal_binding/tcp_wrap.ts:302:14
    at eventLoopTick (ext:core/01_core.js:168:7) {
  errno: -4078,
  code: "ECONNREFUSED",
  syscall: "connect",
  address: "127.0.0.1",
  port: 2555,
  localAddress: undefined,
  localPort: undefined
}
```
However, when I run a local Minecraft server on localhost:2555, it returns the error:
```bash
inject allowed
Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
    at __node_internal_errnoException (ext:deno_node/internal/errors.ts:141:10)
    at TCP.onStreamRead [as onread] (ext:deno_node/internal/stream_base_commons.ts:209:20)
    at TCP.#read (ext:deno_node/internal_binding/stream_wrap.ts:245:12)
    at eventLoopTick (ext:core/01_core.js:168:7) {
  errno: -4077,
  code: "ECONNRESET",
  syscall: "read"
}
```
In my limited understanding, an ECONNRESET occurs when the host refuses the connection for some reason. However, the Minecraft server produces no error messages. Is there a way I can get more information from either Minecraft or mineflayer?

**Comment by Macil** [comment]
Mineflayer works fine for me now in Deno 2.6.3. Deno seems to have greatly increased its Node compatibility since 1.x versions.
