### ISSUE TITLE
Add support for 1.21.1

### ISSUE THREAD

**Issue by victor0221** [PrismarineJS/mineflayer#3452]
## Describe the solution you'd like
Add support for 1.21.1

**Comment by extremeheat** [comment]
#3406

**Comment by Kisele4ekYT-Sv** [comment]
TypeError: this.readCompiler.addProtocol is not a function
    at ProtoDefCompiler.addProtocol (C:\Users\minec\OneDrive\Desktop\testbot\node_modules\protodef\src\compiler.js:28:27)
    at createProtocol (C:\Users\minec\OneDrive\Desktop\testbot\node_modules\minecraft-protocol\src\transforms\serializer.js:33:14)
    at createSerializer (C:\Users\minec\OneDrive\Desktop\testbot\node_modules\minecraft-protocol\src\transforms\serializer.js:49:25)
    at Client.setSerializer (C:\Users\minec\OneDrive\Desktop\testbot\node_modules\minecraft-protocol\src\client.js:42:23)
    at set state (C:\Users\minec\OneDrive\Desktop\testbot\node_modules\minecraft-protocol\src\client.js:133:10)
    at new Client (C:\Users\minec\OneDrive\Desktop\testbot\node_modules\minecraft-protocol\src\client.js:33:16)
    at Object.createClient (C:\Users\minec\OneDrive\Desktop\testbot\node_modules\minecraft-protocol\src\createClient.js:37:18)
    at Object.createBot (C:\Users\minec\OneDrive\Desktop\testbot\node_modules\mineflayer\lib\loader.js:99:35)
    at Object.<anonymous> (C:\Users\minec\OneDrive\Desktop\testbot\index.js:3:24)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)

Node.js v22.12.0

**Comment by rom1504** [comment]
use a new issue and provide a lot more details
