### ISSUE TITLE
bug with 1 21 1 server but with viaversion in lobby

### ISSUE THREAD

**Issue by EbatteSratte** [PrismarineJS/mineflayer#3455]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: #.#.#
 - server: vanilla/spigot/paper #.#.#
 - node: #.#.#

## Detailed description of a problem
i start bot and i think in lobby i have crash

## Your current code
```js

/*
Some code here, replace this
*/


```

## Additional context
const { minY, height } = bot.registry.dimensionsByName[bot.game.dimension]
                                                              ^
TypeError: Cannot read properties of undefined (reading 'the_end')
    at handleRespawnPacketData (/home/container/node_modules/mineflayer/lib/plugins/game.js:46:63)
    at Client.<anonymous> (/home/container/node_modules/mineflayer/lib/plugins/game.js:80:5)
    at Client.emit (node:events:531:35)
    at emitPacket (/home/container/node_modules/minecraft-protocol/src/client.js:83:12)
    at FullPacketParser.<anonymous> (/home/container/node_modules/minecraft-protocol/src/client.js:112:9)
    at FullPacketParser.emit (node:events:519:28)
    at addChunk (/home/container/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:279:12)
    at readableAddChunk (/home/container/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:262:11)
    at Readable.push (/home/container/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:228:10)
    at Transform.push (/home/container/node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:132:32)

**Comment by EbatteSratte** [comment]
before the server upgrade everything was working

**Comment by r58iiz** [comment]
Library hasn't been updated to work with 1.21.1 yet.

**Comment by EbatteSratte** [comment]
but server has viaversion

**Comment by SanD-STAX** [comment]
II'm also having this issue, I tried using the default DIM and min_Y but it didn't work
