### ISSUE TITLE
AssertionError [ERR_ASSERTION]: varint is too big

### ISSUE THREAD

**Issue by watercatlxh** [PrismarineJS/mineflayer#3472]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: latest
 - server: spigot/paper 1.18.1
 - node: 20.17.0

## Detailed description of a problem
I attempted to create an automated reward collection bot, but after the program has been running for a while, it encounters the following error and is unable to continue running.

## What did you try yet?

Did you try any method from the API?
yes
Did you try any example? Any error from those?
yes

## Error
```js

AssertionError [ERR_ASSERTION]: varint is too big
    at Object.readVarInt [as varint] (/usr/local/lib/python3.11/dist-packages/javascript/js/node_modules/protodef/src/datatypes/utils.js:80:12)
    at Object.string (eval at compile (/usr/local/lib/python3.11/dist-packages/javascript/js/node_modules/protodef/src/compiler.js:258:12), <anonymous>:89:61)
    at Object.packet_success (eval at compile (/usr/local/lib/python3.11/dist-packages/javascript/js/node_modules/protodef/src/compiler.js:258:12), <anonymous>:568:65)
    at eval (eval at compile (/usr/local/lib/python3.11/dist-packages/javascript/js/node_modules/protodef/src/compiler.js:258:12), <anonymous>:590:54)
    at packet (eval at compile (/usr/local/lib/python3.11/dist-packages/javascript/js/node_modules/protodef/src/compiler.js:258:12), <anonymous>:595:9)
    at CompiledProtodef.read (/usr/local/lib/python3.11/dist-packages/javascript/js/node_modules/protodef/src/compiler.js:70:12)
    at e.message (/usr/local/lib/python3.11/dist-packages/javascript/js/node_modules/protodef/src/compiler.js:111:49)
    at tryCatch (/usr/local/lib/python3.11/dist-packages/javascript/js/node_modules/protodef/src/utils.js:50:16)
    at CompiledProtodef.parsePacketBuffer (/usr/local/lib/python3.11/dist-packages/javascript/js/node_modules/protodef/src/compiler.js:111:29)
    at FullPacketParser.parsePacketBuffer (/usr/local/lib/python3.11/dist-packages/javascript/js/node_modules/protodef/src/serializer.js:68:23) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==',
  field: 'login.toClient'
}


```

Then

```
Timed out get 6 createBot <Thread(Thread-2202 (loop), started daemon 140287095662272)>
Timed out accessing 'quit'
```

and

```
Timed out get 6 createBot <Thread(Thread-2202 (loop), started daemon 140287095662272)>
Timed out accessing 'createBot'
```

## Expected behavior
No such error occurred; it continued to function normally.

## Additional context
If you need my code, I will provide it.
Thank you very much for your assistance in resolving my issue.

**Comment by extremeheat** [comment]
This is likely a problem on the server. Can you reproduce on another server?

**Comment by watercatlxh** [comment]
I think so, that server is using custom packets, so is there a way to implement an action that ignores some packets?
