### ISSUE TITLE
problem with 1.21.1

### ISSUE THREAD

**Issue by BallisticOK** [PrismarineJS/mineflayer#3492]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.23.0
 - server: vanilla/spigot/paper paper 1.12.1
 - node: node.js 20

## Detailed description of a problem
when trying to run the example code to learn about this im getting error the bot will join my server but flot there give me an error then just leave idk how i would fix then and the server is running local host

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code
```js

const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: 'localhost', // minecraft server ip
  username: 'Bot', // username to join as if auth is `offline`, else a unique identifier for this account. Switch if you want to change accounts
  auth: 'microsoft' // for offline mode servers, you can set this to 'offline'
  // port: 25565,              // set if you need a port that isn't 25565
  // version: false,           // only set if you need a specific version or snapshot (ie: "1.8.9" or "1.16.5"), otherwise it's set automatically
  // password: '12345678'      // set if you want to use password-based auth (may be unreliable). If specified, the `username` must be an email
})

bot.on('chat', (username, message) => {
  if (username === bot.username) return
  bot.chat(message)
})

// Log errors and kick reasons:
bot.on('kicked', console.log)
bot.on('error', console.log)


```

## Expected behavior
it should just join if im not mistaken and stay there till i make it do more

## Additional context
here is the error im getting 

```

RangeError: Read error for undefined : The value of "offset" is out of range. It must be >= 0 and <= 46944. Received -620568453
    at boundsError (node:internal/buffer:88:9)
    at Buffer.readUInt8 (node:internal/buffer:254:5)
    at Object.readVarInt [as varint] (/home/container/node_modules/protodef/src/datatypes/utils.js:68:22)
    at Object.string (eval at compile (/home/container/node_modules/protodef/src/compiler.js:262:12), <anonymous>:97:61)
    at eval (eval at compile (/home/container/node_modules/protodef/src/compiler.js:262:12), <anonymous>:3837:44)
    at eval (eval at compile (/home/container/node_modules/protodef/src/compiler.js:262:12), <anonymous>:3842:17)
    at eval (eval at compile (/home/container/node_modules/protodef/src/compiler.js:262:12), <anonymous>:3847:15)
    at eval (eval at compile (/home/container/node_modules/protodef/src/compiler.js:262:12), <anonymous>:3850:13)
    at eval (eval at compile (/home/container/node_modules/protodef/src/compiler.js:262:12), <anonymous>:3852:11)
    at Object.packet_advancements (eval at compile (/home/container/node_modules/protodef/src/compiler.js:262:12), <anonymous>:3857:9) {
  code: 'ERR_OUT_OF_RANGE',
  field: 'play.toClient'
}
An error occurred: ERR_OUT_OF_RANGE - Deserialization error for play.toClient : Read error for undefined : The value of "offset" is out of range. It must be >= 0 and <= 46944. Received -620568453 RangeError: Read error for undefined : The value of "offset" is out of range. It must be >= 0 and <= 46944. Received -620568453
    at boundsError (node:internal/buffer:88:9)
    at Buffer.readUInt8 (node:internal/buffer:254:5)
    at Object.readVarInt [as varint] (/home/container/node_modules/protodef/src/datatypes/utils.js:68:22)
    at Object.string (eval at compile (/home/container/node_modules/protodef/src/compiler.js:262:12), <anonymous>:97:61)
    at eval (eval at compile (/home/container/node_modules/protodef/src/compiler.js:262:12), <anonymous>:3837:44)
    at eval (eval at compile (/home/container/node_modules/protodef/src/compiler.js:262:12), <anonymous>:3842:17)
    at eval (eval at compile (/home/container/node_modules/protodef/src/compiler.js:262:12), <anonymous>:3847:15)
    at eval (eval at compile (/home/container/node_modules/protodef/src/compiler.js:262:12), <anonymous>:3850:13)
    at eval (eval at compile (/home/container/node_modules/protodef/src/compiler.js:262:12), <anonymous>:3852:11)
    at Object.packet_advancements (eval at compile (/home/container/node_modules/protodef/src/compiler.js:262:12), <anonymous>:3857:9) {
  code: 'ERR_OUT_OF_RANGE',
  field: 'play.toClient'
}

```

**Comment by rom1504** [comment]
"vanilla/spigot/paper paper 1.12.1" which one ?

**Comment by BallisticOK** [comment]
paper

**Comment by BallisticOK** [comment]
but i have since fixed this problem

**Comment by rom1504** [comment]
Fixed how?

**Comment by i240c** [comment]
How did you fix it?

**Comment by mdmanl** [comment]
Having this same issue, how did you fix it?

**Comment by rom1504** [comment]
Same as https://github.com/PrismarineJS/node-minecraft-protocol/issues/1337

**Comment by Lunarisyn104** [comment]
I have the same issue, are there any fixxes now?

**Comment by rom1504** [comment]
No please report any information you have (log, specific environment to reproduce) to help fix

**Comment by mdmanl** [comment]
At this point it feels like I am absolutely chasing a ghost..
I can't replicate this error on a local server at all. Not with vanilla, not with paper, not with purpur, not with viaversion.

However, what I've noticed. One day the bot spits the following error, doesn't stay connected and doesn't respond to any commands:
```
RangeError [ERR_OUT_OF_RANGE]: Read error for undefined : The value of "offset" is out of range. It must be >= 0 and <= 103190. Received -199989011
    at new NodeError (node:internal/errors:399:5)
    at boundsError (node:internal/buffer:88:9)
    at Buffer.readUInt8 (node:internal/buffer:254:5)
    at Object.readVarInt [as varint] (\node_modules\protodef\src\datatypes\utils.js:68:22)
    at Object.string (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:97:61)
    at eval (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:3837:44)
    at eval (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:3842:17)
    at eval (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:3847:15)
    at eval (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:3850:13)
    at eval (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:3852:11) {
  code: 'ERR_OUT_OF_RANGE',
  field: 'play.toClient'
}
RangeError [ERR_OUT_OF_RANGE]: Read error for undefined : The value of "offset" is out of range. It must be >= 0 and <= 103190. Received -199989011
    at new NodeError (node:internal/errors:399:5)
    at boundsError (node:internal/buffer:88:9)
    at Buffer.readUInt8 (node:internal/buffer:254:5)
    at Object.readVarInt [as varint] (\node_modules\protodef\src\datatypes\utils.js:68:22)
    at Object.string (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:97:61)
    at eval (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:3837:44)
    at eval (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:3842:17)
    at eval (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:3847:15)
    at eval (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:3850:13)
    at eval (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:3852:11) {
  code: 'ERR_OUT_OF_RANGE',
  field: 'play.toClient'
}
```

The day after, it only spitted the following error, but stayed connected and just worked:
```
PartialReadError: Read error for undefined : Missing characters in string, found size is 103191 expected size was 1957790
    at new ExtendableError (\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (\protodef\src\utils.js:70:5)
    at Object.string (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:100:15)
    at eval (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:3837:44)
    at eval (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:3842:17)
    at eval (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:3847:15)
    at eval (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:3850:13)
    at eval (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:3852:11)
    at Object.packet_advancements (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:3857:9)
    at eval (eval at compile (\node_modules\protodef\src\compiler.js:262:12), <anonymous>:4222:64)
Bot spawned
```

The day after that, it went to the behaviour like on the first day, not working. And today it's back to it's behaviour of the second day, only the 1 error and working again..


I'll ask the server owner for a full list of all the plugins, but at this moment it doesn't make any sense for me.

**Comment by Because66666** [comment]
@mdmanl The code you posted, I've encountered them all. Here I give my situation: Client: node: v22.13.1, and mineflayer@4.26.0 | MIT | deps: 17 | versions: 178, Server: as shown in the figure.

![Image](https://github.com/user-attachments/assets/029d5199-4e79-4c57-beb5-616aec86d980)

**Comment by Because66666** [comment]
If I try to use my own server, with an unmodified map, I will find that my bot can log in normally.

**Comment by notsapinho** [comment]
For anyone wondering, this patch on minecraft-protocol@1.57.0 might do it:

```bash
diff --git a/src/transforms/serializer.js b/src/transforms/serializer.js
index 76f7ef271134eb1224e2eaf93605d38b1c1d7942..c6fcdd8a130339a6558332056ae4d4adfeb1ab46 100644
--- a/src/transforms/serializer.js
+++ b/src/transforms/serializer.js
@@ -32,6 +32,7 @@ function createProtocol (state, direction, version, customPackets, compiled = tr
     compiler.addProtocol(mergedProtocol, [state, direction])
     nbt.addTypesToCompiler('big', compiler)
     const proto = compiler.compileProtoDefSync()
+    proto.setVariable('noArraySizeCheck', true);
     protocols[key] = proto
     return proto
   }
```
