### ISSUE TITLE
PartialReadError: Read error for undefined : Missing characters in string, found size is 24 expected size was 111

### ISSUE THREAD

**Issue by marcosar26** [PrismarineJS/mineflayer#3510]
```
PartialReadError: Read error for undefined : Missing characters in string, found size is 24 expected size was 111
    at new ExtendableError (/root/bot/node_modules/protodef/src/utils.js:63:13)
    at new PartialReadError (/root/bot/node_modules/protodef/src/utils.js:70:5)
    at ProtoDef.readPString (/root/bot/node_modules/protodef/src/datatypes/utils.js:107:11)
    at ProtoDef.read (/root/bot/node_modules/protodef/src/protodef.js:36:25)
    at ProtoDef.read (/root/bot/node_modules/protodef/src/protodef.js:36:25)
    at ProtoDef.read (/root/bot/node_modules/protodef/src/protodef.js:114:29)
    at e.message (/root/bot/node_modules/protodef/src/protodef.js:153:49)
    at tryCatch (/root/bot/node_modules/protodef/src/utils.js:50:16)
    at ProtoDef.parsePacketBuffer (/root/bot/node_modules/protodef/src/protodef.js:153:29)
    at Client.onCustomPayload (/root/bot/node_modules/minecraft-protocol/src/client/pluginChannels.js:58:31) {
  partialReadError: true
}
```

Trying to run my script with: npx tsx src/script.ts gives me this error... Why?

**Comment by marcosar26** [comment]
The same script works on WebStorm (Windows) but not in my Ubuntu server, wtf ?

**Comment by marcosar26** [comment]
Fixed
