### ISSUE TITLE
Проблема с запуском бота

### ISSUE THREAD

**Issue by crazy445** [PrismarineJS/mineflayer#3520]
- [ ] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.20.1
 - server: paper mc.MasedWorld.net
 - node: #.#.#

## Detailed description of a problem
Я как понимаю, после вайп и с добоавлением двух режимов, у меня началась проблема в лобби
Ошибка:
const { minY, height } = bot.registry.dimensionsByName[bot.game.dimension]
                                                              ^
TypeError: Cannot read properties of undefined (reading 'overworld')
    at handleRespawnPacketData (/home/container/node_modules/mineflayer/lib/plugins/game.js:46:63)
    at Client.<anonymous> (/home/container/node_modules/mineflayer/lib/plugins/game.js:80:5)
    at Client.emit (node:events:526:35)
    at emitPacket (/home/container/node_modules/minecraft-protocol/src/client.js:83:12)
    at FullPacketParser.<anonymous> (/home/container/node_modules/minecraft-protocol/src/client.js:112:9)
    at FullPacketParser.emit (node:events:514:28)
    at addChunk (/home/container/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:279:12)
    at readableAddChunk (/home/container/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:262:11)
    at Readable.push (/home/container/node_modules/protodef/node_modules/readable-stream/lib/_stream_readable.js:228:10)
    at Transform.push (/home/container/node_modules/protodef/node_modules/readable-stream/lib/_stream_transform.js:132:32)

## What did you try yet?

Я пробовал через replit решить проблему, но у меня всячески вылезает одна и та же ошибка 
## Your current code
```
[рабочий код для клана (без дс).txt](https://github.com/user-attachments/files/18051554/default.txt)
js


## Expected behavior
Бот должен был запуститься на сервер и зайти на порт ЙОТА

**Comment by extremeheat** [comment]
Update your dependencies
```js
npm update
```

**Comment by crazy445** [comment]
Теперь проблема в чанке:
Chunk size is 337 but only 1 was read ; partial packet : {"name":123}; buffer :7b04000a09000565787472610a0000000108000474657874001dd09cd0b0d0b3d0b0d0b7d0b8d0bd20d181d0b5d180d0b2d0b5d180d0b000080004746578740000001768747470733a2f2f6d61736564776f726c642e6e65742f000a09000565787472610a0000000108000474657874001dd09fd180d0b0d0b2d0b8d0bbd0b020d181d0b5d180d0b2d0b5d180d0b000080004746578740000001d68747470733a2f2f6d61736564776f726c642e6e65742f2372756c6573000a09000565787472610a00000001080004746578740012d092d09ad0bed0bdd182d0b0d0bad182d0b500080004746578740000001a68747470733a2f2f766b2e636f6d2f6d617365645f776f726c64000a09000565787472610a00000001080004746578740007446973636f726400080004746578740000001e68747470733a2f2f6d61736564776f726c642e6e65742f646973636f7264
в чем проблема в чанке?

**Comment by crazy445** [comment]
![image](https://github.com/user-attachments/assets/7f4dcff6-d166-45c9-a865-f12c37ef8992)

**Comment by extremeheat** [comment]
Try a different server
