### ISSUE TITLE
PartialReadError (block?) 1.20.5+

### ISSUE THREAD

**Issue by ghost** [PrismarineJS/mineflayer#3526]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.23,0 (Latest)
 - server: purpur
 - node: 22.12.0

## Detailed description of a problem
The bot comes into the server and catches a lot of errors. Sometimes this happens on a vanilla server. On version 1.20.4 and below the error doesn't appear, but with 1.20.5+ it is already there. Not a pro, but you can tell from the log that the error is with block properties, maybe it's a crooked bump version on 1.20.5 done poorly.

## Your current code
```ts
import mineflayer from 'mineflayer';
import * as readline from 'readline';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});


const bot = mineflayer.createBot({
  username: 'mineflayer',
  host: 'localhost',
  port: 25565,
  version: '1.20.5'
});

bot.on('error', console.log);
bot.on('kicked', console.log);

rl.on('line', (line) => {
  readline.moveCursor(process.stdout, 0, -1);
  readline.clearScreenDown(process.stdout);
  bot.chat(line.toString());
  rl.prompt();
});

bot.on('message', (message) => {
  readline.moveCursor(process.stdout, -2, 0);
  console.log(message.toAnsi());
  rl.prompt();
});
```

## Log
```
Version: in this log - 1.20.5 (1.20.6, 1.21, etc.)
- Bot stays on Purpur (Velocity) Lobby
- bot.chat('/connect')
[] Connecting...
[] You connected to the server
> PartialReadError: Read error for undefined : Missing characters in string, found size is 592 expected size was 653
    at new ExtendableError (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\utils.js:70:5)
    at Object.string (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:100:15)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:834:47)
    at Object.BlockProperty (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:838:9)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:870:45)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:875:11)
    at Object.BlockPredicate (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:879:9)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:181:50)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:186:15)
PartialReadError: Read error for undefined : Missing characters in string, found size is 85 expected size was 135
    at new ExtendableError (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\utils.js:70:5)
    at Object.string (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:100:15)
    at Object.BlockProperty (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:813:57)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:870:45)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:875:11)
    at Object.BlockPredicate (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:879:9)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:181:50)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:186:15)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:189:13)
PartialReadError: Read error for undefined : Missing characters in string, found size is 629 expected size was 273992461
    at new ExtendableError (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\utils.js:70:5)
    at Object.string (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:100:15)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:834:47)
    at Object.BlockProperty (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:838:9)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:870:45)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:875:11)
    at Object.BlockPredicate (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:879:9)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:181:50)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:186:15)
PartialReadError: Read error for undefined : undefined
    at new ExtendableError (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\utils.js:63:13)
    at new PartialReadError (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\utils.js:70:5)
    at Object.reader [as i8] (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\datatypes\numeric.js:89:48)
    at Object.Slot (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:680:63)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:625:40)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:630:15)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:632:13)
    at Object.SlotComponent (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:676:9)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:695:49)
    at eval (eval at compile (C:\Users\Professional\Desktop\mmmmm\node_modules\protodef\src\compiler.js:262:12), <anonymous>:700:15)
```

**Comment by extremeheat** [comment]
Likely https://github.com/PrismarineJS/node-minecraft-protocol/issues/1348

**Comment by extremeheat** [comment]
Various SlotComponent issues were fixed in minecraft-data v3.109.1 with https://github.com/PrismarineJS/minecraft-data/pull/1173 and https://github.com/PrismarineJS/minecraft-data/pull/1155, please update your dependencies with `npm update` and check if the issue persists
