### ISSUE TITLE
Use of undefined in plugins/breath.js

### ISSUE THREAD

**Issue by wAIfu-DEV** [PrismarineJS/mineflayer#3534]
- [x] The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 4.23.0
 - server: vanilla LAN 1.16
 - node: 20.9.0 (x64)

## Detailed description of a problem
Error arises at spawn of bot, forcing a shutdown.

Here is the error message:
```
C:\Users\<user>\Desktop\mineflayerTest\node_modules\mineflayer\lib\plugins\breath.js:16
        bot.oxygenLevel = Math.round(packet.metadata[1].value / 15)
                                                        ^

TypeError: Cannot read properties of undefined (reading 'value')
    at Client.<anonymous> (C:\Users\<user>\Desktop\mineflayerTest\node_modules\mineflayer\lib\plugins\breath.js:16:57)
    at Client.emit (node:events:526:35)
    at emitPacket (C:\Users\<user>\Desktop\mineflayerTest\node_modules\minecraft-protocol\src\client.js:83:12)
    at FullPacketParser.<anonymous> (C:\Users\<user>\Desktop\mineflayerTest\node_modules\minecraft-protocol\src\client.js:112:9)
    at FullPacketParser.emit (node:events:514:28)
    at addChunk (C:\Users\<user>\Desktop\mineflayerTest\node_modules\readable-stream\lib\internal\streams\readable.js:321:12)
    at readableAddChunk (C:\Users\<user>\Desktop\mineflayerTest\node_modules\readable-stream\lib\internal\streams\readable.js:298:9)
    at Readable.push (C:\Users\<user>\Desktop\mineflayerTest\node_modules\readable-stream\lib\internal\streams\readable.js:244:10)
    at FullPacketParser._transform (C:\Users\<user>\Desktop\mineflayerTest\node_modules\protodef\src\serializer.js:89:10)
    at Transform._write (C:\Users\<user>\Desktop\mineflayerTest\node_modules\readable-stream\lib\internal\streams\transform.js:153:8)
```

The concerned piece of code is as follow:

```js
function inject (bot) {
  if (bot.supportFeature('mcDataHasEntityMetadata')) {
    // this is handled inside entities.js. We don't yet have entity metadataKeys for all versions but once we do
    // we can delete the numerical checks here and in entities.js https://github.com/extremeheat/mineflayer/blob/eb9982aa04973b0086aac68a2847005d77f01a3d/lib/plugins/entities.js#L469
    return
  }
  bot._client.on('entity_metadata', (packet) => {
    if (!bot.entity) return
    if (bot.entity.id !== packet.entityId) return
    for (const metadata of packet.metadata) {
      if (metadata.key === 1) {
        bot.oxygenLevel = Math.round(packet.metadata[1].value / 15) // <- this causes the error, packet.metadata[1] may be undefined, use metadata instead
        bot.emit('breath')
      }
    }
  })
}
```

Using the following code, here is the log of metadata and packet:

```
metadata: { key: 1, type: 1, value: 252 }
packet: { entityId: <id>, metadata: [ { key: 1, type: 1, value: 252 } ] }
```
As you can observe, packet.metdata[1] does not exist.

## Fix

```js
for (const metadata of packet.metadata) {
      if (metadata.key === 1) {
        bot.oxygenLevel = Math.round(metadata.value / 15) // <- this fixes it
        bot.emit('breath')
      }
    }
```

## Expected behavior
Not to crash at spawn :^)

**Comment by wAIfu-DEV** [comment]
also sorry for not providing the fix as a pull request, I have 0 idea how those work

**Comment by rom1504** [comment]
Press edit on the file in GitHub UI then press open PR, that's it

**Comment by wAIfu-DEV** [comment]
fix was merged
