### ISSUE TITLE
Error when connecting

### ISSUE THREAD

**Issue by PhanaticD** [PrismarineJS/mineflayer#363]
I got this error when trying out the quitter script

TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Bot.EventEmitter.emit (events.js:74:15)
    at Client.<anonymous> (/root/node_modules/mineflayer/index.js:89:10)
    at Client.EventEmitter.emit (events.js:95:17)
    at cb (/root/node_modules/mineflayer/node_modules/minecraft-protocol/dist/createClient.js:59:16)
    at /root/node_modules/mineflayer/node_modules/minecraft-protocol/node_modules/yggdrasil/lib/index.js:59:7
    at Request._callback (/root/node_modules/mineflayer/node_modules/minecraft-protocol/node_modules/yggdrasil/lib/index.js:30:9)
    at Request.self.callback (/root/node_modules/mineflayer/node_modules/minecraft-protocol/node_modules/yggdrasil/node_modules/request/request.js:121:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/root/node_modules/mineflayer/node_modules/minecraft-protocol/node_modules/yggdrasil/node_modules/request/request.js:978:14)

**Comment by rom1504** [comment]
Try adding `bot.on('error',function (err){console.log(err.stack)});`

**Comment by PhanaticD** [comment]
it says "undefined" then

**Comment by rom1504** [comment]
https://github.com/zekesonxx/node-yggdrasil/blob/master/lib/index.js#L50

**Comment by rom1504** [comment]
I think yggdrasil is giving us a undefined error. That should be fixed.

Anyway it likely means authentication is failing. Are you providing your user and password properly @PhanaticD ?

**Comment by PhanaticD** [comment]
yea I think so, it worked fine when I did it a few days ago so im at a loss what changed

**Comment by rom1504** [comment]
ah, try `bot.on('error',function (err){console.log(err)});`

Looks like https://github.com/zekesonxx/node-yggdrasil/blob/master/lib/index.js#L142 is not calling the callback properly.

**Comment by PhanaticD** [comment]
it says "Invalid credentials." but it is right I obviously cant post my email and password but yea

**Comment by rom1504** [comment]
Does that happen everytime or when you try to connect several times?

**Comment by PhanaticD** [comment]
it works now when I try, but it didn't two hours earlier

**Comment by rom1504** [comment]
Did you call quitter.js like that ` node quitter.js <host> <port> [<name>] [<password>]` ?

**Comment by rom1504** [comment]
Okay if you connect too often the mojang server bans you for a few minutes.

**Comment by PhanaticD** [comment]
oh ok

**Comment by rom1504** [comment]
So it works then ?
closing in favor of https://github.com/zekesonxx/node-yggdrasil/issues/12 (for better errors)
