### ISSUE TITLE
Error parsing chat messages

### ISSUE THREAD

**Issue by safazi** [PrismarineJS/mineflayer#475]
Note: I am not in any way using chat. This is sort of like the entities crash, it just happens randomly.

Here is my error:
```
Error parsing text '[object Object]'
C:\Users\safazi\node_modules\mojangson\index.js:9
    throw e;
    ^

TypeError: this._input.match is not a function
    at Object.next (C:\Users\safazi\node_modules\mojangson\grammar.js:535:37)
    at Object.lex (C:\Users\safazi\node_modules\mojangson\grammar.js:576:22)
    at lex (C:\Users\safazi\node_modules\mojangson\grammar.js:198:27)
    at Parser.parse (C:\Users\safazi\node_modules\mojangson\grammar.js:211:26)
    at Object.parse (C:\Users\safazi\node_modules\mojangson\index.js:5:19)
    at ChatMessage.parse (C:\Users\safazi\node_modules\mineflayer\lib\chat_message.js:134:41)
    at new ChatMessage (C:\Users\safazi\node_modules\mineflayer\lib\chat_message.js:17:8)
    at C:\Users\safazi\node_modules\mineflayer\lib\chat_message.js:61:30
    at Array.forEach (native)
    at ChatMessage.parse (C:\Users\safazi\node_modules\mineflayer\lib\chat_message.js:57:16)
```

**Comment by rom1504** [comment]
Are you using version 2.0.0 of mineflayer ?
Can you add a console.log at line 134 of chat_message.js ?

**Comment by safazi** [comment]
`console.log(this.hoverEvent.value);`
results in
`[ { text: '{id:"minecraft:air",Count:1b,Damage:0s}' } ]`

**Comment by safazi** [comment]
bump
