### ISSUE TITLE
Crash after joining server

### ISSUE THREAD

**Issue by 27therealone** [PrismarineJS/mineflayer#486]
After joining a server on version 1.8 it crashes a few seconds after with this error
/root/node_modules/prismarine-chunk/dist/pc/1.8/chunk.js:218
      if (data.length != SECTION_SIZE * chunkCount + w * l) throw new Error('Data buffer not correct size (was ' + data.length + ', expected ' + BUFFER_SIZE + ')');
                                                            ^

Error: Data buffer not correct size (was 51456, expected 196864)
    at Chunk.load (/root/node_modules/prismarine-chunk/dist/pc/1.8/chunk.js:218:67)
    at addColumn (/root/node_modules/mineflayer/lib/plugins/blocks.js:46:12)
    at Client.<anonymous> (/root/node_modules/mineflayer/lib/plugins/blocks.js:168:5)
    at emitTwo (events.js:106:13)
    at Client.emit (events.js:191:7)
    at Parser.<anonymous> (/root/node_modules/minecraft-protocol/dist/client.js:101:16)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at readableAddChunk (/root/node_modules/readable-stream/lib/_stream_readable.js:217:18)
    at Parser.Readable.push (/root/node_modules/readable-stream/lib/_stream_readable.js:176:10)
    at Parser.Transform.push (/root/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at Parser._transform (/root/node_modules/protodef/dist/serializer.js:88:14)

**Comment by rom1504** [comment]
Is it really 1.8 ? did you specify version:'1.8' ?

**Comment by 27therealone** [comment]
Yes i did

**Comment by rom1504** [comment]
What server is it ?
You put your bot code in /root ?

**Comment by 27therealone** [comment]
mc.aliacraft.net and yeah

**Comment by 27therealone** [comment]
Join and have the bot type /survival

**Comment by rom1504** [comment]
just tried it.
It just works.
Put `version:"1.8"` in the bot option
