### ISSUE TITLE
AssertionError: undefined == true on Minecraft Vanilla 1.11.2

### ISSUE THREAD

**Issue by zikeji** [PrismarineJS/mineflayer#499]
```
AssertionError: undefined == true
    at new Item (./node_modules/prismarine-item/index.js:22:10)
    at Function.Item.fromNotch (./node_modules/prismarine-item/index.js:61:10)
    at Client.<anonymous> (./node_modules/mineflayer/lib/plugins/entities.js:77:57)
    at emitTwo (events.js:106:13)
    at Client.emit (events.js:191:7)
    at Parser.<anonymous> (./node_modules/minecraft-protocol/dist/client.js:101:16)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at readableAddChunk (./node_modules/readable-stream/lib/_stream_readable.js:217:18)
    at Parser.Readable.push (./node_modules/readable-stream/lib/_stream_readable.js:176:10)
    at Parser.Transform.push (./node_modules/readable-stream/lib/_stream_transform.js:123:32)
```

Not exactly sure what's going on here. Used to happen sporadically and now it seems to happen everytime.

**Comment by rom1504** [comment]
@zikeji can you run `npm update` (that will update prismarine-item), try again and report the new error message ?

**Comment by rom1504** [comment]
Also, on which server do you get this ?

**Comment by zikeji** [comment]
was happening on play.seriousmc.com

Haven't been able to recreate this / haven't run into it again. My thought is it had something to do with the HolographicDisplays plugin.

**Comment by rom1504** [comment]
Reopen if you can reproduce
