### ISSUE TITLE
Validation error with spigotmc-1.11.2

### ISSUE THREAD

**Issue by kovzol** [PrismarineJS/mineflayer#500]
The newest npm version of mineflayer raises an error when starting a bot on spigotmc-1.11.2:
```
$ /mypath/node-v6.9.4-linux-x64/bin/node jumper.js localhost 26656 bo
You are using a pure-javascript implementation of RSA.
Your performance might be subpar. Please consider installing URSA
{
  "keyword": "oneOf",
  "dataPath": "",
  "schemaPath": "#/oneOf",
  "params": {},
  "message": "should match exactly one schema in oneOf",
  "schema": [
    {
      "enum": [
        "native"
      ]
    },
    {
      "$ref": "i8"
    },
    {
      "$ref": "u8"
    },
    {
      "$ref": "i16"
    },
    {
      "$ref": "u16"
    },
    {
      "$ref": "i32"
    },
    {
      "$ref": "u32"
    },
    {
      "$ref": "f32"
    },
    {
      "$ref": "f64"
    },
    {
      "$ref": "li8"
    },
    {
      "$ref": "lu8"
    },
    {
      "$ref": "li16"
    },
    {
      "$ref": "lu16"
    },
    {
      "$ref": "li32"
    },
    {
      "$ref": "lu32"
    },
    {
      "$ref": "lf32"
    },
    {
      "$ref": "lf64"
    },
    {
      "$ref": "i64"
    },
    {
      "$ref": "li64"
    },
    {
      "$ref": "u64"
    },
    {
      "$ref": "lu64"
    },
    {
      "$ref": "varint"
    },
    {
      "$ref": "bool"
    },
    {
      "$ref": "pstring"
    },
    {
      "$ref": "buffer"
    },
    {
      "$ref": "void"
    },
    {
      "$ref": "bitfield"
    },
    {
      "$ref": "cstring"
    },
    {
      "$ref": "mapper"
    },
    {
      "$ref": "array"
    },
    {
      "$ref": "count"
    },
    {
      "$ref": "container"
    },
    {
      "$ref": "switch"
    },
    {
      "$ref": "option"
    },
    {
      "$ref": "UUID"
    },
    {
      "$ref": "entityMetadataLoop"
    },
    {
      "$ref": "restBuffer"
    },
    {
      "$ref": "nbt"
    },
    {
      "$ref": "optionalNbt"
    },
    {
      "$ref": "string"
    },
    {
      "$ref": "slot"
    },
    {
      "$ref": "position"
    },
    {
      "$ref": "entityMetadataItem"
    },
    {
      "$ref": "entityMetadata"
    },
    {
      "$ref": "compressedNbt"
    },
    {
      "$ref": "registerarr"
    },
    {
      "$ref": "REGISTER"
    },
    {
      "$ref": "UNREGISTER"
    }
  ],
  "parentSchema": {
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "dataType",
    "oneOf": [
      {
        "enum": [
          "native"
        ]
      },
      {
        "$ref": "i8"
      },
      {
        "$ref": "u8"
      },
      {
        "$ref": "i16"
      },
      {
        "$ref": "u16"
      },
      {
        "$ref": "i32"
      },
      {
        "$ref": "u32"
      },
      {
        "$ref": "f32"
      },
      {
        "$ref": "f64"
      },
      {
        "$ref": "li8"
      },
      {
        "$ref": "lu8"
      },
      {
        "$ref": "li16"
      },
      {
        "$ref": "lu16"
      },
      {
        "$ref": "li32"
      },
      {
        "$ref": "lu32"
      },
      {
        "$ref": "lf32"
      },
      {
        "$ref": "lf64"
      },
      {
        "$ref": "i64"
      },
      {
        "$ref": "li64"
      },
      {
        "$ref": "u64"
      },
      {
        "$ref": "lu64"
      },
      {
        "$ref": "varint"
      },
      {
        "$ref": "bool"
      },
      {
        "$ref": "pstring"
      },
      {
        "$ref": "buffer"
      },
      {
        "$ref": "void"
      },
      {
        "$ref": "bitfield"
      },
      {
        "$ref": "cstring"
      },
      {
        "$ref": "mapper"
      },
      {
        "$ref": "array"
      },
      {
        "$ref": "count"
      },
      {
        "$ref": "container"
      },
      {
        "$ref": "switch"
      },
      {
        "$ref": "option"
      },
      {
        "$ref": "UUID"
      },
      {
        "$ref": "entityMetadataLoop"
      },
      {
        "$ref": "restBuffer"
      },
      {
        "$ref": "nbt"
      },
      {
        "$ref": "optionalNbt"
      },
      {
        "$ref": "string"
      },
      {
        "$ref": "slot"
      },
      {
        "$ref": "position"
      },
      {
        "$ref": "entityMetadataItem"
      },
      {
        "$ref": "entityMetadata"
      },
      {
        "$ref": "compressedNbt"
      },
      {
        "$ref": "registerarr"
      },
      {
        "$ref": "REGISTER"
      },
      {
        "$ref": "UNREGISTER"
      }
    ]
  },
  "data": [
    "i32",
    []
  ]
}
{
  "keyword": "enum",
  "dataPath": "",
  "schemaPath": "#/enum",
  "params": {
    "allowedValues": [
      "i32"
    ]
  },
  "message": "should be equal to one of the allowed values",
  "schema": [
    "i32"
  ],
  "parentSchema": {
    "enum": [
      "i32"
    ]
  },
  "data": [
    "i32",
    []
  ]
}
/mypath/node_modules/protodef-validator/index.js:96
        throw new Error("validation error");
        ^

Error: validation error
    at Validator.validateTypeGoingInside (/mypath/node_modules/protodef-validator/index.js:96:15)
    at Validator.validateType (/mypath/node_modules/protodef-validator/index.js:79:14)
    at ProtoDef.addType (/mypath/node_modules/protodef/dist/protodef.js:96:38)
    at Client.registerChannel (/mypath/node_modules/minecraft-protocol/src/client/pluginChannels.js:24:23)
    at Object.inject [as villager] (/mypath/node_modules/mineflayer/lib/plugins/villager.js:15:15)
    at Bot.connect (/mypath/node_modules/mineflayer/index.js:84:24)
    at Object.createBot (/mypath/node_modules/mineflayer/index.js:57:7)
    at Object.<anonymous> (/mypath/node_modules/mineflayer/examples/jumper.js:16:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```
Thanks in advance for any hints.

**Comment by rom1504** [comment]
Are you really using mineflayer 2.1.1 ? Oh and can you run npm update ?

**Comment by kovzol** [comment]
Thanks, it was an installation problem in my node configuration. Now it seems to be OK.
