### ISSUE TITLE
Error when starting bot

### ISSUE THREAD

**Issue by The-JC** [PrismarineJS/mineflayer#520]
When I start the bot with the example script it will throw this error: 

> Error: Deserialization error for play.toClient : Read error for name : 109 is not in the mappings value
    at ProtoDef.readMapper (C:\Users\Julian\Desktop\Bot\node_modules\protodef\src\datatypes\utils.js:27:31)
    at ProtoDef.read (C:\Users\Julian\Desktop\Bot\node_modules\protodef\src\protodef.js:127:29)
    at tryDoc (C:\Users\Julian\Desktop\Bot\node_modules\protodef\src\datatypes\structures.js:46:32)
    at tryCatch (C:\Users\Julian\Desktop\Bot\node_modules\protodef\src\utils.js:63:16)
    at tryDoc (C:\Users\Julian\Desktop\Bot\node_modules\protodef\src\utils.js:67:10)
    at typeArgs.forEach (C:\Users\Julian\Desktop\Bot\node_modules\protodef\src\datatypes\structures.js:45:5)
    at Array.forEach (native)
    at ProtoDef.readContainer (C:\Users\Julian\Desktop\Bot\node_modules\protodef\src\datatypes\structures.js:44:12)
    at ProtoDef.read (C:\Users\Julian\Desktop\Bot\node_modules\protodef\src\protodef.js:39:25)
    at ProtoDef.read (C:\Users\Julian\Desktop\Bot\node_modules\protodef\src\protodef.js:127:29)

It only occours when I join a Bungecord 1.8.x, 1.9.x, 1.10.x, 1.11x server, it works on a normal Spigot 1.11.2 Server.

**Comment by rom1504** [comment]
did you specify the version in the options of createBot ?

**Comment by The-JC** [comment]
No, how can I specify the version?

**Comment by rom1504** [comment]
version:"1.10" but it will now guess the version of the server if you don't specify it
