### ISSUE TITLE
108 is not in the mappings value

### ISSUE THREAD

**Issue by MrSonicMaster** [PrismarineJS/mineflayer#526]
Error: Deserialization error for play.toClient : Read error for name : 108 is not in the mappings value
    at ProtoDef.readMapper (C:\Program Files\nodejs\node_modules\protodef\src\datatypes\utils.js:27:31)
    at ProtoDef.read (C:\Program Files\nodejs\node_modules\protodef\src\protodef.js:127:29)
    at tryDoc (C:\Program Files\nodejs\node_modules\protodef\src\datatypes\structures.js:46:32)
    at tryCatch (C:\Program Files\nodejs\node_modules\protodef\src\utils.js:63:16)
    at tryDoc (C:\Program Files\nodejs\node_modules\protodef\src\utils.js:67:10)
    at typeArgs.forEach (C:\Program Files\nodejs\node_modules\protodef\src\datatypes\structures.js:45:5)
    at Array.forEach (native)
    at ProtoDef.readContainer (C:\Program Files\nodejs\node_modules\protodef\src\datatypes\structures.js:44:12)
    at ProtoDef.read (C:\Program Files\nodejs\node_modules\protodef\src\protodef.js:39:25)
    at ProtoDef.read (C:\Program Files\nodejs\node_modules\protodef\src\protodef.js:127:29)

**Comment by Gjum** [comment]
What code did you use to get this error? (I'm stuck on a similar one, maybe we can figure it out that way)

**Comment by rom1504** [comment]
Did you set the version (for example version:"1.11" in the createBot
options) ?

**Comment by MrSonicMaster** [comment]
Yes, I did set the server version, and it was the exact same version of minecraft I used to join the server

**Comment by MrSonicMaster** [comment]
Also I would like to point out it doesn't seem to be 100% of the time, only some of the time.

**Comment by rom1504** [comment]
What version is it ?

**Comment by MrSonicMaster** [comment]
1.11

**Comment by JonasFowl** [comment]
https://prismarinejs.github.io/minecraft-data/?d=protocol#play

I am getting similar errors, (e.g 9034) and they all come from the play.toClient sector.

**Comment by rom1504** [comment]
Also on 1.11 ?

**Comment by rom1504** [comment]
This error means the packet id has not been recognized.
There are 2 potential cause : 
* the packet id mapping of a protocol version is incorrect (a packet is missing or its id is wrongly assigned)
* the wrong protocol version is used

If you can determine which case you are in, it would help solve the problem ;)

**Comment by JonasFowl** [comment]
Case A) most probable.
I tested it with 1.11, 1,11,2 with a local server and it happened there. The (vanilla) server always used the exact same version.

**Comment by rom1504** [comment]
> I tested it with 1.11, 1,11,2 with a local server and it happened there.

When does it happen ?

**Comment by ViRb3** [comment]
#543

**Comment by jaideepsinghheer** [comment]
Similar error
```
Error: Deserialization error for play.toClient : Read error for name : 84 is not in the mappings value
    at ProtoDef.readMapper (D:\Node.JS\node_modules\protodef\src\datatypes\utils.js:27:31)
    at ProtoDef.read (D:\Node.JS\node_modules\protodef\src\protodef.js:127:29)
    at tryDoc (D:\Node.JS\node_modules\protodef\src\datatypes\structures.js:46:32)
    at tryCatch (D:\Node.JS\node_modules\protodef\src\utils.js:63:16)
    at tryDoc (D:\Node.JS\node_modules\protodef\src\utils.js:67:10)
    at typeArgs.forEach (D:\Node.JS\node_modules\protodef\src\datatypes\structures.js:45:5)
    at Array.forEach (native)
    at ProtoDef.readContainer (D:\Node.JS\node_modules\protodef\src\datatypes\structures.js:44:12)
    at ProtoDef.read (D:\Node.JS\node_modules\protodef\src\protodef.js:39:25)
    at ProtoDef.read (D:\Node.JS\node_modules\protodef\src\protodef.js:127:29)
```

**Comment by rom1504** [comment]
@jaideepsinghheer on which online server ? That completely depends on the server.

**Comment by jaideepsinghheer** [comment]
It's MCW 'playminecraftworld.nl'.

**Comment by jaideepsinghheer** [comment]
I also had to ping the server to prevent the `Please refresh your server list error.`

**Comment by rom1504** [comment]
might be related to https://github.com/PrismarineJS/node-minecraft-protocol/issues/336

**Comment by codingJWilliams** [comment]
+1 still an issue @rom1504 :-( I can reproduce locally. First start up any kind of server, preferably spigot. Connect. It works fine. Setup a bungeecord with just the one server on it and try to connect.
```
Error: Deserialization error for play.toClient : Read error for name : 108 is not in the mappings value
    at ProtoDef.readMapper (C:\Users\Jay\Desktop\Code\FacBot\node_modules\protodef\src\datatypes\utils.js:27:31)
    at ProtoDef.read (C:\Users\Jay\Desktop\Code\FacBot\node_modules\protodef\src\protodef.js:127:29)
    at tryDoc (C:\Users\Jay\Desktop\Code\FacBot\node_modules\protodef\src\datatypes\structures.js:46:32)
    at tryCatch (C:\Users\Jay\Desktop\Code\FacBot\node_modules\protodef\src\utils.js:63:16)
    at tryDoc (C:\Users\Jay\Desktop\Code\FacBot\node_modules\protodef\src\utils.js:67:10)
    at typeArgs.forEach (C:\Users\Jay\Desktop\Code\FacBot\node_modules\protodef\src\datatypes\structures.js:45:5)
    at Array.forEach (native)
    at ProtoDef.readContainer (C:\Users\Jay\Desktop\Code\FacBot\node_modules\protodef\src\datatypes\structures.js:44:12)
    at ProtoDef.read (C:\Users\Jay\Desktop\Code\FacBot\node_modules\protodef\src\protodef.js:39:25)
    at ProtoDef.read (C:\Users\Jay\Desktop\Code\FacBot\node_modules\protodef\src\protodef.js:127:29)
```

**Comment by codingJWilliams** [comment]
Please help this library has real promise

**Comment by rom1504** [comment]
would help to go through bungee code and figure out what custom packet it's sending

**Comment by roblabla** [comment]
BungeeCord shouldn't be sending any custom packets, it works perfectly well on a vanilla client.

**Comment by rom1504** [comment]
Does it mean
1. The vanilla client ignore custom packets
2. There's some splitting bug or other network bug that make it so the
packet id is not at the correct place in the buffer we're giving to the
parser : why don't the vanilla client get that too ?
3. ???

Regardless, I guess bungee cord is doing something special, whatever it is

**Comment by codingJWilliams** [comment]
Is there a bodge? A try-catch you can put in?
Anything lol. Even if it's bungee being a special little sausage it shouldn't be too hard to fix right?
Ignore my noobiness :P

**Comment by rom1504** [comment]
My point is it might be easier to look directly at bungee cord code to see
what's up instead of trying to guess from our end.
