### ISSUE TITLE
Unhandled 108 (0x6C) packet and chat

### ISSUE THREAD

**Issue by ViRb3** [PrismarineJS/mineflayer#543]
I get this exception most of the times I join a server. Mineflayer can also neither receive nor send chat messages.

Server version: 1.11.2
Server jar (most likely): CraftBukkit or Spigot

```
Exception has occurred: Error
Error: Deserialization error for play.toClient : Read error for name : 108 is not in the mappings value
    at ProtoDef.readMapper (c:\Users\Admin\Desktop\OculusBot\node_modules\protodef\src\datatypes\utils.js:27:31)
    at ProtoDef.read (c:\Users\Admin\Desktop\OculusBot\node_modules\protodef\src\protodef.js:127:29)
    at typeArgs.forEach.tryDoc (c:\Users\Admin\Desktop\OculusBot\node_modules\protodef\src\datatypes\structures.js:46:32)
    at tryCatch (c:\Users\Admin\Desktop\OculusBot\node_modules\protodef\src\utils.js:63:16)
    at tryDoc (c:\Users\Admin\Desktop\OculusBot\node_modules\protodef\src\utils.js:67:10)
    at typeArgs.forEach (c:\Users\Admin\Desktop\OculusBot\node_modules\protodef\src\datatypes\structures.js:45:5)
    at Array.forEach (native)
    at ProtoDef.readContainer (c:\Users\Admin\Desktop\OculusBot\node_modules\protodef\src\datatypes\structures.js:44:12)
    at ProtoDef.read (c:\Users\Admin\Desktop\OculusBot\node_modules\protodef\src\protodef.js:39:25)
    at ProtoDef.read (c:\Users\Admin\Desktop\OculusBot\node_modules\protodef\src\protodef.js:127:29)
```

**Comment by plexigras** [comment]
it dose.

**Comment by ViRb3** [comment]
> it does.

Then I guess something is wrong with the protocol handling.

**Comment by plexigras** [comment]
what dose `DEBUG="minecraft-protocol" node yourscript.js` say?

**Comment by ViRb3** [comment]
Could you please elaborate what you want me to do?

**Comment by Gjum** [comment]
run your script to reproduce the error, but this time enable the debug logging by setting the `DEBUG` environment variable to `"minecraft-protocol"`.

**Comment by rom1504** [comment]
```js

var customPackets={
  "1.11.2": {
    "play": {
      "toClient": {
        "types": {
          "packet_custom_name": [
            "container",[
              {
                "name": "custom",
                "type": "restBuffer"
              }
            ]
          ],
          "packet": [
            "container",
            [
              {
                "name": "name",
                "type": [
                  "mapper",
                  {
                    "type": "varint",
                    "mappings": {
                      "0x6C": "custom_name"
                    }
                  }
                ]
              },
              {
                "name": "params",
                "type": [
                  "switch",
                  {
                    "compareTo": "name",
                    "fields": {
                      "custom_name": "packet_custom_name"
                    }
                  }
                ]
              }
            ]
          ]
        }
      }
    }
  }
};
var bot = mineflayer.createBot({
  host: process.argv[2],
  port: parseInt(process.argv[3]),
  username: process.argv[4] ? process.argv[4] : "jumper",
  password: process.argv[5],
  verbose: true,
  version:"1.11.2",
  customPackets:customPackets
});
```

that "solves" it.
No idea what that 0x6C packet is.

**Comment by rom1504** [comment]
No idea why the vanilla client doesn't crash.

**Comment by rom1504** [comment]
Seems too specific. Reopen if needed
