### ISSUE TITLE
2.6.0 problem

### ISSUE THREAD

**Issue by ReveresPL** [PrismarineJS/mineflayer#561]
Day ago i downloaded mineflayer 2.5.0 and it is awesome, but today i installed mineflayer on my vps, but downloaded version is 2.6.0 and i have some bugs:
`function createBot (options = {}) {
                            ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/bot.js:2:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)`

When i remove = {} from options argument, and put
options = options || {} like in older version work fine, but is next problem:

`class Bot extends EventEmitter {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/bot.js:2:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)`

And I must using older version ;(

**Comment by rom1504** [comment]
you need a newer node.
