### ISSUE TITLE
Issue with ProtocolLib

### ISSUE THREAD

**Issue by hitzzaf** [PrismarineJS/mineflayer#585]
I saw something that said protocollib but i couldn't copy it fast enough due to the spam but, 
it's not even letting players join when in onlinemode so i disabled it for now.
protocol lib is spamming telnet when enabled with this error:
`:[15:21:01 WARN]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:java.lang.NullPointerException

at net.minecraft.server.v1_11_R1.NetworkManager.close(NetworkManager.java:247)

at net.minecraft.server.v1_11_R1.NetworkManager.channelInactive(NetworkManager.java:106)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)

at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)

at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)

at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)

at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:228)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)

at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)

at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)

at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)

at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)

at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144)

at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)

at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)

at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769)

at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:567)

at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)

at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)

at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)

at java.lang.Thread.run(Thread.java:748)

Read more: http://totalfreedom.boards.net/thread/54670/protocollib-error?page=1&scrollTo=626336#ixzz4qtZFpmkc`

**Comment by rom1504** [comment]
Is that related to mineflayer ?

**Comment by roblabla** [comment]
Doesn't look like it, and we need to create an account to access the link, which I certainly am *not* going to do.

@hitzzaf if you want help, please provide all necessary context through channels that don't require a login. Thank you.
