### ISSUE TITLE
TypeError: Serialization error for play.toServer.window_click.action

### ISSUE THREAD

**Issue by johnpyp** [PrismarineJS/mineflayer#598]
Getting a new error:

>  { TypeError: Serialization error for play.toServer.window_click.action : Write error for params.window_click.action : "value" argument is out of bounds
    at checkInt (buffer.js:1178:11)
    at Buffer.writeInt16BE (buffer.js:1357:5)
    at ProtoDef.writer (D:\epcmuser\Desktop\Coding\HTML & Web Development\Node\mineflayer-bot\node_modules\protodef\src\datatypes\numeric.js:76:25)
    at ProtoDef.write (D:\epcmuser\Desktop\Coding\HTML & Web Development\Node\mineflayer-bot\node_modules\protodef\src\protodef.js:135:29)
    at tryDoc (D:\epcmuser\Desktop\Coding\HTML & Web Development\Node\mineflayer-bot\node_modules\protodef\src\datatypes\structures.js:64:23)
    at tryCatch (D:\epcmuser\Desktop\Coding\HTML & Web Development\Node\mineflayer-bot\node_modules\protodef\src\utils.js:63:16)
    at tryDoc (D:\epcmuser\Desktop\Coding\HTML & Web Development\Node\mineflayer-bot\node_modules\protodef\src\utils.js:67:10)
    at typeArgs.reduce (D:\epcmuser\Desktop\Coding\HTML & Web Development\Node\mineflayer-bot\node_modules\protodef\src\datatypes\structures.js:64:5)
    at Array.reduce (<anonymous>)
    at ProtoDef.writeContainer (D:\epcmuser\Desktop\Coding\HTML & Web Development\Node\mineflayer-bot\node_modules\protodef\src\datatypes\structures.js:63:19) field: 'play.toServer.window_click.action' }

I have tampered with the mineflayer code twice to fix other issues:

First, I changed cb(err) to cb() in compression.js in NMP to fix unexpected end of line.

I also removed a line in buffer.js (I believe) that returned an out of sync error.

I have a feeling tampering with the code is causing more errors, but the bot won't work on my server I play on without the first fix and the buffer.js error I have no idea what it is.

My repository for my bot can be found here: https://github.com/johnpyp/mineflayer-bot

**Comment by rom1504** [comment]
For what Minecraft version do you get this error ?

**Comment by johnpyp** [comment]
The serialization error is only on 1.8.9. On 1.9, I didn't get the chunk.js error or the serialization error, but there were many other problems.

**Comment by johnpyp** [comment]
I've been testing it a little bit after resetting my node_modules and it hasn't done the serialization error yet again (quick-fixes already done).

I'll update again if I receive a serialization error or a different one.

**Comment by johnpyp** [comment]
Haven't been able to reproduce as of yet, I'll update if it does.

Any ideas on trying to disable exp gain?

**Comment by johnpyp** [comment]
Alright, so after long periods of time it seems to still occur.

Additionally, I am having an issue with using http-proxies. Here is my start page:
```
var express = require("express");
var app = new express();
const http = require("http");

const server = http.createServer(app);

var io = require("socket.io")(server);
const mineflayer = require("mineflayer");
const path = require("path");
var Convert = require("ansi-to-html");
var convert = new Convert();
var commands = require("./main/commands.js");

// var createBot = require("./main/createBot.js");
server.listen(3000, function() {
  console.log("Server listening at port %d", 3000);
});

app.get("/", function(req, res) {
  res.sendFile(path.join(__dirname, "/public/index.html"));
});

let presets = require("./profiles.json");

let bots = [];

(function next(i) {
  if (i < presets["default"]["accounts"].length) {
    setTimeout(() => {
      createBot(presets["default"]["accounts"][i]);
      i++;

      next(i);
    }, 500);
  }
})(0);
function createBot(data) {
  index = {};
  //Create bot
  index.bot = mineflayer.createBot({
    username: data["email"] || "dead",
    password: data["password"] || "dead",
    verbose: true,
    version: data["version"] || "1.8.9",
    connect: function(client) {
      const req = server.request({
        host: "104.160.17.199",
        port: 80,
        method: "CONNECT",
        path: data["host"] + ":" + parseInt(data["port"])
      });
      req.end();

      req.on("connect", function(res, stream) {
        client.setSocket(stream);
        client.emit("connect");
      });
    }
  });
```

The proxies I supposedly are using makes it so the bot does nothing. It says "server listening at port 3000" and nothing after that.

**Comment by roblabla** [comment]
For the proxies : Are you using public proxies ? If so, I can't really help you much. Try to set up your own proxy servers and check if those work. If they don't, tell me what proxy software and version you tried using so I can figure out what's wrong.

For the chunk errors : we probably have a mistake in the way we handle chunks. We'll need a TCP dump.

@rom1504 just had a silly thought : when we get a parse error in NMP, we should output a file on the disk with the raw buffer that failed to parse (after splitting phase) and ask users to upload that in the stacktrace message ^^.

**Comment by johnpyp** [comment]
They aren't public proxies. I bought "semi-dedicated" proxies from BuyProxies.org. Would it throw an error if they are incompatible? It just feels like I'm doing something wrong based on the fact it returns nothing.

The error I'm still getting isn't a chunk error, it is the serialization error.

**Comment by johnpyp** [comment]
Anyways, I bought new proxies, ones that support Connect and can be socks or http. I've tried both methods you've mentioned for proxies extensively with neither of them working. 

The "connect" method seems to just not trigger correctly. The proxy will go as far as `client.emit("connect")` and even trigger the connect event, but nothing will work past that.

The stream method with a socks5 proxy hasn't worked either. I've tried multiple different socks5 proxy npm modules to try to accomplish the same thing and none of them work, here is an error I get when trying to use [socks](https://github.com/JoshGlazebrook/socks):

```
 [14/10/2017 22:16:16] [LOG]   Server listening at port 3000
[14/10/2017 22:16:16] [LOG]   New Socket Connection
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:25565
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
```

I am trying to connect to a remote server like this:
```
client = mineflayer.createBot({
    stream: Socks.createConnection(
      {
        proxy: {
          ipaddress: "[redacted]",
          port: [redacted],
          type: 5,
          authentication: {
            username: "[redacted]",
            password: "[redacted]"
          },
          command: "connect"
        },
        target: {
          host: "pvp.desteria.net",
          port: 25565
        }
      },
      function(err, socket, info) {
        if (err) {
          console.log(err);
        }
      }
    ),

    username: data["email"] || "dead",
    password: data["password"] || "dead",
    version: data["version"] || "1.8.9"
  });
```

**Comment by roblabla** [comment]
`Error: connect ECONNREFUSED 127.0.0.1:25565` means it failed to connect to the server (nothing is listening on that port). I am going to guess that you're trying to connect to a socks proxy that doesn't exist ?

**Comment by rom1504** [comment]
There is a socks 5 proxy example now, you should do what it does. Stream
option won't work , you need connect option.

See
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_socks_proxy/client_socks_proxy.js

That definitely works for self hosted proxy, that's how I tested it.

It should work for external proxies too.

**Comment by rom1504** [comment]
proxy problem is fixed.

Are you sure about these 1.9 issues ? Do they also happen in 1.12 ?

**Comment by johnpyp** [comment]
I've only tested 1.9 vs 1.8.9. Also, which proxy did you fix? Socks or
http? Which method of implenentation?

**Comment by rom1504** [comment]
I didn't fix anything, it was already working.
I meant in this issue I gave you the solution, so that part of the issue is fixed.

> Player doesn't pick up items or exp.

Seems highly unlikely since our tests check that, I bet you're testing on some non vanilla ?

**Comment by Vxrize** [comment]
> > There is a socks 5 proxy example now, you should do what it does. Stream
> option won't work , you need connect option.
> 
> See
> https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_socks_proxy/client_socks_proxy.js
> 
> That definitely works for self hosted proxy, that's how I tested it.
> 
> It should work for external proxies too.

I'm having difficulties understanding this code, could you maybe try to explain what it does or show an example with Mineflayer? In the example you have implemented the code directly at the part where you create a new client using the minecraft-protocol library (mc.createClient). 

Does this mean I would have to change the source of Mineflayer to use proxies?

Is there a way to connect using a proxy in the mineflayer.createBot() function? If yes, could you quickly explain how it is done or maybe show an example?
