### ISSUE TITLE
Error: Deserialization error for play.toClient : Read error for name : 123 is no t in the mappings value

### ISSUE THREAD

**Issue by FaZeMelon** [PrismarineJS/mineflayer#603]
Edit:
New error:

```

C:\Users\Melon\Pictures\Bot\mineflayer-master\examples>node melonBot.js play.t
otalfreedom.me 25565 MelonBot
melonbot@melon:~$ events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Deserialization error for play.toClient : Read error for name : 107127 is
 not in the mappings value
    at ProtoDef.readMapper (C:\Users\Melon\Pictures\Bot\node_modules\protodef\
src\datatypes\utils.js:27:31)
    at ProtoDef.read (C:\Users\Melon\Pictures\Bot\node_modules\protodef\src\pr
otodef.js:127:29)
    at tryDoc (C:\Users\Melon\Pictures\Bot\node_modules\protodef\src\datatypes
\structures.js:46:32)
    at tryCatch (C:\Users\Melon\Pictures\Bot\node_modules\protodef\src\utils.j
s:63:16)
    at tryDoc (C:\Users\Melon\Pictures\Bot\node_modules\protodef\src\utils.js:
67:10)
    at typeArgs.forEach (C:\Users\Melon\Pictures\Bot\node_modules\protodef\src
\datatypes\structures.js:45:5)
    at Array.forEach (native)
    at ProtoDef.readContainer (C:\Users\Melon\Pictures\Bot\node_modules\protod
ef\src\datatypes\structures.js:44:12)
    at ProtoDef.read (C:\Users\Melon\Pictures\Bot\node_modules\protodef\src\pr
otodef.js:39:25)
    at ProtoDef.read (C:\Users\Melon\Pictures\Bot\node_modules\protodef\src\pr
otodef.js:127:29)

C:\Users\Melon\Pictures\Bot\mineflayer-master\examples>pause
Press any key to continue . . .

```

**Comment by rom1504** [comment]
Which server which version ?

**Comment by FaZeMelon** [comment]
Play.totalfreedom.me > 1.12.2

**Comment by FaZeMelon** [comment]
I don't know if you saw my previous message but it was TotalFreedom and
1.12.2. I don't think it's the version since I've used the bot and it has
worked on the same server and the same version. I doubt that it was
anything on my side since I did reinstall mineflayer.

**Comment by ThierryKamber** [comment]
Same issue here.
Tested with two servers:

1. CraftBukkit version git-Spigot-5695bca-53fccdf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Bot connects and then works normally for a couple of seconds and then disconnects with the error above.

2. Paper version git-Paper-1244 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
(behind BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:8d49424:1273 by md_5)
Bot connects and doesn't execute any actions and gets disconnected almost instantly.

**Comment by ItzRaiin94** [comment]
Ok, I've seemed to represent the issue presented by the OP.
[Console Log Here](https://i.imgur.com/FiXOu4W.png)
The error seems to be related to users on the server using particles relating to a plugin called "PlayerParticles". I managed to crash my bot using them and got a similar error. I can only assume this is the error which was presented to the OP.

Node version: v6.11.2
NPM version: v3.10.10

**Comment by plexigras** [comment]
do you guys have the same issue when just using node-minecraft-protocol?

**Comment by ThierryKamber** [comment]
None of the servers I have tested it with, had that plugin (or any other particle-related plugins) installed.
I'm currently not able to do any tests, but will try it with nmp once I'm able to.

**Comment by ThierryKamber** [comment]
Sorry for the (very) late reply. I've just tested the client_echo example and am getting a similar error:

```
connected
C:\Users\ThiKam\Downloads\node-minecraft-protocol-master\src\transforms\framing.js:76
          throw e;
          ^

Error: Deserialization error for play.toClient : Chunk size is
    at FullPacketParser._transform (C:\Users\ThiKam\Downloads\node-minecraft-protocol-master\node_modules\protodef\src\serializer.js
:78:15)
    at FullPacketParser.Transform._read (C:\Users\ThiKam\Downloads\node-minecraft-protocol-master\node_modules\readable-stream\lib\_
stream_transform.js:184:10)
    at FullPacketParser.Transform._write (C:\Users\ThiKam\Downloads\node-minecraft-protocol-master\node_modules\readable-stream\lib\
_stream_transform.js:172:83)
    at doWrite (C:\Users\ThiKam\Downloads\node-minecraft-protocol-master\node_modules\readable-stream\lib\_stream_writable.js:418:64
)
    at writeOrBuffer (C:\Users\ThiKam\Downloads\node-minecraft-protocol-master\node_modules\readable-stream\lib\_stream_writable.js:
407:5)
    at FullPacketParser.Writable.write (C:\Users\ThiKam\Downloads\node-minecraft-protocol-master\node_modules\readable-stream\lib\_s
tream_writable.js:334:11)
    at Decompressor.ondata (C:\Users\ThiKam\Downloads\node-minecraft-protocol-master\node_modules\readable-stream\lib\_stream_readab
le.js:619:20)
    at emitOne (events.js:116:13)
    at Decompressor.emit (events.js:211:7)
    at addChunk (C:\Users\ThiKam\Downloads\node-minecraft-protocol-master\node_modules\readable-stream\lib\_stream_readable.js:291:1
2)
```

**Comment by FaZeMelon** [comment]
I was getting the error from my own client that I coded. The problem arises
with certain particles, and that makes servers with particles functionally
useless.

**Comment by rom1504** [comment]
reopen if you still have this issue

**Comment by moom0o** [comment]
still have the issue, 1.15.2 mineflayer
Error: Deserialization error for play.toClient.declare_recipes.recipes.0.data : Read error for params.declare_recipes.recipes.0.data : crafting_shapeless has no associated fieldInfo in switch

earthmc.net

**Comment by rom1504** [comment]
Ok weird, I'll have a look

**Comment by skyrawr** [comment]
Error: Deserialization error for play.toClient.entity_metadata.metadata.value : Read error for params.entity_metadata.metadata.value : -84 has no associated fieldInfo in switch

**Comment by wvffle** [comment]
@skyrawr this is pretty much another error, please create new issue for that

**Comment by duxeyo** [comment]
same issue, proxy broke after defending a raid, 1.15.2.

**Comment by shadowdevfr** [comment]
Same issue.

**Comment by rom1504** [comment]
Post the full error.
"Same issue" is not solvable

**Comment by rom1504** [comment]
too random
