### ISSUE TITLE
Deserialization error for play.toClient : play is not defined.

### ISSUE THREAD

**Issue by 160Productions** [PrismarineJS/mineflayer#641]
Every time I try to connect my bot to a server, it just returns this error:

ERROR: ReferenceError: Deserialization error for play.toClient : play is not defined
{ ReferenceError: Deserialization error for play.toClient : play is not defined
    at Bot.<anonymous> (C:\Users\callu\Downloads\Workshop\2018\MAIN_PROJECTS\160System\160SYSTEM\dev\JS\BridgeBOT-dc4\main.js:64:2)
    at emitNone (events.js:86:13)
    at Bot.emit (events.js:188:7)
    at Client.bot._client.on (C:\Users\callu\Downloads\Workshop\2018\MAIN_PROJECTS\160System\160SYSTEM\dev\JS\BridgeBOT-dc4\node_modules\mineflayer\lib\plugins\health.js:15:9)
    at emitTwo (events.js:106:13)
    at Client.emit (events.js:194:7)
    at FullPacketParser.deserializer.on (C:\Users\callu\Downloads\Workshop\2018\MAIN_PROJECTS\160System\160SYSTEM\dev\JS\BridgeBOT-dc4\node_modules\minecraft-protocol\src\client.js:103:12)
    at emitOne (events.js:96:13)
    at FullPacketParser.emit (events.js:191:7)
    at addChunk (C:\Users\callu\Downloads\Workshop\2018\MAIN_PROJECTS\160System\160SYSTEM\dev\JS\BridgeBOT-dc4\node_modules\readable-stream\lib\_stream_readable.js:284:12)
    at readableAddChunk (C:\Users\callu\Downloads\Workshop\2018\MAIN_PROJECTS\160System\160SYSTEM\dev\JS\BridgeBOT-dc4\node_modules\readable-stream\lib\_stream_readable.js:271:11) field: 'play.toClient' }
Error (Count:1)

It used to work fine, on the same server that I've always been using it on, and I used to get the same error, but only when the bot tried to use mineflayer-navigate to navigate to a user that wasn't on the bots radar in mineflayer-radar, but I added error handling for that and made it just return an "I can't see you." message in chat. I've updated to the latest version of Mineflayer, and still the same error appears!

**Comment by RONTheCookie** [comment]
can reproduce

**Comment by plexigras** [comment]
what is your script and full log?

if you are on linux or mac you should be able to run `DEBUG="minecraft-protocol" node mybot.js > log.txt` to pipe the debug log into log.txt

**Comment by RONTheCookie** [comment]
I did it with the echo example in the readme, here's my log https://hastebin.com/gugiwowiji.sm
Also it seems to only work and not say invalid uname & passw about half of the time.

**Comment by rom1504** [comment]
The "chunk size is" is very weird. Guess there's a bug in the error logging.

**Comment by RONTheCookie** [comment]
Any way to get around this for now?

**Comment by rom1504** [comment]
Yes, use a vanilla server.

Second option is try to fix it.
Figures it why the error message is cut then use the full error message to
have a better idea how to fix it.

**Comment by RONTheCookie** [comment]
Not really my server so I can't do that.

**Comment by RONTheCookie** [comment]
Now I sometimes get `Error: Invalid credentials. Invalid username or password.` , yay!

**Comment by rom1504** [comment]
If you connect too many times you get banned temporarily by the Mojang
server.
You can use the session storing functionality to avoid that.

**Comment by RONTheCookie** [comment]
how'd you do that

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by plexigras** [comment]
you can get the session by doing `bot._client.on('session', session => ... )` and you can provide session as a option when creating a bot/client.

**Comment by RONTheCookie** [comment]
alright

**Comment by RONTheCookie** [comment]
got it working, thanks everyone
