### ISSUE TITLE
Invalid Username and Password

### ISSUE THREAD

**Issue by RileyDatLord** [PrismarineJS/mineflayer#649]
I am getting the "Invalid Username and Password" error as I put in the correct details, I am using VSC so I am self hosting, not on a vps.

**Comment by RileyDatLord** [comment]
Full Error:
`Error: Invalid credentials. Invalid username or password.
    at C:\Users\Riley\Desktop\code\node_modules\yggdrasil\lib\utils.js:33:10
    at IncomingMessage.<anonymous> (C:\Users\Riley\Desktop\code\node_modules\phin\lib\phin.compiled.js:1:2111)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)`

Server: `minehut.com` Port: `25565`

**Comment by Vrganj** [comment]
Have you found a solution?

**Comment by GunnerBasil** [comment]
I have the same problem. sorry for necroposting.
