### ISSUE TITLE
cant connect to a minecraft server

### ISSUE THREAD

**Issue by BurnGemios** [PrismarineJS/mineflayer#652]
i have this error and bot stop when i start it: ### C:\Users\Burn\Desktop\mineflayer>node index.js
Bots Starting...
Bot Spawned...
C:\Users\Burn\Desktop\mineflayer\node_modules\minecraft-protocol\src\transforms\framing.js:76
          throw e;
          ^

Error: Deserialization error for play.toClient : Chunk size is
    at FullPacketParser._transform (C:\Users\Burn\Desktop\mineflayer\node_modules\protodef\src\serializer.js:78:15)
    at FullPacketParser.Transform._read (C:\Users\Burn\Desktop\mineflayer\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at FullPacketParser.Transform._write (C:\Users\Burn\Desktop\mineflayer\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\Users\Burn\Desktop\mineflayer\node_modules\readable-stream\lib\_stream_writable.js:418:64)
    at writeOrBuffer (C:\Users\Burn\Desktop\mineflayer\node_modules\readable-stream\lib\_stream_writable.js:407:5)
    at FullPacketParser.Writable.write (C:\Users\Burn\Desktop\mineflayer\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at Decompressor.ondata (C:\Users\Burn\Desktop\mineflayer\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at Decompressor.emit (events.js:180:13)
    at addChunk (C:\Users\Burn\Desktop\mineflayer\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\Burn\Desktop\mineflayer\node_modules\readable-stream\lib\_stream_readable.js:278:11)
Emitted 'error' event at:
    at Client.self._client.on (C:\Users\Burn\Desktop\mineflayer\node_modules\mineflayer\index.js:89:12)
    at Client.emit (events.js:180:13)
    at FullPacketParser.deserializer.on (C:\Users\Burn\Desktop\mineflayer\node_modules\minecraft-protocol\src\client.js:92:12)
    at FullPacketParser.emit (events.js:185:15)
    at onwriteError (C:\Users\Burn\Desktop\mineflayer\node_modules\readable-stream\lib\_stream_writable.js:433:12)
    at onwrite (C:\Users\Burn\Desktop\mineflayer\node_modules\readable-stream\lib\_stream_writable.js:460:11)
    at WritableState.onwrite (C:\Users\Burn\Desktop\mineflayer\node_modules\readable-stream\lib\_stream_writable.js:180:5)
    at FullPacketParser.afterTransform (C:\Users\Burn\Desktop\mineflayer\node_modules\readable-stream\lib\_stream_transform.js:93:3)
    at FullPacketParser._transform (C:\Users\Burn\Desktop\mineflayer\node_modules\protodef\src\serializer.js:86:7)
    at FullPacketParser.Transform._read (C:\Users\Burn\Desktop\mineflayer\node_modules\readable-stream\lib\_stream_transform.js:184:10)

**Comment by rom1504** [comment]
see https://github.com/PrismarineJS/node-minecraft-protocol/issues/532
