### ISSUE TITLE
support 1.12.2

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/mineflayer#660]
* [x] check issues for bug in 1.12.2
* [x] fix stuff about ping checkout time

**Comment by duralakun** [comment]
I once wrote a bot (the code is really messy), for an online server. The server uses some plugins, but the bot still works and i can login. Now i updated (reinstalled mineflayer with npm in a different folder) and copied the bot.js (that i wrote) to the new modules. I can join my local server (v 1.12.2) but i can no longer join the online server (v 1.8.x-1.12.x). It crashes when it tries to join:
```
/node_modules/minecraft-protocol/src/transforms/framing.js:76
          throw e;
          ^

Error: Deserialization error for play.toClient : Chunk size is
    at FullPacketParser._transform (/node_modules/protodef/src/serializer.js:78:15)
    at FullPacketParser.Transform._read (/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at FullPacketParser.Transform._write (/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at FullPacketParser.Writable.write (/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Decompressor.ondata (/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at emitOne (events.js:116:13)
    at Decompressor.emit (events.js:211:7)
    at addChunk (/node_modules/readable-stream/lib/_stream_readable.js:291:12)

```
Is it supposed to be backwards compatible? Do i have to change a version number somewhere?
I could try to download a server with the same version and then do the test locally to see if i get the same results. The bot still works on the same server if i use the outdated node modules that i still have on my computer.

**Comment by rom1504** [comment]
done
