### ISSUE TITLE
Error causing bot to crash

### ISSUE THREAD

**Issue by crzassassin** [PrismarineJS/mineflayer#677]
TypeError: Cannot read property 'id' of undefined
    at confirmTransaction (C:\Users\Aiden\Desktop\testing\node_modules\mineflayer\lib\plugins\inventory.js:390:21)
    at Client.bot._client.on (C:\Users\Aiden\Desktop\testing\node_modules\mineflayer\lib\plugins\inventory.js:502:5)
    at Client.emit (events.js:182:13)
    at FullPacketParser.deserializer.on (C:\Users\Aiden\Desktop\testing\node_modules\minecraft-protocol\src\client.js:81:12)
    at FullPacketParser.emit (events.js:182:13)
    at addChunk (C:\Users\Aiden\Desktop\testing\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\Aiden\Desktop\testing\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at FullPacketParser.Readable.push (C:\Users\Aiden\Desktop\testing\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at FullPacketParser.Transform.push (C:\Users\Aiden\Desktop\testing\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at FullPacketParser._transform (C:\Users\Aiden\Desktop\testing\node_modules\protodef\src\serializer.js:85:10)

**Comment by rom1504** [comment]
Any clue when that happens ? (how to reproduce)

**Comment by crzassassin** [comment]
well, make it join a 1.12.2 server, and throw an item at it.

**Comment by rom1504** [comment]
What kind of 1.12.2 server ?
Vanilla ? Spigot ?

**Comment by crzassassin** [comment]
spigot specifically paper 1.12.2

**Comment by rom1504** [comment]
now fixed
