### ISSUE TITLE
Getting an error while doing a basic example.

### ISSUE THREAD

**Issue by SaltySpark** [PrismarineJS/mineflayer#699]
If you are reporting a bug please report on these points :

* what you want to do (the objective in english)
just trying to get the bot started and the chat event running.
* what you tried (the code)
```
const Discord = require('discord.js');
const chalk = require('chalk');
const ddiff = require('return-deep-diff');
const fs = require('graceful-fs');
const mineflayer = require('mineflayer');

const sparkMcClient = new mineflayer.createBot({
    host: 'play.sadonmc.com',
    username: 'myUsername',
    password: 'mypassword',
    version: "1.8",
    });

const sparkClient = new Discord.Client();

sparkMcClient.on('chat', (username, message) => {
    if (username === sparkMcClient.username) return
    console.log(message);
  })
```
* what `happened`
```
{ Error: querySrv ENOTFOUND _minecraft._tcp.play.sadonmc.com
    at errnoException (dns.js:50:10)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:238:19)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'querySrv',
  hostname: '_minecraft._tcp.play.sadonmc.com' }
```
* what you expected to happen
Just trying to get the bot started
In particular it will be useful to provide these informations :

* what happens when using a mineflayer example?
I'm using the echo example, just trying to see if I can get this bot to connect.
* what happens when using a node-minecraft-protocol example?
* what mineflayer version?
2.7.3
* what server version?
The server only accepts 1.8 & higher.
* which server? (spigot, paper, vanilla, any particular plugins ?)
* what's the output of DEBUG="minecraft-protocol" node your_bot.js ?
* what's the error msg?
* what script is used?

**Comment by SaltySpark** [comment]
```
{ Error: querySrv ESERVFAIL _minecraft._tcp.play.hypixel.net
    at errnoException (dns.js:50:10)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:238:19)
  code: 'ESERVFAIL',
  errno: 'ESERVFAIL',
  syscall: 'querySrv',
  hostname: '_minecraft._tcp.play.hypixel.net' }
```

Getting this error when I tried it on hypixel.

**Comment by SaltySpark** [comment]
Still not solved, keeps giving the same error.

**Comment by plexigras** [comment]
you could try setting the port to `25565`

**Comment by rom1504** [comment]
We probably should remove the code trying to use that _tcp thing. Not sure what it even tries to do.

**Comment by roblabla** [comment]
It's for SRV DNS records support. Minecraft does it too, we shouldn't remove it.

**Comment by SaltySpark** [comment]
So other then setting the port to 2556, which is should do by default, what should I do?

**Comment by SaltySpark** [comment]
I've tried changing the server, seems like none work.

**Comment by SaltySpark** [comment]
There is no tcp.js

Really confused on what to do, please help.

**Comment by rom1504** [comment]
It's in node-minecraft-protocol

**Comment by rom1504** [comment]
now fixed, just run npm update
