### ISSUE TITLE
Assertion errors for items when joining a forge (sponge api 7) server

### ISSUE THREAD

**Issue by JSEverything** [PrismarineJS/mineflayer#700]
When trying to connect to a forge (1.12.2 - forge 14.23.3.2670) server (sponge api 7) mineflayer throws an assertion error after joining (join message appears ingame):
```
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: item with id 8342 not found
    at new Item (C:\Users\Pawii\Desktop\bot\node_modules\prismarine-item\index.js:22:10)
    at Function.Item.fromNotch (C:\Users\Pawii\Desktop\bot\node_modules\prismarine-item\index.js:61:10)
    at Client.bot._client.on (C:\Users\Pawii\Desktop\bot\node_modules\mineflayer\lib\plugins\inventory.js:559:19)
    at emitTwo (events.js:126:13)
    at Client.emit (events.js:214:7)
    at FullPacketParser.deserializer.on (C:\Users\Pawii\Desktop\bot\node_modules\minecraft-protocol\src\client.js:81:12)
    at emitOne (events.js:116:13)
    at FullPacketParser.emit (events.js:211:7)
    at addChunk (C:\Users\Pawii\Desktop\bot\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\Pawii\Desktop\bot\node_modules\readable-stream\lib\_stream_readable.js:278:11)
```
Code: 
```js
var mineflayer = require('mineflayer');
var autoVersionForge = require('minecraft-protocol-forge').autoVersionForge;

var bot = mineflayer.createBot({
  version: false,
  host: "192.168.1.13",
  port: 25565,
  username: "bot1"
});
autoVersionForge(bot._client);
```

Server is in offline-mode and it's working on just minecraft-protocol with forge plugin.
Mineflayer version: 2.7.3
Note: I tried finding the item in JEI but I couldn't find it, modpack: Crimson Skies 1.2.4.2
Expected result: it should connect and stay connected without crashing the process

**Comment by Pawiczekk** [comment]
I think i found a cause of the problem and a workaround, item with id 8342 was the manual for the mod One Probe which every player gets when spawning in for the first time, temporary workaround would be to not allow the player have modded items in inventory.

**Comment by rom1504** [comment]
I guess we could allow unknown item if that's a thing

**Comment by Pawiczekk** [comment]
Even assuming a max stack size for the item to be 64 and storing it with only it's ID instead the name would be good enough, that could be manually edited if needed. Still, the best option in my opinion would be either to get the item's details from the server (if possible) or make a forge mod that would create the database for minecraft-data.

**Comment by extremeheat** [comment]
Was fixed in prismarine-item
