### ISSUE TITLE
can't connect to server

### ISSUE THREAD

**Issue by theonlygusti** [PrismarineJS/mineflayer#737]
Getting error

```
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 173.236.67.31:25566
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1170:14)
Emitted 'error' event at:
    at Client.self._client.on (/project/node_modules/.registry.npmjs.org/mineflayer/2.7.3/node_modules/mineflayer/index.js:90:12)
    at Client.emit (events.js:180:13)
    at Socket.onFatalError (/project/node_modules/.registry.npmjs.org/minecraft-protocol/1.8.2/node_modules/minecraft-protocol/src/client.js:139:12)
    at Socket.emit (events.js:185:15)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)```

I am just trying to run this:

```js
const mineflayer = require('mineflayer')

const bot = mineflayer.createBot({
  host: process.env.HOST, // us.mineplex.com
  port: parseInt(process.env.PORT), // 25565
  username: process.env.USER, // I can log into the mojang site using this username
  password: process.env.PASS, // and password.
  version: process.env.VERSION, // "1.8"
  verbose: true
});

bot.chatAddPattern(/^.+$/, 'chat', 'testing chat');

bot.on('chat', (username, message, translate, jsonMsg, matches) => {
  console.log('Chat received!');
  console.log(jsonMsg);
});

bot.on('actionbar', (jsonMsg) => {
  console.log('ActionBar received!');
  console.log(jsonMsg);
});```

**Comment by rom1504** [comment]
Looks like your host and port are wrong

**Comment by theonlygusti** [comment]
@rom1504 how? us.mineplex.com:25565 is a server I can join from a normal client

**Comment by theonlygusti** [comment]
nvm you're right. Can close this. I typoed and had 25566 in my actual code.
