### ISSUE TITLE
Ignore chunk errors

### ISSUE THREAD

**Issue by theonlygusti** [PrismarineJS/mineflayer#745]
```
prismarine-chunk/src/pc/1.8/chunk.js:182
    if (data.length !== SECTION_SIZE * chunkCount + w * l) { throw (new Error(`Data buffer not correct size (was ${data.length}, expected ${BUFFER_SIZE})`)) }
                                                             ^

Error: Data buffer not correct size (was 24576, expected 196864)
```

How can I just continue running the bot if I get this error?

**Comment by rom1504** [comment]
you could do a PR to prismarine-chunk for this, but I'm not convinced that
mineflayer would still work if you ignore these errors

**Comment by theonlygusti** [comment]
@rom1504 I actually have no idea what causes these errors.

I had just assumed they can be ignored because all my GUI clients (and even other command line ones like ORelio's C# Minecraft-Console-Client) can all connect to these servers without crashing.

**Comment by rom1504** [comment]
Ok, try it

**Comment by derjp** [comment]
What actually causes this error to happen?
Does anyone know? I'm guessing non-vanilla servers sending modified packets, but as said before other libraries/clients don't have that problem.

**Comment by rom1504** [comment]
what other libraries/clients are you talking about ?

**Comment by lbarthon** [comment]
I'm having the same problem rn after 15/20 minutes :/

```0|script   | Error: Data buffer not correct size (was 24576, expected 24832)
0|script   |     at Chunk.load (/home/admin/BotMc/node_modules/prismarine-chunk/src/pc/1.8/chunk.js:181:69)
0|script   |     at addColumn (/home/admin/BotMc/node_modules/mineflayer/lib/plugins/blocks.js:47:14)
0|script   |     at Client.bot._client.on (/home/admin/BotMc/node_modules/mineflayer/lib/plugins/blocks.js:172:5)
0|script   |     at Client.emit (events.js:197:13)
0|script   |     at FullPacketParser.deserializer.on (/home/admin/BotMc/node_modules/minecraft-protocol/src/client.js:82:12)
0|script   |     at FullPacketParser.emit (events.js:197:13)
0|script   |     at addChunk (/home/admin/BotMc/node_modules/readable-stream/lib/_stream_readable.js:297:12)
0|script   |     at readableAddChunk (/home/admin/BotMc/node_modules/readable-stream/lib/_stream_readable.js:279:11)
0|script   |     at FullPacketParser.Readable.push (/home/admin/BotMc/node_modules/readable-stream/lib/_stream_readable.js:240:10)
0|script   |     at FullPacketParser.Transform.push (/home/admin/BotMc/node_modules/readable-stream/lib/_stream_transform.js:139:32)```

**Comment by rom1504** [comment]
try using a server without bug

**Comment by rom1504** [comment]
now fixed
