### ISSUE TITLE
SizeOf error for name : chat is not in the mappings value

### ISSUE THREAD

**Issue by Wqrld** [PrismarineJS/mineflayer#754]
Newest mineflayer from npm
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Serialization error for handshaking.toServer : SizeOf error for name : chat is not in the mappings value
    at ProtoDef.sizeOfMapper (/root/bot/node_modules/protodef/src/datatypes/utils.js:58:31)
    at ProtoDef.sizeOf (/root/bot/node_modules/protodef/src/protodef.js:145:31)
    at tryDoc (/root/bot/node_modules/protodef/src/datatypes/structures.js:72:30)
    at tryCatch (/root/bot/node_modules/protodef/src/utils.js:63:16)
    at tryDoc (/root/bot/node_modules/protodef/src/utils.js:67:10)
    at typeArgs.reduce (/root/bot/node_modules/protodef/src/datatypes/structures.js:72:12)
    at Array.reduce (<anonymous>)
    at ProtoDef.sizeOfContainer (/root/bot/node_modules/protodef/src/datatypes/structures.js:71:25)
    at ProtoDef.sizeOf (/root/bot/node_modules/protodef/src/protodef.js:44:27)
    at ProtoDef.sizeOf (/root/bot/node_modules/protodef/src/protodef.js:145:31)
```

Getting this when starting my bot, it seems to be happening on all mc versions for the bot.
happens when joining a bungeecord (oxiuspvp, 145.239.150.154)

**Comment by Wqrld** [comment]
```
        try {
            console.log(account.name);
            botnames[account.name] = mineflayer.createBot({
                host: config.ip,
                port: config.port,
                username: account.username,
                version: "1.12.2",
                password: account.password
            })


/*            setTimeout(function() {
                botnames[account.name].chat(config.joincommand);
                console.log(`spawned and did ${config.joincommand}`)
            }, 3000);
*/
            console.log(account.name + " init")
            botigns.push(account.name);
            bots.push(botnames[account.name]);
        } catch (err) {
            console.log(err);
        }
```
```
setTimeout(function() {
                botnames[account.name].chat(config.joincommand);
                console.log(`spawned and did ${config.joincommand}`)
            }, 3000);
```
was causing the issue, not sure why though
