### ISSUE TITLE
Redundant "Version unsupported" exception

### ISSUE THREAD

**Issue by mspaintmsi** [PrismarineJS/mineflayer#773]
Upon finishing a simple script, when I tried to execute it I was informed that the Minecraft version for the server is unsupported, which, while correct, shouldn't matter, because the server accepts clients from 1.7.2 up to 1.13.2.
Is there a way to ignore the exception without messy changes to the original code?
```
/home/mspaintmsi/Unixej_Bots/Mineflayer/node_modules/minecraft-protocol/src/transforms/framing.js:66
          } else { throw e }
                   ^

Error: Version 1.13.2 is not supported.
    at Client.next (/home/mspaintmsi/Unixej_Bots/Mineflayer/node_modules/mineflayer/index.js:100:15)
    at Object.onceWrapper (events.js:285:13)
    at Client.emit (events.js:197:13)
    at /home/mspaintmsi/Unixej_Bots/Mineflayer/node_modules/minecraft-protocol/src/client/autoVersion.js:53:12
    at Client.<anonymous> (/home/mspaintmsi/Unixej_Bots/Mineflayer/node_modules/minecraft-protocol/src/ping.js:28:7)
    at Object.onceWrapper (events.js:285:13)
    at Client.emit (events.js:197:13)
    at FullPacketParser.deserializer.on (/home/mspaintmsi/Unixej_Bots/Mineflayer/node_modules/minecraft-protocol/src/client.js:82:12)
    at FullPacketParser.emit (events.js:197:13)
    at addChunk (/home/mspaintmsi/Unixej_Bots/Mineflayer/node_modules/readable-stream/lib/_stream_readable.js:296:12)`

**Comment by rom1504** [comment]
1.13 and 1.13.2 are not supported (yet ?)
