### ISSUE TITLE
TypeError: absoluteVector.floored is not a function

### ISSUE THREAD

**Issue by KenWa51** [PrismarineJS/mineflayer#776]
C:\Users\kenny\node_modules\mineflayer\lib\location.js:7
  this.floored = absoluteVector.floored()
                                ^

TypeError: absoluteVector.floored is not a function
    at new Location (C:\Users\kenny\node_modules\mineflayer\lib\location.js:7:33)
    at Bot.blockAt (C:\Users\kenny\node_modules\mineflayer\lib\plugins\blocks.js:89:17)
    at dig (C:\Users\kenny\Desktop\cosmic pvp mining bot\bot\index.js:81:22)
    at Bot.<anonymous> (C:\Users\kenny\Desktop\cosmic pvp mining bot\bot\index.js:158:5)
    at Bot.emit (events.js:189:13)
    at checkForChatPatterns (C:\Users\kenny\node_modules\mineflayer\lib\plugins\chat.js:44:80)
    at Client.bot._client.on (C:\Users\kenny\node_modules\mineflayer\lib\plugins\chat.js:56:5)
    at Client.emit (events.js:189:13)
    at FullPacketParser.deserializer.on (C:\Users\kenny\node_modules\minecraft-protocol\src\client.js:82:12)
    at FullPacketParser.emit (events.js:189:13)

Has something to do with

bot.entity.position

**Comment by KenWa51** [comment]
nevermind not sure how to close this lmao

**Comment by KenWa51** [comment]
BTW
something simple that could be added is logging in with session ids

**Comment by rom1504** [comment]
Yes there's an issue for this in node-minecraft-protocol.
Feel free to contribute
