### ISSUE TITLE
Mineflayer not working (at all)

### ISSUE THREAD

**Issue by Chrisstar56** [PrismarineJS/mineflayer#815]
## Versions
 - mineflayer: 2.8.1
 - server: vanilla/spigot/paper: 1.12 (probably not version specific)
 - node: 10.15.3

## Detailed description of a problem
I cannot start mineflayer and always get the same error message at mineflayer.createBot (even default example). It seems to happen before the connection is established

## Current code
```js
var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
  host: "...", // optional
  port: 25565,       // optional
  username: "...", // email and password are required only for
  password: "...",          // online-mode=true servers,
  version: "1.12.2"
});
bot.on('chat', function(username, message) {
  if (username === bot.username) return;
  bot.chat(message);
});
```

## Error Message

```
internal/validators.js:130
    throw new ERR_INVALID_ARG_TYPE(name, 'number', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "msecs" argument must be of type number. Received type object
    at validateNumber (internal/validators.js:130:11)
    at validateTimerDuration (internal/timers.js:146:3)
    at TLSSocket.Socket.setTimeout (net.js:405:11)
    at setRequestSocket (_http_agent.js:361:10)
    at handleSocketCreation_Inner (_http_agent.js:349:7)
    at oncreate (_http_agent.js:224:5)
    at Agent.createSocket (_http_agent.js:229:5)
    at Agent.addRequest (_http_agent.js:185:10)
    at new ClientRequest (_http_client.js:249:16)
    at Object.request (https.js:281:10)
```

## Additional context
The exact used to work a few months prior, I suspect it has to do with a new node version, although I am using LTS.

**Comment by Chrisstar56** [comment]
Problem disappeared on it's own
