### ISSUE TITLE
Error: read ECONNRESET     at TCP.onStreamRead (internal/stream_base_commons.js:111:27)

### ISSUE THREAD

**Issue by Nukestye** [PrismarineJS/mineflayer#817]
## Versions
 - mineflayer: Latest
 - server:  Its a faction server so its moded?
 - node: Latest

## Detailed description of a problem
I'm trying to get the bot to send a messsage every so often, however it keeps on giving the error or not sending it at all.
I've looked online to see what I can use as a reference point for my issue but haven't found anything yet.

## Current code
```js
minecraftBot.chatAddPattern(/(.*) (.*)/, 'chat', 'Public Chat') // (.*)?  (.*)  -  ^(?:[^]*\] )?([^ »]*) ? (.*)»(.*)$
minecraftBot.chatAddPattern(/^\[ ?([^ ]*) -> me ?] (.*)$/, 'whisper', 'Factions whisper') // Skyblock


discordBot.on("message", async message => {
	if(message.author.bot) return; // Checks if the msg is sent by a user
  if(message.channel.type == "dm") return message.reply("No Commands in DMS!"); // Checks if the msg is sent in channels, not DMS
  let prefix = config.prefix;
  let messageArry = message.content.split(" ");
  let cmd = messageArry[0];
  let args = messageArry.slice(1);
	if(cmd[0] != config.prefix) return;
  // '!say Hello' => '!say' being the cmd, while 'Hello' being the args
  let cmdfiles = bot.commands.get(cmd.slice(prefix.length));
  if (cmdfiles) cmdfiles.run(bot,message,args);
});


minecraftBot.on('message', (username, message, type, rawMessage, matches) => {
	var walls = "↬ ✘ Hi ✘"
	setInterval(function() {
		minecraftBot.chat(walls);
	}, 60000);
});

minecraftBot.on('chat', (username, message, type, rawMessage, matches) => {
  if (username === minecraftBot.username) return;
  //console.log('Chat received!')
  console.log(`${username} ${message}`)
	discordBot.guilds.get("Server Id").channels.get("Channel Id").send("`"+`${username} ${message}`+"`") // Showing you where the IDS will be,
```

## Expected behavior
The bot would send the message in `walls` every `60000` however it sends it once & gives the error
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at Client.self._client.on (C:\Users\nukestye\Desktop\discordBot\test_Bot\node_modules\mineflayer\index.js:93:12)
    at Client.emit (events.js:189:13)
    at Socket.onFatalError (C:\Users\nukestye\Desktop\discordBot\test_Bot\node_modules\minecraft-protocol\src\client.js:139:12)
    at Socket.emit (events.js:194:15)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19
```

**Comment by rom1504** [comment]
The error is "unhandled error event", so handle the error event ;)

Add something like bot.on('error', err=> console.log(err))

**Comment by Nukestye** [comment]
Well I did did what you said added `minecraftBot.on('error', err => console.log(err))` & it outputs this error
```js
{ Error: write ECONNRESET
    at afterWriteDispatched (internal/stream_base_commons.js:78:25)
    at writeGeneric (internal/stream_base_commons.js:73:3)
    at Socket._writeGeneric (net.js:704:5)
    at Socket._write (net.js:716:8)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at Cipheriv.ondata (_stream_readable.js:689:20)
    at Cipheriv.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'write' }
```
& the same thing happens. The account gets kicked?

**Comment by rom1504** [comment]
yes

**Comment by rom1504** [comment]
```
minecraftBot.on('message', (username, message, type, rawMessage, matches) => {
	var walls = "↬ ✘ Hi ✘"
	setInterval(function() {
		minecraftBot.chat(walls);
	}, 60000);
});
```
this makes the bot spam (send N messages every 60s with N the number of messages received till that point). Are you sure you want to use setInterval (which trigger every 60s) and not setTimeout (which trigger once after 60s) ?

**Comment by Nukestye** [comment]
I fixed it somehow, rather then putting the `setInterval` in message I put it in login, which triggers it from the start.

Also I have tried using `SetTimeout` it was the same error...
Thanks for your help 👍

**Comment by wvffle** [comment]
please, show us your current code

**Comment by Nukestye** [comment]
```js

minecraftBot.on('error',err => {
	console.log(err)
});

/*
 * The chat event returns username as the first regex match and message as the second match
 * type argument is only used for server event messages like player joining, player disconnected, etc.
 * rawMessage is the JSON object (vanillia) or the raw string (spigot/bukkit/other) the server sent.
 * matches is the regex.matches object containing all matches
 */

//minecraftBot.once()

minecraftBot.on('whisper', (username, message, rawMessage) =>{
	minecraftBot.whisper(username, `${message} Back to you!`)
})





minecraftBot.on('login', (username, message, type, rawMessage, matches) => {	
	minecraftBot.chat('/f join Envision')
	var walls = "↬ ✘ ᴄʜᴇᴄᴋ ᴡᴀʟʟs ✘ - DM @ภยкเภคt๏г#4595 .check once done"
	setInterval(function() {
		minecraftBot.chat('/f c f')
		minecraftBot.chat(walls);
	}, 60000);
});



minecraftBot.on('kicked', (reason) => {
  console.log(`I got kicked for ${reason}`)
})

minecraftBot.on('chat', (username, message, type, rawMessage, matches) => {
  if (username === minecraftBot.username) return;
  //console.log('Chat received!')
  console.log(`${username} ${message}`)
	discordBot.guilds.get("573602053352456193").channels.get("574703944140324864").send("`"+`${username} ${message}`+"`")
	//console.log(`${username} » ${message} `);

	
	
	

  /*
   * Using the matches object, you could get the same output using
   * console.log("Username: " + matches[1]); and
   * console.log("Message: " + matches[2]);
   */
})



// Bot logs in using the token from config file.
discordBot.login(config.token);
```

Here

**Comment by rom1504** [comment]
yeah that seems to make sense.

good that it's fixed

**Comment by GanskeMC** [comment]
Hey, 
My friend is having an issue upon loading Minecraft which I don't really understand:
![image](https://user-images.githubusercontent.com/63660106/180662731-d5e61dda-ef6b-4d5a-94e1-3580500e947a.png)
I don't suppose you could help?
Thanks,
Ganske
