### ISSUE TITLE
TypeError: Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by Wqrld** [PrismarineJS/mineflayer#821]
```
TypeError: Cannot read property 'remove' of undefined
    at Client.bot._client.on (/root/bot/node_modules/mineflayer/lib/plugins/scoreboard.js:37:28)
    at emitTwo (events.js:126:13)
    at Client.emit (events.js:214:7)
    at FullPacketParser.deserializer.on (/root/bot/node_modules/minecraft-protocol/src/client.js:82:12)
    at emitOne (events.js:116:13)
    at FullPacketParser.emit (events.js:211:7)
    at addChunk (/root/bot/node_modules/readable-stream/lib/_stream_readable.js:301:12)
    at readableAddChunk (/root/bot/node_modules/readable-stream/lib/_stream_readable.js:283:11)
    at FullPacketParser.Readable.push (/root/bot/node_modules/readable-stream/lib/_stream_readable.js:247:10)
    at FullPacketParser.Transform.push (/root/bot/node_modules/readable-stream/lib/_stream_transform.js:149:32)

```

node v8.11.2
newest mineflayer
server 1.8.8
Happens when joining a server with featherboard, it stops new bots from joining the server

**Comment by wvffle** [comment]
It's been fixed in mineflayer 2.8.1. Please check your mineflayer version.
