### ISSUE TITLE
Proxy Support doesn't work.

### ISSUE THREAD

**Issue by peter12908** [PrismarineJS/mineflayer#827]
I am trying to use a Proxy with my Bot but it doesn't work.
Here's my Code:
```
var Http = require("http");
var minecraft = { host: "858585.aternos.me", port: 25565 };
var proxy = { host: '94.153.169.22', port: 59177 };
var req = Http.request({
  host: proxy.host,
  port: proxy.port,
  method: 'CONNECT',
  path: minecraft.host + ":" + minecraft.port
});
req.on("connect", function(res, stream, head) {
  require("minecraft-protocol").createClient({
    stream: stream,
    username: "proxy",
    //password: "bleh"
  });
});
```

And here is the Ouput:
```
E:\peter\NodeJS\Proxy Bot>node index.js
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketOnEnd (_http_client.js:426:23)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Socket.socketOnEnd (_http_client.js:426:9)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Comment by rom1504** [comment]
are you banned ?

**Comment by peter12908** [comment]
no i tried 20 different proxies and it didn't work

**Comment by rom1504** [comment]
Can you connect without a proxy ?

**Comment by peter12908** [comment]
yes

**Comment by rom1504** [comment]
Ok, did you use an http proxy that support CONNECT ?
if not, try to use a sock proxy instead (see socks example)
