### ISSUE TITLE
no support for invadedlands.net

### ISSUE THREAD

**Issue by CatC3r** [PrismarineJS/mineflayer#836]
I know this might have been covered elsewhere and I might have posted it in the wrong section but I'm new to this so I don't know well. My issue is that when I try to join a server: "invadedlands.net" it Works just after 2 seconds I get this error:

```
TypeError: Cannot read property 'id' of undefined
    at confirmTransaction (c:\Users\tvynj\Desktop\mineflayer-1\node_modules\mineflayer\lib\plugins\inventory.js:452:21)
    at Client.bot._client.on (c:\Users\tvynj\Desktop\mineflayer-1\node_modules\mineflayer\lib\plugins\inventory.js:564:5)
    at Client.emit (events.js:189:13)
    at FullPacketParser.deserializer.on (c:\Users\tvynj\Desktop\mineflayer-1\node_modules\minecraft-protocol\src\client.js:82:12)
    at FullPacketParser.emit (events.js:189:13)
    at addChunk (c:\Users\tvynj\Desktop\mineflayer-1\node_modules\readable-stream\lib\_stream_readable.js:297:12)
    at readableAddChunk (c:\Users\tvynj\Desktop\mineflayer-1\node_modules\readable-stream\lib\_stream_readable.js:279:11)
    at FullPacketParser.Readable.push (c:\Users\tvynj\Desktop\mineflayer-1\node_modules\readable-stream\lib\_stream_readable.js:240:10)
    at FullPacketParser.Transform.push (c:\Users\tvynj\Desktop\mineflayer-1\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at FullPacketParser._transform (c:\Users\tvynj\Desktop\mineflayer-1\node_modules\protodef\src\serializer.js:81:10)
```

The server itself is for 1.8 and 1.7. I'm using 1.8.9. This is my code: 
```const mineflayer = require('mineflayer')
var owner = 'XP20TOMS';
const bot = mineflayer.createBot({
	host: "invadedlands.net",
	port: 25565,
username: "", // email and password are required only for
  password: "",          // online-mode=true servers
	version: "1.8",
})

bot.on('chat', function(username, message) {
	console.log(message);
	
});

bot.on('whisper', (username, message, rawMessage) => {
  console.log(`I received a message from ${username}: ${message}`)
	if (message == 'help') {bot.whisper(username, 'owner - shows the owner of the bot')}
	else if (message == 'owner') {bot.whisper(username, 'The owner of this bot is: ' + owner)}
	else {bot.whisper(username, 'Unknown command! Type help for a list of commands.')}

})

bot.on('login', function() {
	
	console.log(bot.username + " joined the server!")
})

//bot.on('message', (username, message) => {
//	console.log(username + " Sent: " + message)
//})
```

And I have the email and password there and they work!

Edit: I tested it also on another server and it worked. But I need just that server

**Comment by 1by** [comment]
I have a fix for it but its kinda hacky,
Go in inventory.js file and comment out every time confirmTransaction() is called.

**Comment by rom1504** [comment]
We did many changes, could you reopen if you still observe that issue?
