### ISSUE TITLE
"SyntaxError: Unexpected token" when mineflayer trying parse tablist header

### ISSUE THREAD

**Issue by hexatester** [PrismarineJS/mineflayer#837]
## Versions
 - mineflayer: 2.9.0
 - server: spigot 1.12.2
 - offline-mode: true
 - node: v10.15.3

## Detailed description of a problem
"SyntaxError: Unexpected token" when mineflayer trying parse tablist

## Current code
```js
var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
	host: 'play.wheelcraft-id.net',
	port: 25565,
	username: 'heracless',
	version: "1.12.2",
	verbose: true
});
bot.once('login', () => {
	console.log(bot.username);
	bot.chat('/login password');
	console.log("OK")
})
bot.on('error', err => console.log(err))
```

## Expected behavior
heracless
OK

## Ouput
```
heracless
undefined:1
{"text":"","extra":[{"text":"Wheel","color":"dark_red","bold":"true"},{"text":"Craft ","color":"white","bold":"true"},{"text":"Indonesia


SyntaxError: Unexpected token
 in JSON at position 136
    at JSON.parse (<anonymous>)
    at Client.bot._client.on (D:\Projects\minebot\node_modules\mineflayer\lib\plugins\tablist.js:13:49)
    at Client.emit (events.js:189:13)
    at FullPacketParser.deserializer.on (D:\Projects\minebot\node_modules\minecraft-protocol\src\client.js:82:12)
    at FullPacketParser.emit (events.js:189:13)
    at addChunk (D:\Projects\minebot\node_modules\readable-stream\lib\_stream_readable.js:297:12)
    at readableAddChunk (D:\Projects\minebot\node_modules\readable-stream\lib\_stream_readable.js:279:11)
    at FullPacketParser.Readable.push (D:\Projects\minebot\node_modules\readable-stream\lib\_stream_readable.js:240:10)
    at FullPacketParser.Transform.push (D:\Projects\minebot\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at FullPacketParser._transform (D:\Projects\minebot\node_modules\protodef\src\serializer.js:81:10)```

**Comment by rom1504** [comment]
looks like your server is broken. Can you reproduce anywhere else ?

**Comment by wvffle** [comment]
Can you provide a screenshot of the tablist?

**Comment by hexatester** [comment]
@wvffle 
Screenshot [Imgur](https://imgur.com/a/dUzpSp8)

**Comment by rom1504** [comment]
What about my question ?

**Comment by wvffle** [comment]
Hmmm, could it be a `\n` character in the header?

Possible to `.replace('\n', '\\n')` inside `JSON.parse`

**Comment by wvffle** [comment]
Well, the replace function should be called on the fields

![](https://i.imgur.com/i1hzbPF_d.webp?maxwidth=640&shape=thumb&fidelity=medium)

**Comment by hexatester** [comment]
@rom1504 i don't know, yet.

**Comment by hexatester** [comment]
> Hmmm, could it be a `\n` character in the header?
> 
> Possible fix is to `.replace('\n', '\\n')` inside `JSON.parse`

I'll try it.

**Comment by wvffle** [comment]
Much more correct fix is to replace `\n` only in values of `packet.header` and `packet.footer`

```js
const escapeValueNewlines = str => {
  return str.replace(/": *"([^"]+)/, (_, match) => '":"' + match.replace('\n', '\\n'))
}
```
