### ISSUE TITLE
AssertionError [ERR_ASSERTION]: item with id 4809 not found

### ISSUE THREAD

**Issue by egeres** [PrismarineJS/mineflayer#840]
I'm connecting a mineflayer bot to a forge server with many mods installed. Node crashes a while after the bot walks around the world. It seems that this issue might be caused when a player holds a certain item from a mod.

**Comment by rom1504** [comment]
What's the full error

**Comment by egeres** [comment]
assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: item with id 4809 not found
    at new Item (D:\Users\...\Desktop\doggo\node_modules\prismarine-item\index.js:28:10)
    at Function.Item.fromNotch (D:\Users\...\Desktop\doggo\node_modules\prismarine-item\index.js:81:12)
    at Client.bot._client.on (D:\Users\...\Desktop\doggo\node_modules\mineflayer\lib\plugins\entities.js:78:57)
    at Client.emit (events.js:182:13)
    at FullPacketParser.deserializer.on (D:\Users\...\Desktop\doggo\node_modules\minecraft-protocol\src\client.js:82:12)
    at FullPacketParser.emit (events.js:182:13)
    at addChunk (D:\Users\...\Desktop\doggo\node_modules\readable-stream\lib\_stream_readable.js:297:12)
    at readableAddChunk (D:\Users\...\Desktop\doggo\node_modules\readable-stream\lib\_stream_readable.js:279:11)
    at FullPacketParser.Readable.push (D:\Users\...\Desktop\doggo\node_modules\readable-stream\lib\_stream_readable.js:24
0:10)
    at FullPacketParser.Transform.push (D:\Users\...\Desktop\doggo\node_modules\readable-stream\lib\_stream_transform.js:
139:32)

**Comment by rom1504** [comment]
Ok do a pr for prismarine-item to allow unknown items

**Comment by egeres** [comment]
PR is done !
I changed `assert.ok(itemEnum, 'item with id ' + type + ' not found')`  by an if statement that sets the values to something neutral in case the item doesn't exists. With this tweak my bot doesn't crash anymore.
