### ISSUE TITLE
Error when mining sugarcane (happens rarely)

### ISSUE THREAD

**Issue by GoogleSites** [PrismarineJS/mineflayer#857]
```
F:\Minecraft\MinerBot\node_modules\mineflayer\lib\plugins\digging.js:87
      bot.blockAt(bot.entity.position).type === 9, !bot.entity.onGround) // only stationary water counts
                                      ^

TypeError: Cannot read property 'type' of null
    at Bot.digTime (F:\Minecraft\MinerBot\node_modules\mineflayer\lib\plugins\digging.js:87:39)
    at bot.lookAt (F:\Minecraft\MinerBot\node_modules\mineflayer\lib\plugins\digging.js:19:28)
    at Bot.checkYaw (F:\Minecraft\MinerBot\node_modules\mineflayer\lib\plugins\physics.js:355:9)
    at Bot.emit (events.js:197:13)
    at sendPositionAndLook (F:\Minecraft\MinerBot\node_modules\mineflayer\lib\plugins\physics.js:251:9)
    at Timeout.sendPosition [as _onTimeout] (F:\Minecraft\MinerBot\node_modules\mineflayer\lib\plugins\physics.js:294:7)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)```

**Comment by rom1504** [comment]
You're trying to dig a null block
We should have more type checking in functions

**Comment by GoogleSites** [comment]
I have a check to make sure the block isn't air before mining it

**Comment by rom1504** [comment]
no the block you are mining is not air, it's `null` (ie you have a bug)

**Comment by GoogleSites** [comment]
```
function mineCane() {
  return new Promise(async (resolve) => {
    const blocks = [bot.blockAt(bot.entity.position.offset(0, 1, 0)), bot.blockAt(bot.entity.position.offset(0, 1, -1)), bot.blockAt(bot.entity.position.offset(0, 1, -3)), bot.blockAt(bot.entity.position.offset(0, 1, -4))];

    for (let i = 0; i < blocks.length; i++) {
      try {
        if (blocks[i].name === 'reeds') {
          await dig(blocks[i]);
          await wait(25);
        }
      } catch(e) {}
    }

    resolve();
  });
}```

is what I'm currently using. It will only mine the block if it's sugarcane - so it can never be null
