### ISSUE TITLE
How to use mineflayer with http proxys

### ISSUE THREAD

**Issue by peter12908** [PrismarineJS/mineflayer#883]
I googled for like 2 hours and found nothing helpful
Then only thing i got is:
`
var Http = require("http");
var minecraft = { host: "158.58.xxx.xxx", port: 25565 };
var proxy = { host: '82.113.xxx.xxx', port: 33915 };
var req = Http.request({
  host: proxy.host,
  port: proxy.port,
  method: 'CONNECT',
  path: minecraft.host + ":" + minecraft.port
});
req.on("connect", function(res, stream, head) {
  require("minecraft-protocol").createClient({
    stream: stream,
    username: "proxy",
  });
});

`
but that doesn't work...

**Comment by rom1504** [comment]
You need to use require('https')
And your proxy need to support CONNECT method (highly unlikely)

**Comment by peter12908** [comment]
hmm okay is there any other method to use http (https) proxies?

**Comment by rom1504** [comment]
If the proxy doesn't support CONNECT then no.
Use a socks proxy

**Comment by peter12908** [comment]
hmm i know that there is relly nice socks5-client but is there also an socks4-client?

**Comment by rom1504** [comment]
Most likely yes

**Comment by peter12908** [comment]
So i have found a libary that support socks v4 and v5 and now i am trying to connect to the minecraft server but i always get an error
Code:
`
var Socks = require("socks");
var mineflayer = require('mineflayer');

const options = {
      proxy: {
        host: "87.197.163.118",
        port: 4145,
        type: 4 // Proxy version (4 or 5)
      },

      command: 'connect',
	  
	  destination: {
		host: '158.58.173.241',
		port: 25565
	  }
    };
Socks.createConnection(options, (err, info) => {
    var bot = mineflayer.createBot({
		host: "158.58.173.241",
        port: 25565,
        username: "user",
        version: "1.8",
        keepAlive: true
    })
});
`
Error:
`TypeError: Socks.createConnection is not a function`

**Comment by peter12908** [comment]
ok fixed the problem problem was i forgot to write Socks.SocksClient.createConnection(options, (err, info) => {

**Comment by rom1504** [comment]
Look at the proxy example

**Comment by peter12908** [comment]
hmm idk why but the bot doesn't connect over the proxy it connects over my ip

**Comment by peter12908** [comment]
which proxy example? for mineflayer there's no proxy example

**Comment by rom1504** [comment]
Look at node-minecraft-protocol proxy example you need to do exactly the
same for mineflayer

**Comment by peter12908** [comment]
still havn't gotten any further could u pls send me how to use it in mineflayer?

**Comment by rom1504** [comment]
Put this in the option of createBot
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_socks_proxy/client_socks_proxy.js#L13

**Comment by peter12908** [comment]
Ok did it but now i get following error: TypeError: this.socket.on is not a function

**Comment by peter12908** [comment]
I got an Error: E:\peter\NodeJS\Proxy Bot>node index.js
E:\peter\NodeJS\Proxy Bot\node_modules\socks\build\common\helpers.js:14
        throw new util_1.SocksClientError(constants_1.ERRORS.InvalidSocksCommand, options);
        ^

Error: An invalid SOCKS command was provided. Valid options are connect, bind, and associate.
    at Object.validateSocksClientOptions (E:\peter\NodeJS\Proxy Bot\node_modules\socks\build\common\helpers.js:14:15)
    at Function.createConnection (E:\peter\NodeJS\Proxy Bot\node_modules\socks\build\client\socksclient.js:39:19)
    at Object.connect (E:\peter\NodeJS\Proxy Bot\index.js:5:23)
    at module.exports (E:\peter\NodeJS\Proxy Bot\node_modules\minecraft-protocol\src\client\auth.js:57:13)
    at Object.createClient (E:\peter\NodeJS\Proxy Bot\node_modules\minecraft-protocol\src\createClient.js:36:3)
    at Bot.connect (E:\peter\NodeJS\Proxy Bot\node_modules\mineflayer\index.js:84:23)
    at Object.createBot (E:\peter\NodeJS\Proxy Bot\node_modules\mineflayer\index.js:72:7)
    at Object.<anonymous> (E:\peter\NodeJS\Proxy Bot\index.js:3:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

**Comment by rom1504** [comment]
What code are you running

**Comment by peter12908** [comment]
const client = mc.createClient({
  connect: client => {
    socks.SocksClient.createConnection({
      proxy: {
        ipaddress: "87.197.163.118",
        port: 4145,
        type: 4
      },
      target: {
        host: "136.243.78.43",
        port: 25590
      }
    }, function (err, socket) {
      if (err) {
        console.log(err)
        return
      }

      client.setSocket(socket)
      client.emit('connect')
    })
  },
  username: 'testuser'
})

**Comment by peter12908** [comment]
Do u know how to fix the error?

**Comment by rom1504** [comment]
Yes follow that example
https://github.com/PrismarineJS/node-minecraft-protocol/blob/master/examples/client_socks_proxy/client_socks_proxy.js

You are using the wrong socks package

**Comment by peter12908** [comment]
i am using the right one

**Comment by rom1504** [comment]
Ok what error are you getting with this code ?

**Comment by peter12908** [comment]
I got an Error: E:\peter\NodeJS\Proxy Bot>node index.js
E:\peter\NodeJS\Proxy Bot\node_modules\socks\build\common\helpers.js:14
throw new util_1.SocksClientError(constants_1.ERRORS.InvalidSocksCommand, options);
^

Error: An invalid SOCKS command was provided. Valid options are connect, bind, and associate.
at Object.validateSocksClientOptions (E:\peter\NodeJS\Proxy Bot\node_modules\socks\build\common\helpers.js:14:15)
at Function.createConnection (E:\peter\NodeJS\Proxy Bot\node_modules\socks\build\client\socksclient.js:39:19)
at Object.connect (E:\peter\NodeJS\Proxy Bot\index.js:5:23)
at module.exports (E:\peter\NodeJS\Proxy Bot\node_modules\minecraft-protocol\src\client\auth.js:57:13)
at Object.createClient (E:\peter\NodeJS\Proxy Bot\node_modules\minecraft-protocol\src\createClient.js:36:3)
at Bot.connect (E:\peter\NodeJS\Proxy Bot\node_modules\mineflayer\index.js:84:23)
at Object.createBot (E:\peter\NodeJS\Proxy Bot\node_modules\mineflayer\index.js:72:7)
at Object. (E:\peter\NodeJS\Proxy Bot\index.js:3:26)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

**Comment by rom1504** [comment]
No that's when using your code which is incorrect.
Can you try with the code from the example ?

**Comment by peter12908** [comment]
When i use the code from the example i get following error:

E:\peter\NodeJS\TheAlteningBot\index.js:69
      socks.createConnection({
            ^

TypeError:socks.createConnection is not a function
    at Object.connect (E:\peter\NodeJS\TheAlteningBot\index.js:69:13)
    at cb (E:\peter\NodeJS\TheAlteningBot\node_modules\minecraft-protocol\src\client\auth.js:20:17)
    at E:\peter\NodeJS\TheAlteningBot\node_modules\yggdrasil\lib\Client.js:35:5
    at E:\peter\NodeJS\TheAlteningBot\node_modules\yggdrasil\lib\utils.js:35:7
    at IncomingMessage.<anonymous> (E:\peter\NodeJS\TheAlteningBot\node_modules\phin\lib\phin.compiled.js:1:2162)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by rom1504** [comment]
Ok that means you are not using the correct socks package.
Use the one of the example (check its package.json to see the exact name)

**Comment by B4RC0DE-TM** [comment]
Hope this helps... n Hello Peter 😳🙌


var Socks  = require("socks5-client");
var proxy = { host: 'proxyip', port: 1080 };

var mineflayer = require('mineflayer');
mineflayer.createBot({
  stream: Socks.createConnection({
    host: process.argv[2],
    port: parseInt(process.argv[3]),
    socksHost: proxy.host,
    socksPort: proxy.port
  }),
  username: "player",
  password: ""
})
****
