### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by ufilme** [PrismarineJS/mineflayer#930]
## Versions
 - mineflayer: 2.11.0
 - server: forge 1.12.2
 - node: 10.15.2

## Detailed description of a problem
Once the bot logs into the server it doesn't respond to chat commands and then he bot quit the server and this error occurs.
```
{ Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:782:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
{ Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:782:14) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }
```

## Current code
```js
var mineflayer = require('mineflayer');
var bot = mineflayer.createBot({
  host: "ip", // optional
  port: 25565,       // optional
  username: "Bot", // email and password are required only for
  //password: "12345678",          // online-mode=true servers
  version: false                 // false corresponds to auto version detection (that's the default), put for example "1.8.8" if you need a specific version
});
var autoVersionForge = require('minecraft-protocol-forge').autoVersionForge;
autoVersionForge(bot._client);
console.log("loaded");
bot.on('chat', function(username, message) {
  console.log("ok");
  if (username === bot.username) return;
  if (message == "jump")
    bot.setControlState('jump', true);
  else if (message == "stop jump")
    bot.setControlState('jump', false);
});
bot.on('error', err => console.log(err));
```

## Expected behavior
The bot should start jumping

**Comment by rom1504** [comment]
This error means you are got kicked, do you get the same thing on another
server?

**Comment by pippognetow** [comment]
Got the same error on localhost

![image](https://user-images.githubusercontent.com/32271330/77794645-877b3900-706c-11ea-8d6b-e8d23125b8f4.png)

**Comment by rom1504** [comment]
Try without forge

**Comment by pippognetow** [comment]
No problem on a non-forge server

**Comment by rom1504** [comment]
So the problem is with node minecraft forge. Try to debug it

**Comment by pippognetow** [comment]
How?

**Comment by rom1504** [comment]
for example by trying to add some console.log in the code (
https://github.com/PrismarineJS/node-minecraft-protocol-forge)
