### ISSUE TITLE
Cannot read property "type" of undefined

### ISSUE THREAD

**Issue by werymanen** [PrismarineJS/mineflayer#951]
## Versions
 - mineflayer: ^2.11.0
 - server: vanilla lan world 1.12.2
 - node: v13.12.0

## Detailed description of a problem
I am currently working on a bot that is going to put an item in a chest. But when I try to run the command, it navigates to the chest, opens it, crashes, and drops the item on the floor. The error:
```
node_modules/minecraft-protocol/src/transforms/framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read property 'type' of undefined
    at clickDest (/media/manen/PROGRAMMING/botnet/node_modules/mineflayer/lib/plugins/inventory.js:264:51)
    at /media/manen/PROGRAMMING/botnet/node_modules/mineflayer/lib/plugins/inventory.js:256:13
    at Bot.<anonymous> (/media/manen/PROGRAMMING/botnet/node_modules/mineflayer/lib/plugins/inventory.js:524:9)
    at Object.onceWrapper (events.js:422:26)
    at Bot.emit (events.js:315:20)
    at onAccepted (/media/manen/PROGRAMMING/botnet/node_modules/mineflayer/lib/plugins/inventory.js:474:11)
    at confirmTransaction (/media/manen/PROGRAMMING/botnet/node_modules/mineflayer/lib/plugins/inventory.js:464:7)
    at Client.<anonymous> (/media/manen/PROGRAMMING/botnet/node_modules/mineflayer/lib/plugins/inventory.js:568:5)
    at Client.emit (events.js:315:20)
    at FullPacketParser.<anonymous> (/media/manen/PROGRAMMING/botnet/node_modules/minecraft-protocol/src/client.js:87:12)
```

## Current code
```js
        const chestLoc = vec3(-324, 72, 253);
        const path = bot.navigate.findPathSync(vec3(-323, 72, 253));
        bot.navigate.walk(path.path, reason => {
            res("Got to the chest"); // res is basically bot.chat
            const chest = bot.openChest(bot.blockAt(chestLoc));

            chest.on("open", () => {
                chest.deposit(2, null, 1, err => {
                    if (err) console.log(err);
                });
            });
        });
```

## Expected behavior
I expect it to open the chest, and put in the grass block.

**Comment by rom1504** [comment]
could you have a look @Karang ? it looks like a consequence of recent changes

**Comment by Karang** [comment]
Mineflayer 2.11.0 is from feb 8, can you try with the 2.12.0 which was released yesterday ?
The useChest.js test is working and does basically what you need.

**Comment by rom1504** [comment]
ahhh good point I did not notice it wasn't from the last version

**Comment by werymanen** [comment]
Thank you, updating worked.

**Comment by rom1504** [comment]
Great
